### ISSUE TITLE
[docs] : update ansible-galaxy installation instructions for each role

### ISSUE THREAD

**Issue by nqb** [debops/debops#1015]
All roles have an "Installation" section with a `ansible-galaxy` command. This command need to be replace by `mazer install debops.debops`

**Comment by nqb** [comment]
On top of that, examples playbooks need to be update because we need to use `debops.debops.role_name` in place of `debops.role_name`.

**Comment by drybjed** [comment]
I would just remove these 'Installation' sections altogether. The 'Introduction' sections can be moved to the `index.rst` files, see for example `debops.apt_mark` role documentation.

**Comment by drybjed** [comment]
Example playbooks are the actual playbooks used by DebOps, so they cannot be modified until [Ansible Galaxy fixes its role dpendencies support](https://github.com/ansible/galaxy/issues/1938).

**Comment by nqb** [comment]
> Example playbooks are the actual playbooks used by DebOps, so they cannot be modified until [Ansible Galaxy fixes its role dpendencies support](https://github.com/ansible/galaxy/issues/1938).

I understand, I forgot this issue.

**Comment by nqb** [comment]
In Ansible 2.9, `ansible-galaxy` command will support installing Ansible collections.

**Comment by gentoo9ball** [comment]
Any update on guidance here? I'd love to use debops directly from ansible, but this is holding everything up without manually editing all the dependencies. I've been through many bug reports here and on the ansible repository, but I haven't seen a clear work-around or guidance.

Are you guys waiting on ansible to clean their galaxy mess up?

edit: Kind of dirty, but got it to work by cloning and placing the debops/ansible/roles/* in ~/.ansible/roles/.
     How bad is this? :)

**Comment by drybjed** [comment]
I plan to rename all of the DebOps roles and drop the `debops.` prefix from them; this should improve support for the Ansible Galaxy installation. I tried to do that once before, but updating all references in the documentation was more time-consuming that I liked. Therefore I'll just try to do as minimal changes as possible and leave the `debops.` prefix in the documentation for now.

The DebOps v2.0.0 release is planned for the end of January 2020, so I'll try to do it this month, after I get from holiday break in about a week.

**Comment by SuperSandro2000** [comment]
Shouldn't be that hard if you use find and replace.

**Comment by drybjed** [comment]
The installation instructions have been removed from the role documentation, and DebOps is now fully supported on Ansible Galaxy. Closing issue.
