### ISSUE TITLE
[debops.users] Ubuntu16 - Can not add groups as /etc/libuser.conf is missing 

### ISSUE THREAD

**Issue by alinalexandru** [debops/debops#1044]

**Comment by alinalexandru** [comment]
@drybjed 
What solution do you think is the best one?

1. Can we just create an empty file if /etc/libuser.conf is missing
1. Can we put a default one?
1. Install libuser only in certain cases

I saw that 3 roles are affected by the libuser package.

**Comment by drybjed** [comment]
I think that because that's already 3 roles, a separate `debops.libuser` role will be better than putting relevant configuration into the separate roles themselves. So I'll work on it soon, I'll try to add it before the end of October.
