### ISSUE TITLE
[docs] Edit on GitHub link will never work for defaults

### ISSUE THREAD

**Issue by nqb** [debops/debops#1047]
When you want to edit defaults from a role by using "Edit on GitHub" from http://docs.debops.org, you got a 404.

### Steps to reproduce
1. Go in https://docs.debops.org/en/master/ansible/roles/debops.nsswitch/defaults/main.html
2. Click on "Edit on GitHub"

### Actual results
You got a 404 error from GitHub, unable to open: https://github.com/debops/debops/blob/master/docs/ansible/roles/debops.nsswitch/defaults/main.rst

### Expected results
Redirected to https://github.com/debops/debops/blob/master/ansible/roles/debops.nsswitch/defaults/main.yml (or directory if several `*.yml` files are present)

**Comment by drybjed** [comment]
Good catch. The script that generates the defaults needs to be updated. I'm not sure when that stopped working, perhaps even way back when the documentation was moved to the monorepo? I'll check it out.
