### ISSUE TITLE
[Vagrant] debops installation broken

### ISSUE THREAD

**Issue by nqb** [debops/debops#1063]
```console
vagrant@debops-0c8a1c:~/src/controller$ debops common
Traceback (most recent call last):
  File "/usr/local/bin/debops", line 270, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/debops", line 204, in main
    require_commands(ANSIBLE-PLAYBOOK)
NameError: name 'ANSIBLE' is not defined
```
### Steps to reproduce
`vagrant up` on master branch

### Actual results
`debops` should start common playbook.

**Comment by nqb** [comment]
Related to https://github.com/debops/debops/pull/1054. If I reverted change introduce by this PR, it works as expected.

@htgoebel, any ideas ?

**Comment by nqb** [comment]
Got it: ANSIBLE-PLAYBOOK should be ANSIBLE_PLAYBOOK. Will provide a fix now.

**Comment by htgoebel** [comment]
Shame on me, this a really stupid error.

**Comment by nqb** [comment]
> Shame on me, this a really stupid error.

@htgoebel: nevermind, there are only people who didn't make changes that didn't make mistakes.
