### ISSUE TITLE
[debops.resolvconf] ansible_dns fact incorrect when using systemd-resolved 

### ISSUE THREAD

**Issue by DouglasHeriot** [debops/debops#1078]
When using `systemd-resolved` as the system DNS resolver (the default on Ubuntu 18.04), `/etc/resolv.conf` only lists `127.0.0.53` instead of the real DNS servers being used, as it hooks the `glibc` DNS functions instead.

This leads to the `debops.resolvconf` facts script to only retrieving `127.0.0.53` as the `nameserver` in `ansible_dns`
https://github.com/debops/debops/blob/master/ansible/roles/debops.resolvconf/templates/etc/ansible/facts.d/resolvconf.fact.j2

So what are the effects of this? `debops.docker_server` uses `ansible_dns` to fill in the `/etc/docker/daemon.json` file. But `systemd-resolved` will [only listen on `lo0` and not respond to requests from inside containers](https://unix.stackexchange.com/questions/445782/how-to-allow-systemd-resolved-to-listen-to-an-interface-other-than-loopback). This means none of my containers can talk to DNS.

I have fixed this by setting `docker_server__dns_nameserver` to `null` which prevents DNS servers from being listed in `daemon.json` at all so that Docker can work out how to handle this on its own (which it does by correctly).

So, do we need to work out how to fetch DNS servers correctly when using `systemd-resolved`? I haven't yet looked into how to do that.

**Comment by drybjed** [comment]
Yes, getting the nameservers `systemd-resolved` uses as upstream nameservers would be ideal. They hopefully are exposed somewhere in the filesystem from where the fact script could read them. Not sure yet where to look.

**Comment by DouglasHeriot** [comment]
It looks like you can find them in `/run/systemd/resolve/resolv.conf`
https://stackoverflow.com/a/51060649/466698
