### ISSUE TITLE
[LDAP] Planned major changes in the OpenLDAP ACLs

### ISSUE THREAD

**Issue by drybjed** [debops/debops#1110]
I would like to change the type of some objects created by default in an OpenLDAP installation from `groupOfNames` to `organizationalRole`. This involves modifications in the default OpenLDAP ACLs which might break installations if people are unaware of the changes needed.

The change comes from the fact that the `groupOfNames` object class requires at least one `member` attribute to be present, and the `organizationalRole` does not. This results in some of the objects in the LDAP directory, for example `cn=LDAP Replicators,ou=System Groups,dc=example,dc=org` to require at least one `member`, even if there are no replicators configured yet. And when the last `member` of a given group is deleted, the entry is not updated by the `refint` overlay because removing the `member` attribute would break the `groupOfNames` object consistency.

In comparsion, the `organizationalRole` object class does not enforce any `roleOccupant` attributes (equivalent to the `member` attribute) to be present, so we can have "roles" defined without anybody that performs them and no issues with directory consistency on removals. Additionally, `organizationalRole` has much more diverse set of attributes that can describe a role than `groupOfNames` which might be a plus.

Changing the object class will require modifications to the OpenLDAP ACLs to base the lookups on the new object attributes, changes in the `ldap/init-directory.yml` playbook which will create the new objects as well as additional indexes at least for `roleOccupant` and more attributes in the `refint` overlay configuration. Because this change is very intrusive and the LDAP directory structure will have to be carefully modified, I'll schedule it for the DebOps `v2.0.0` release. The migration process will be carefully planned and described in the upgrade notes - I think that first running the `ldap/init-directory` playbook and then applying the `debops.slapd` role LDAP tasks to change the ACLs should be enough, but that will have to be tested first.

Perhaps at the same time the objects in the `ou=System Groups,dc=example,dc=org` subtree could be moved to `ou=Groups,dc=example,dc=org`. After using the current set of ACLs and directory layout for a while I see some issues with using two separate sets of groups in various applications. This will probably require more rules to protect certain groups like `cn=LDAP Administrators`, but that might be beneficial in the long run.

**Comment by reixd** [comment]
I would also propose to improve the LDAP schema to allow user management belonging to different TLDs (Domains). For example by using the Person `uid` with an unique email and not just the `username`. Or put the Persons/Users inside domains, just like the Servers/Hosts.

**Comment by drybjed** [comment]
User management per domain is already possible - just create the separate `dNSdomain` objects under the `ou=People` object and put your users in those domains however you want. Various applications will use search filters to find the correct user object under `ou=People` subtree.

I wouldn't recommend using an e-mail address as the `uid=` value - this might not be supported everywhere `uid=` might be used, for example in shell accounts. DebOps roles that support LDAP are configured to lookup the user accounts using the `mail` attribute, so no matter if you specify the `uid` or `mail` address, you should be able to login to the same account.

**Comment by reixd** [comment]
> User management per domain is already possible - just create the separate `dNSdomain` objects under the `ou=People` object and put your users in those domains however you want. Various applications will use search filters to find the correct user object under `ou=People` subtree.

thx for the hint.
