### ISSUE TITLE
[debops.netbase] : several 127.0.1.1 entries cause issues

### ISSUE THREAD

**Issue by nqb** [debops/debops#1132]
Hello,

I bootstrapped a fresh VPS running Debian Buster with following `/etc/hosts` (before bootstrap):
```
127.0.0.1	localhost

::1	localhost	ip6-localhost	ip6-loopback
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters


127.0.1.1	debian.example.com
127.0.1.1	vps999999	vps999999
127.0.1.1	vps999999.vps.net	vps999999
```
After bootstrap, I realized that `netbase.fact` use `debian.example.com` in place of `netbase__domain` defined in my inventory. Consequently, many roles are misconfigured.

### Steps to reproduce
- Use `/etc/hosts` mentioned below
- Create your `netbase.yml` with `netbase__domain.yml` using different domain name than `vps.net` (i.e: `foo.com`)
- Run bootstrap playbook
- Check value of  `netbase.fact` 

### Actual results
`netbase.fact` return following informations:
```console
# python3 /etc/ansible/facts.d/netbase.fact 
{
    "configured": true,
    "self_address": "127.0.1.1",
    "self_domain": "example.com",
    "self_domain_source": "localhost",
    "self_fqdn": "debian.example.com",
    "self_local_hostname": true
}
```
`/etc/hosts` file:
```
127.0.0.1	localhost

::1	localhost	ip6-localhost	ip6-loopback
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters

127.0.1.1	debian.example.com
127.0.1.1	vps999999	vps999999
127.0.1.1	vps999999.foo.com	vps999999
```

### Expected results
- an additional entry in `/etc/hosts` with default IP address of host
- only keep one 127.0.1.1 entry based on `netbase__domain` value

### Workaround
Delete extra entries in `/etc/hosts` before running bootstrap.

**Comment by drybjed** [comment]
By default the `debops.netbase` role uses the `lineinfile` module to make changes in `/etc/hosts` file. This module will not remove duplicate lines; I looked at an alternative, `replace` module but it also doesn't have that functionality.

You could try switching to template-based `/etc/hosts` managed for these particular hosts by setting in the inventory:
```yaml
netbase__hosts_config_type: 'template'
```
Let me know if that helps.

**Comment by nqb** [comment]
I will take a look.

Just another question, in this situation, is it intended to not have `ansible.default_ipv4.address` in `/etc/hosts` ?

**Comment by drybjed** [comment]
If you have a sane DNS setup that resolves the host's FQDN to its IP address and optionally its IP address to its FQDN, then an entry in `/etc/hosts` becomes unnecessary and an obstruction. But if this is a host managed by a VPS, that might not be possible.

**Comment by nqb** [comment]
Ok thanks for clarification.

**Comment by nqb** [comment]
@drybjed, it works as expected with settting you mentioned. `/etc/hosts`file after bootstrap:
```
# This file is managed remotely, all changes will be lost

127.0.0.1	localhost

127.0.1.1	srv.foo.fr srv
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

```
