### ISSUE TITLE
debops.postgresql grant a role only select privileges to public schema

### ISSUE THREAD

**Issue by scosist** [debops/debops#116]
I found the https://www.github.com/debops/debops/blob/master/ansible/roles/debops.postgresql/tasks/main.yml#L117 `Grant public schema permissions` task but this gives `ALL` privileges. Is there a way to grant a role `SELECT` privileges only to the public schema? This would be for a read only user I need to create.

**Comment by drybjed** [comment]
Not yet, but it could be added as another `item` option for `postgresql__databases` variables... Perhaps `public_privs` with a default of `ALL` in the task? Want to try adding it?
