### ISSUE TITLE
[debops.owncloud] Fails to set HTTP header X-Frame-Options at SAMEORIGIN 

### ISSUE THREAD

**Issue by WhilelM** [debops/debops#1192]
Get to fresh install nextcloud 16 instance with debops.ansible-owncloud , got warning 
>     The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.

After looking at the code, I can't get the point with omitting this variable when version owncloud > 12 ?
l. 68 of  debops/ansible/roles/debops.owncloud/defaults/main.yml 
>    frame_options: '{{ omit if (owncloud__variant in ["nextcloud"] and owncloud__release is version_compare("12.0", ">=")) else "SAMEORIGIN" }}'"

Couldn't be simple to set SAMEORIGIN all the time ?

**Comment by paulinsche** [comment]
With <= 15 you get the same error, when the header _is_ set. The Header also is set in an other location:

```
      - pattern: '~ \.(?:css|js|woff2?|svg|gif|map)$'
        options: |
          # Adding the cache control header for js, css and map files
          # Make sure it is BELOW the PHP block

          try_files $uri /index.php$request_uri;
          add_header Cache-Control "public, max-age=15778463";

          add_header X-Content-Type-Options nosniff;
          add_header X-Download-Options noopen;
          {% if not (owncloud__variant in ["nextcloud"] and owncloud__release is version_compare("12.0", ">=")) %}
          add_header X-Frame-Options "SAMEORIGIN";
          {% endif %}


```
To get a A+ rating on https://scan.nextcloud.com/ we need there also an 

`          add_header X-Frame-Options "SAMEORIGIN" always;
`
in that part. See also: https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

**Comment by SuperSandro2000** [comment]
> To get a A+ rating on [scan.nextcloud.com](https://scan.nextcloud.com/) we need there also an

Are Owncloud and Nextcloud still so close that this applys? I could imagine that Nextcloud developed quite far apart.

**Comment by paulinsche** [comment]
Differences between owncloud and nextcloud are/should be handled by „owncloud__variant“.
