### ISSUE TITLE
'i386' Dictionary Key in apt__architecture_map is unnecessary

### ISSUE THREAD

**Issue by jrgoldfinemiddleton** [debops/debops#123]
The 'i386' key-value pair is superfluous based on this comment: "Only definitions that are different from the detected ones are listed here, otherwise the value of ``ansible_architecture`` is used."

https://github.com/debops/debops/blob/4e91e72c4a9969729d4069b4737a46b021e01fb7/ansible/roles/debops.apt/defaults/main.yml#L186

**Comment by drybjed** [comment]
Agreed, it's all accounted for in the `apt__architecture` variable as well. Want to make a PR that removes it?
