### ISSUE TITLE
[debops.yadm] Detect the installed yadm version

### ISSUE THREAD

**Issue by alinalexandru** [debops/debops#1235]
I discovered that Ubuntu 16 comes with yadm 1.03 and the bootstrap option has been added in 1.07.
https://github.com/TheLocehiliosan/yadm/releases/tag/1.07
I propose: 
- either to add xenial into the `yadm__upstream_enabled`. This is the easiest one.
- either to detect the version and compare with 1.07 (or 1.12.0 as it's in `yadm__upstream_version`). If it's lower use upstream, otherwise use the package from OS. The advantage here is that it doesn't depend on the OS version.

@drybjed What do you think is the best way?

**Comment by drybjed** [comment]
I don't think that the bootstrap option will be removed anytime soon, so checking the version seems a bit overcomplicated; I would go with the first choice - add `xenial` to list of releases that should enable upstream installation.
