### ISSUE TITLE
debops.console Use /etc/update-motd.d to generate motd file

### ISSUE THREAD

**Issue by gardouille** [debops/debops#125]
According to [Debian's wiki](https://wiki.debian.org/motd#How_to_script_updates_to_your_.2Fetc.2Fmotd), /etc/motd may be automatically update by /etc/update-motd.d content (such script,…).

**Comment by drybjed** [comment]
Sounds good. The MOTD feature needs to be moved out from `debops.console` role to its own role, perhaps it's a good opportunity to enhance it a bit.

**Comment by drybjed** [comment]
This should be fixed by https://github.com/debops/debops/pull/142.

**Comment by drybjed** [comment]
I'm closing this thread as resolved.
