### ISSUE TITLE
ERROR! 'collections' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by damko** [debops/debops#1253]
I just updated debops with debops-update and now I get this blocking error every time I run debops. 

```
debops -l machine
Running Ansible playbooks:
/home/user/.local/share/debops/debops/ansible/playbooks/site.yml
ERROR! 'collections' is not a valid attribute for a Play

The error appears to have been in '/home/user/.local/share/debops/debops/ansible/playbooks/common.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
- name: Security assertions
  ^ here
```
/home/user/.local/share/debops/debops/ansible/playbooks/common.yml seems fine to me.

The same error happens if I run a specific playbook:

```
debops service/mariadb_server -l machine
Running Ansible playbooks:
/home/user/.local/share/debops/debops/ansible/playbooks/service/mariadb_server.yml
ERROR! 'collections' is not a valid attribute for a Play

The error appears to have been in '/home/user/.local/share/debops/debops/ansible/playbooks/service/mariadb_server.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Manage MariaDB server
  ^ here
```

It was working right before the update but I didn't have the minio playbook so I updated to fetch it.

I'm running ansible 2.7.6 on Debian stable.

Any tip? (It's really urgent, pleeeeeeease :-) )

**Comment by drybjed** [comment]
You need to switch to at least Ansible 2.8, older releases do not support the `collections:` keyword in the playbook. Alternatively, comment them out and the playbooks should work fine again.

**Comment by damko** [comment]
yes @drybjed that was it.

Thanks a lot for your prompt reply. You're awesome!
