### ISSUE TITLE
netbase: fetching facts takes over a minute when no name servers are configured

### ISSUE THREAD

**Issue by scibi** [debops/debops#1254]
I've got a quite a few systems which don't use DNS. The `/etc/resolv.conf` is empty.

Unfortunately fetching facts takes a lot of time. I narrowed the issue to `/etc/ansible/facts.d/netbase.fact` and to two calls to `dns.resolver.query()`.

If I replace:
```python
except Exception:
    pass
```
with:
```python
except Exception as e:
    print(e)
    pass
```

I can see why:

```
The DNS operation timed out after 30.0011789799 seconds
```

After some digging in `dns.resolver` I found that if it doesn't find any nameservers in `/etc/resolv.conf` it uses `127.0.0.1` by default. That's why I get a timeout.

Maybe this script shouldn't try tu use DNS at all when `/etc/resolv.conf` is empty or there are no `nameserver` lines there?

**Comment by drybjed** [comment]
Hmm, sounds like a good workaround. I'll implement it over the weekend.

**Comment by drybjed** [comment]
@scibi I'm trying to recreate your case but with everything commented out in `/etc/resolv.conf`, the `netbase.fact` script exists immediately with an error:
```
Traceback (most recent call last):                 
  File "/etc/ansible/facts.d/netbase.fact", line 55, in <module>
    'self_address': socket.gethostbyname(socket.getfqdn()),                                                                                             
socket.gaierror: [Errno -5] No address associated with hostname
```
Is there a chance that you could describe your environment further? Is the `/etc/resolv.conf` file completely empty or are there any comments? Do you use `system-resolved` or is it not enabled?

**Comment by scibi** [comment]
@drybjed It doesn't matter if `/etc/resolv.conf` is completely empty or not. In both cases te result is the same.

`systemd-resolved`  is disabled.

I'm running Buster (10.2).

**Comment by drybjed** [comment]
@scibi The issue should be fixed by https://github.com/debops/debops/pull/1256/commits/80b9ee264bd2bf8662ae171507335bea6f0d2260, can you confirm?

**Comment by scibi** [comment]
Now it works great. Thanks!
