### ISSUE TITLE
[slapd] olcObjectIdentifier: "DebOps" previously defined

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#1258]
I've recently started seeing this message in the slapd-snapshot cron output:

```
5e39f771 olcObjectIdentifier: value #0 olcObjectIdentifier: "DebOps" previously defined "1.3.6.1.4.1.53622"
5e39f771 olcObjectIdentifier: value #1 olcObjectIdentifier: "LDAP" previously defined "1.3.6.1.4.1.53622.42"
5e39f771 olcObjectIdentifier: value #0 olcObjectIdentifier: "DebOps" previously defined "1.3.6.1.4.1.53622"
5e39f771 olcObjectIdentifier: value #1 olcObjectIdentifier: "LDAP" previously defined "1.3.6.1.4.1.53622.42"
```

The message can also be found when dumping databases with `slapcat`:

```
root@infra:~# slapcat -n 0 > /dev/null
5e3a84e5 olcObjectIdentifier: value #0 olcObjectIdentifier: "DebOps" previously defined "1.3.6.1.4.1.53622"
5e3a84e5 olcObjectIdentifier: value #1 olcObjectIdentifier: "LDAP" previously defined "1.3.6.1.4.1.53622.42"
```

I believe this behaviour was introduced in commit b68d6b3a9b0f9fb723df505bf937c732f1e3700e. The 'DebOps' and 'LDAP' olcObjectIdentifiers are defined in both the 'posixgroupid' and 'mailservice' schemas, like so:

```
dn: cn={4}posixgroupid,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: {4}posixgroupid
olcObjectIdentifier: {0}DebOps 1.3.6.1.4.1.53622
olcObjectIdentifier: {1}LDAP DebOps:42
olcObjectIdentifier: {2}posixGroupId LDAP:1
olcObjectIdentifier: {3}posixGroupIdAttribute posixGroupId:3
olcObjectIdentifier: {4}posixGroupIdObject posixGroupId:4
[..]
```

```
dn: cn={12}mailservice,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: {12}mailservice
olcObjectIdentifier: {0}DebOps 1.3.6.1.4.1.53622
olcObjectIdentifier: {1}LDAP DebOps:42
olcObjectIdentifier: {2}mailService LDAP:2
olcObjectIdentifier: {3}mailServiceAttribute mailService:3
olcObjectIdentifier: {4}mailServiceObject mailService:4
[..]
```

I don't think that just removing the 'DebOps' and 'LDAP' olcObjectIdentifier attributes from the 'mailservice' schema is a good solution, as this will prevent anyone from using the 'mailservice' schema without the 'posixgroupid' schema. Maybe we can define the olcObjectIdentifiers somewhere else?

**Comment by drybjed** [comment]
Thanks for the bug report. I saw these messages as well during development but I wasn't aware that other tools like `slapcat` will emit them as well. Agreed, the schema files that come from DebOps project need to be restructured. There can be one "debops-root" schema file that defines the main OIDs used in other schemas. I'll look at it as soon as possible. i'm afraid that the LDAP servers set up with existing roles will have to be rebuilt in this case, but there's nothing we can do about it.

**Comment by imrejonk** [comment]
Maybe it's an idea to rename the 'LDAP' objectIdentifier to something like 'DebOpsLDAP' as well? The name 'LDAP' is a bit generic, it might cause conflicts with other schemas in the future.

**Comment by drybjed** [comment]
Agreed. Namespaces are one honking great idea — let’s do more of those!
