### ISSUE TITLE
mariadb_server: not respecting mariadb_server__delegate_to

### ISSUE THREAD

**Issue by alemonmk** [debops/debops#1298]
Looks like there is no reference of `mariadb_server__delegate_to` in any task file of the role.

**Comment by drybjed** [comment]
The variable is not used in the role itself, however it is included in the `mariadb.fact` file written by the role. It's meant to aid the `mariadb` client role to the server via Ansible local facts.

I admit that this is not a very elegant solution, however it was designed a long ago and will have to be rethought at some point; similar solution is used in the `postgresql` and `postgresql_server` roles. Today i would probably use a DNS SRV records for this.

**Comment by alemonmk** [comment]
Then I don't understand what can I do with this role. I'm trying to use it in a role, does it mean I have to run this role with `delegate_to` if I want to use this role to install on a separate server?

**Comment by drybjed** [comment]
The `mariadb_server` and `mariadb` roles were designed to be used in a distributed environment, where a database server might be on one host, and the application that uses it on another. You can use the `mariadb_server` role to set up the MariaDB service, and then use the `mariadb` role via dependent variables from your own application role to configure the MariaDB user and database for it.

You can set the `mariadb__delegate_to` and mariadb_server__delegate_to` variables in the Ansible inventory to point to the MariaDB service if it's on a different host than the one you are installing the application on. If it's on the same host, the `mariadb` role should detect this automatically and you don't need to change anything.

**Comment by alemonmk** [comment]
I just forgot there's no `delegate_to` for `include_role`... it seems the way to go is run `mariadb_server` out of my role then include `mariadb` with `mariadb__delegate_to` defined, is it correct?

**Comment by drybjed** [comment]
Yes. You shouldn't apply `delegate_to` to the whole `mariadb` role because it sill has to do stuff on the host with the application, for example create the UNIX account and the `~/.my.cnf` configuration file. Only certain tasks should be delegated to the database server, which is handled via the `mariadb__delegate_to` variable.

**Comment by alemonmk** [comment]
Got it, thanks.

If you are going to update docs and closing this issue with a PR I will leave this open.
