### ISSUE TITLE
debops.gitlab_runner: disable skel to prevent issue

### ISSUE THREAD

**Issue by nqb** [debops/debops#1299]
Hello,

[Following merge request](https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/1523) has been merged (available in gitlab-runner 12.10).  We should adapt code of `gitlab_runner` to disable skel.

**Comment by drybjed** [comment]
This should already be fixed in DebOps via https://github.com/debops/debops/commit/ef3e3a73e864bba922da6468f317adfdd307f09c; the `user` module should not copy over the `/etc/skel/` contents on new installations. @nqb, can you confirm on your end if that's fixed?

**Comment by nqb** [comment]
Hello @drybjed,

Did not test if it was fixed. I just want to point out that upstream as fixed this bug in order to adapt our current workaround.

**Comment by drybjed** [comment]
Ah, I see. This should already be covered, since the `gitlab-runner` .deb package uses the `postinst` script to create the UNIX account if it doesn't exist already - we do that before installing the package so there should be no impact.

Closing this issue as resolved.
