### ISSUE TITLE
[slapd] slapd-snapshot stops slapd service

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#1306]
It seems that the nightly slapd-snapshot cronjob sometimes causes the slapd service to exit, after which the service has to be manually restarted.

We are running a four-node multi-master slapd cluster across two data centers as described in the [Guide](https://docs.debops.org/en/master/ansible/roles/slapd/guide-multi-master-replication.html). This setup has been working nicely for us, but we recently had a few node outages happen exactly at midnight, which is when the `slapd-snapshot` cronjob runs. At one occasion both nodes at one of our data centers stopped, while this Sunday one node at the other location stopped functioning.

Here is a syslog extract from the node that failed this Sunday (infra.ciphermail.com/0.ldap.ciphermail.com):

```
Mar 22 00:00:01 infra slapd-snapshot[15634]: Waiting for PID 15636 to finish
Mar 22 00:00:01 infra slapd-snapshot[15638]: Waiting for PID 15636 to finish
Mar 22 00:00:01 infra slapd-snapshot[15636]: Creating daily snapshot of the slapd:0 database
Mar 22 00:00:01 infra slapd-snapshot[15636]: Dumping the slapd:0 database
Mar 22 00:00:01 infra slapd-snapshot[15636]: Daily snapshot of the slapd:0 database created successfully
Mar 22 00:00:01 infra slapd-snapshot[15636]: Creating daily snapshot of the slapd:1 database
Mar 22 00:00:01 infra slapd-snapshot[15636]: Enabling read-only mode in the slapd:1 database
Mar 22 00:00:02 infra systemd[1]: Starting Rotate log files...
Mar 22 00:00:02 infra systemd[1]: Starting Daily man-db regeneration...
Mar 22 00:00:02 infra nslcd[977]: [5c42ac] <group="admins"> ldap_result() failed: Can't contact LDAP server
Mar 22 00:00:02 infra nslcd[977]: [5c42ac] <group="admins"> ldap_abandon() failed to abandon search: Can't contact LDAP server: Transport endpoint is not connected
Mar 22 00:00:02 infra slapd-snapshot[15636]: Dumping the slapd:1 database
Mar 22 00:00:02 infra nslcd[977]: [5c42ac] <group="admins"> ldap_start_tls_s() failed (uri=ldap://0.ldap.ciphermail.com/): Can't contact LDAP server: Connection reset by peer
Mar 22 00:00:02 infra nslcd[977]: [5c42ac] <group="admins"> failed to bind to LDAP server ldap://0.ldap.ciphermail.com/: Can't contact LDAP server: Connection reset by peer
Mar 22 00:00:02 infra slapd-snapshot[15636]: Disabling read-only mode in the slapd:1 database
Mar 22 00:00:03 infra systemd[1]: man-db.service: Succeeded.
Mar 22 00:00:03 infra systemd[1]: Started Daily man-db regeneration.
Mar 22 00:00:03 infra nslcd[977]: [5c42ac] <group="admins"> connected to LDAP server ldap://1.ldap.ciphermail.com/
Mar 22 00:00:09 infra slapd-snapshot[15634]: Creating weekly snapshot of the slapd:0 database
Mar 22 00:00:09 infra slapd-snapshot[15634]: Dumping the slapd:0 database
Mar 22 00:00:09 infra slapd-snapshot[15634]: Weekly snapshot of the slapd:0 database created successfully
Mar 22 00:00:09 infra slapd-snapshot[15634]: Creating weekly snapshot of the slapd:1 database
Mar 22 00:00:09 infra slapd-snapshot[15634]: Enabling read-only mode in the slapd:1 database
Mar 22 00:00:26 infra slapd-snapshot[15638]: Creating weekly snapshot of the slapd:0 database
Mar 22 00:00:26 infra slapd-snapshot[15638]: Dumping the slapd:0 database
Mar 22 00:00:26 infra slapd-snapshot[15638]: Weekly snapshot of the slapd:0 database created successfully
Mar 22 00:00:26 infra slapd-snapshot[15638]: Creating weekly snapshot of the slapd:1 database
Mar 22 00:00:26 infra slapd-snapshot[15638]: Enabling read-only mode in the slapd:1 database
Mar 22 01:09:01 infra nslcd[977]: [2d05ee] <group/member="root"> ldap_start_tls_s() failed (uri=ldap://0.ldap.ciphermail.com/): Can't contact LDAP server: Transport endpoint is not connected
Mar 22 01:09:01 infra nslcd[977]: [2d05ee] <group/member="root"> failed to bind to LDAP server ldap://0.ldap.ciphermail.com/: Can't contact LDAP server: Transport endpoint is not connected
Mar 22 01:09:02 infra nslcd[977]: [2d05ee] <group/member="root"> connected to LDAP server ldap://1.ldap.ciphermail.com/
```

It looks like the slapd service becomes unreachable as soon as the read-only mode on the slapd:1 database is enabled. The read-only mode is never disabled and the slapd service requires a manual restart to become functional again.

We have mitigated the impact of this issue by disabling the slapd-snapshot cronjob on all but one slapd node.

**Comment by drybjed** [comment]
I think that this might be an issue with OpenLDAP itself, not specifically with the `slapd` role. If this issue is reproductible, you should probably enable debug log in `slapd` and check what the logs say, that might give us more clues.

Also, what OS release and OpenLDAP version are you using? Did you test that the database backups can be correctly imported to a fresh instance, to be sure that data can be recovered?

**Comment by imrejonk** [comment]
I haven't found a reliable way to reproduce this issue, unfortunately. All I can do is wait until the next occurrence :/

All our `slapd` nodes run on Debian 10 with OpenLDAP version 2.4.47. The nighly backups are complete and can be restored on a fresh instance. Synchronization also seems to work just fine.

**Comment by imrejonk** [comment]
I'm closing this issue because this hasn't occured since and I don't have a way to reproduce it. We're still running slapd-snapshot on only one of the nodes.

If anyone experiences this behaviour as well, please feel free to reopen this issue.
