### ISSUE TITLE
no action detected in task

### ISSUE THREAD

**Issue by markgraf** [debops/debops#131]
Hi all,

So I'm doing my first steps with debops an run into the error below...
Unfortunately I couldn't find anything related in the docs.

While the error says 'gunicorn', it probably comes from elswhere, as I do not have
[debops_service_gunicorn] anywhere in my inventory.

I looked into debops/ansible/playbooks/srv/gunicorn.yml, couldn't see any errors there, though.
I commented out the role from /srv/all.yml, and got hit with the same error for debops.opendkim.

git log tells me I#m using commit 0876f8686c0fd51348c498bd2c3517009a0030a3

Any ideas where to dig further?

8<- - - - -
```
$ debops
Running Ansible playbook from:
/home/marco/.local/share/debops/debops/ansible/playbooks/site.yml ...
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/marco/.local/share/debops/debops/ansible/roles/debops.gunicorn/tasks/main.yml': line 11, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Configure Green Unicorn on older OS releases
  ^ here


The error appears to have been in '/home/marco/.local/share/debops/debops/ansible/roles/debops.gunicorn/tasks/main.yml': line 11, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Configure Green Unicorn on older OS releases
  ^ here
```

8<- - - - -

**Comment by drybjed** [comment]
What Ansible version are you using? You should be using the current stable release, 2.4. There's probably a module which was not available in an older release and is used now, somewhere in the playbook.

**Comment by markgraf** [comment]
My distro comes with 2.2.1.0-1 as the newest available :-/ *sigh*
ok, I'll check...

**Comment by markgraf** [comment]
Problem solved :+1: 
running ansible-2.4.2.0 now, thanks to pip :-)

Thanks a lot!
