### ISSUE TITLE
https://debops.org/ HTTPS certificate expired

### ISSUE THREAD

**Issue by SuperGnarf** [debops/debops#1323]
I don't no where to put this, but the certificate of the https://debops.org/ domain has expired.

**Comment by drybjed** [comment]
Thanks, fixed. I'm not sure what's with cloudflare though, this might be an issue with https://debops.readthedocs.io/.

**Comment by SuperSandro2000** [comment]
debops.org uses HSTS so currently I can't visit the site.

**Comment by SoulRaven** [comment]
same problem here, NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by SuperGnarf** [comment]
Works again, thx for fixing this.
