### ISSUE TITLE
Collection: lookup plugin (debops.debops.debops.debops.template_src) not found

### ISSUE THREAD

**Issue by DouglasHeriot** [debops/debops#1324]
In the `sshd` role in the built collection, this line of the playbook is changed from `lookup("template_src"` to `lookup("debops.debops.debops.debops.template_src"`
https://github.com/debops/debops/blob/master/ansible/roles/sshd/tasks/main.yml#L165
This also applies to the `dovecot` role in multiple places:
https://github.com/debops/debops/blob/master/ansible/roles/dovecot/tasks/main.yml#L130

I assume it's related to the `make-collection` script, but somehow it's applying this transformation twice? I haven't had time to fully understand everything this script is doing to debug the issue properly.
https://github.com/debops/debops/blob/master/lib/ansible-galaxy/make-collection#L300

It works when I manually modify my installed collection to have `lookup("debops.debops.template_src"`

**Comment by drybjed** [comment]
Yup, looks like a bug in the script. Thanks for reporting it, I'll try to fix it before the next stable release in a day or two.
