### ISSUE TITLE
debops.nginx failes with  lookup/ferm__fix_dependent_rules.j2 error

### ISSUE THREAD

**Issue by jankowa** [debops/debops#133]
Hi,

running debops service/nginx the role fails with:

`the template file lookup/ferm__fix_dependent_rules.j2 could not be found for the lookup`

This happens on the Task: "Create default welcome page if enabled" If disabled this with `nginx_webroot_create: False` everything works fine.

I didn't understand yet, what leads to this error. Any Idea?

**Comment by drybjed** [comment]
You need to downgrade your `jinja2` install to 2.8, this is an Ansible issue.

**Comment by thiagotalma** [comment]
To help those who get here with this problem:
`pip install Jinja2==2.8`

**Comment by drybjed** [comment]
This bug should be finally fixed by https://github.com/debops/debops/pull/223, therefore I'm closing this issue.
