### ISSUE TITLE
[debops.ldap] fusiondirectory will not work on a DIT initialized by ldap/init-directory

### ISSUE THREAD

**Issue by tasosalvas** [debops/debops#1341]
Trying to setup an apt installed `fusiondirectory` on top of a fresh `ldap/init-directory` blocks right after it binds and displays the following errors: 

* __Warning__: Missing optional object class "fdTemplate"! Schema "template-fd.schema": Used to store templates.
* __Error__: Missing required object class "fdLockEntry"! Schema "core-fd.schema": Main FusionDirectory schema
* __Error__: Missing required object class "fusionDirectoryConf"! Schema "core-fd-conf.schema": Schema used to store FusionDirectory configuration
* __Error__: Your schema is configured to support mixed groups, but this plugin is not present. Schema "nis.schema": The objectClass "posixGroup" must be STRUCTURAL

Tested on a fresh `buster` vm with very minimal other configuration. 
Just dropping those here for anyone interested, I'm just going to use Apache Directory Studio.

**Comment by drybjed** [comment]
I suppose that adding the schema required by FusionDirectory wouldn't be a big problem, however the requirement of `posixGroup` being STRUCTURAL is - with this you wouldn't be able to combine `posixGroup` and `groupOfNames` in a neat LDAP object, and that doesn't let you create clean [User Private Groups](https://wiki.debian.org/UserPrivateGroups) in shared environments.

FusionDirectory could be modified to allow for this scenario, maybe at some point they will. Unless that's already posible via some kind of plugin? I will have to investigate...

Apparently the [`fusiondirectory-plugin-mixedgroups`](https://packages.debian.org/buster/fusiondirectory-plugin-mixedgroups) should allow this. Maybe it's a possibility after all.

**Comment by tasosalvas** [comment]
It shaved the last error off, but I still get the warning and the other two and block.

I admit without the last one the others kinda look like misconfiguration on my part? Weird that it's missing its own stuff.

**Comment by tasosalvas** [comment]
Okay, the initial errors were solved (Thanks drybjed! :))
* `apt install fusiondirectory-plugins-mixedgroups` fixed the last one
* `fusiondirectory-insert-schema -i` fixed the rest

## Config screen
Fusiondirectory has its own take on ACL. It defaults to `ou=people` and `ou=aclroles`.
I changed those to `ou=People` and `ou=Roles`, but predictably the rest of the roles structure didn't happen to be the same. So I ended up with a bunch of new entries in `ou=Roles` implementing acl.

I ignored settings about password hashing and snapshots.

## Post-config checks
Added some extra fields to my user

Offered to move these entries "to the configured tree". Said "Doing this may straighten your LDAP service". :) But it let me go with a warning.
* my user
* `cn=UNIX Administrators,ou=Groups,dc=...`
* `cn=UNIX SSH users,ou=Groups,dc=...`

Offered to add,
```
objectClass: gosaDepartment
description: FusionDirectory department
```
To all `ou=`s, "so they are visible in the interface". Fair enough.
But this errors out with a "too few arguments". It shows a preview of the changes, so it isn't like it has trouble calculating them. I bet I did something wrong again.

Had to create an extra administrative user.

I can't seem to be able to access these migrations now that I've finalized the config, so no more info. :( I could do it over for the exact error message but I don't think it's worth it.

## And we're in!
It's looks ok. Certainly prettier than phpmyadmin. xD
Most configuration is in `ou=fusiondirectory,cn=config`.

Well, I don't see all the debops `ou`s,  just `ou=Roles` under a _Groups and Roles_ menu item, as expected.

I guess it could be nice if it had the rest of the stuff, but it seems to be very streamlined towards its own workflow.
I mean, ok, having an "Access Departments" top level menu item is only a bit weird... but navigating a DIT without a tree view anywhere is hubris.

## First impressions
I suppose it would have been a bit marginally more tidy to dump its organizational units under separate names (`ou=folks`?).
The duplicate ACL systems would be a security mess either way, I'm guessing.

Overall I don't think it would make sense to try and get its configuration compatible with debops, to be used as a viewer. It's clearly meant to be the primary way of managing the tree.

I think if debops were to do anything with fusiondirectory, it would be to yield to its dit structure and work with that instead, tagging its own `ou`s the way fd likes, so fd users can keep the workflow of primarily managing through the app.

Personally I need to write client-facing frontend anyway (can't have them Accessing Departments ;)), so between `debops.ldap` and `python-ldap` I think I'll be covered, and ADS can provide an overview without any footprint on the data itself (or php and a webserver on the host).

**Comment by sedros** [comment]
Hi. I have a very similar issue with a fresh installation of FusionDirectory (1.2.3-4+deb10u1) and 389-ds (1.4.0.21-1) on Debian 10, but when I try to use `fusiondirectory-insert-schema` command I get an error:

`! This tool is only intended to be with with a cn=config backend, cn=config could not be found in the LDAP at /usr/bin/ldap-schema-manager line 324.`

Can you help solving this problem?

**Comment by drybjed** [comment]
@sedros: the `389-ds` server does not use the same configuration interface as OpenLDAP (`slapd`) server. The `fusiondirectory-insert-schema` scritpt does not support it. I think that if you try to import the schema files into `389-ds` manually (not sure how at the moment), FusionDirectory could probably work with it, but I haven't tried that configuration. Your best bet would to switch to OpenLDAP server instead.

**Comment by sedros** [comment]
@drybjed: Thank you for the response. I noticed that there are big differences between OpenLDAP and 389-ds but as the [FusionDirectory documentation](https://readthedocs.org/projects/fusiondirectory-user-manual/downloads/pdf/1.4/) states that it works with 389-ds I think that this issue should be treated like a bug.

**Comment by sedros** [comment]
@drybjed: [I created a new issue](https://github.com/debops/debops/issues/1369) regarding it as it seems to be a separate problem than the original one in this thread. We can move there with the discussion.
