### ISSUE TITLE
[BUG] [etc_aliases] Installation from Ansible Galaxy is broken (etc_aliases__parse_recipients)

### ISSUE THREAD

**Issue by JoelKle** [debops/debops#1360]
I've followed the documented installation path:
https://docs.debops.org/en/master/introduction/install.html#installation-from-ansible-galaxy
and installed debops as a collection with the `ansible-galaxy` command.

```
$ ansible-galaxy collection install debops.debops
Process install dependency map
Starting collection install process
Installing 'debops.debops:2.0.3' to '/home/xxx/.ansible/collections/ansible_collections/debops/debops'
Installing 'debops.roles01:2.0.3' to '/home/xxx/.ansible/collections/ansible_collections/debops/roles01'
Installing 'debops.roles02:2.0.3' to '/home/xxx/.ansible/collections/ansible_collections/debops/roles02'
Installing 'debops.roles03:2.0.3' to '/home/xxx/.ansible/collections/ansible_collections/debops/roles03'
```
All collections where installed with the latest version `2.0.3`.

After the installation I've tried to use the `postfix.yml` as my playbook for a mailserver installation.
https://github.com/debops/debops/blob/master/ansible/playbooks/service/postfix.yml

The playbook run fails with the following error (snipped):
```
ASK [etc_aliases : Generate the /etc/aliases file] ****************************
AnsibleError: template error while templating string: no filter named 'etc_aliases__parse_recipients'. String: # {{ ansible_managed }}\n\n.............................................
```

The custom filter `etc_aliases__parse_recipients` was not found!
I understood, that this filter should resists in the `ansible_plugins` role (collection = debops.debops). But it's not there!
```
xxx@xxx:~/.ansible/collections/ansible_collections/debops$ grep etc_aliases__parse_recipients * -R
roles01/roles/etc_aliases/filter_plugins/etc_aliases__parse_recipients.py:def etc_aliases__parse_recipients(*args, **kwargs):
roles01/roles/etc_aliases/filter_plugins/etc_aliases__parse_recipients.py:        return {'etc_aliases__parse_recipients': etc_aliases__parse_recipients}
roles01/roles/etc_aliases/templates/etc/aliases.j2:{% set etc_aliases__tpl_filtered_recipients = (etc_aliases__combined_recipients | etc_aliases__parse_recipients) %}
roles01/FILES.json:   "name": "roles/etc_aliases/filter_plugins/etc_aliases__parse_recipients.py",
```

In the upstream GithHub repo this filter is already in the `ansible_plugin` role.

For me it looks like in the `debops.debops` collection contains a too old version of the`ansible_plugin` role on Ansible Galaxy.
Currently it is not possible to use the `etc_aliases` role.

Thanks Joel

**Comment by drybjed** [comment]
Sorry about that. The filter plugin has already be moved to the `ansible_plugins` directory; I'll try to publish an updated version of the collection soon.

**Comment by JoelKle** [comment]
Okay perfect, I'll test it when the new version is available.
And thank you for your work. Your roles are great 👍

**Comment by JoelKle** [comment]
This bus has been fixed in an already published version. I'll close this bug. Thanks.
