### ISSUE TITLE
Jinja Undefined values improved in Ansible 2.8

### ISSUE THREAD

**Issue by ypid** [debops/debops#1371]
Hi @drybjed

You are aware of https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.8.html#jinja-undefined-values ?

This finally allows us to change this:

```YAML
cryptsetup__keyfile_remote_location: '{{ (ansible_local.root.var
                                         if (ansible_local|d() and ansible_local.root|d() and
                                             ansible_local.root.var|d())
                                         else "/var/local") + "/keyfiles" }}'
```

Into this:

```YAML
cryptsetup__keyfile_remote_location: '{{ (ansible_local.root.var
                                         if ansible_local.root.var|d()
                                         else "/var/local") + "/keyfiles" }}'
```

**Comment by drybjed** [comment]
Yes, I know about it and I have been using it in various roles already. Also, above could probably be written as:
```yaml
cryptsetup__keyfile_remote_location: '{{ (ansible_local.root.var | d("/var/local"))
                                         + "/keyfiles" }}'
```
We will get there eventually. :-) As for `ansible_local.root`, I decided to move these to a new role, `hier` - the `root` name has too many connotations in Linux already. I'll try to push the PR with changes today, you will see what I mean.

**Comment by ypid** [comment]
Thanks for the hint. You are right, can be even shorter. OK then, so this can be used while working on a role, nice.

**Comment by ypid** [comment]
Progress has been made on this issue. I was able to write a regex search/replace to do most of this automatically :) I will test a bit even though I reviewed the whole diff manually.

Ref: https://github.com/ypid/debops/blob/improve-stuff-3/bin/debops-optimize
