### ISSUE TITLE
apt__conf: Unable to generate additional configuration file

### ISSUE THREAD

**Issue by mbehrle** [debops/debops#1399]
I am just new to ansible and debops, so if I am doing something terribly wrong please forgive and advise;)

I have already an apt-cacher running in the local network, that also was used for the initial setup of the host, thus resulting in an entry in /etc/apt/apt.conf. This file is deleted by debops to avoid side-effects. Now I wanted to re-introduce the proxy configuration with

apt.yml
```
---

apt__conf:
  - name: apt-cacher
    priority: '02'
    content: |
      Acquire::HTTP {
      Proxy "http://apt-cacher.{{ ansible-domain }}:9999";
      };
```
which resulted in doing nothing (task being skipped) after running

$:~/projects/debops/debops/first_project$ debops service/apt -l majestix 

 To be safe that the task is executed I removed for debugging purposes the when clause from the task and started with the debugger activated

TASK [apt : Generate additionnal APT configuration files] ***********************************************************************************************************************************************************************************
fatal: [majestix]: FAILED! => 
  msg: '''ansible'' is undefined'
[majestix] TASK: apt : Generate additionnal APT configuration files (debug)> p
***SyntaxError:SyntaxError('unexpected EOF while parsing', ('<string>', 0, 0, ''))

I tried with different entries, also using 'src':  /path/to/some/file, but with no success.

What to do next to debug the issue?

**Comment by drybjed** [comment]
The next step would be to add a debug task to see the contents of the variable:
```yaml
- debug: var=apt__conf
```
With this, you would see the result of the templating:
```
ok: [gamma] => {
    "apt__conf": "VARIABLE IS NOT DEFINED!"
}
```
After inspection, it seems that you wrote `ansible-domain`, but you should have used `ansible_domain` which would resolve to a proper variable. After fixing this issue, the task generates the file as expected in my environment.

**Comment by mbehrle** [comment]
Thanks a lot for your help!

> The next step would be to add a debug task to see the contents of the variable:
> 
> ```yaml
> - debug: var=apt__conf
> ```
> 
> With this, you would see the result of the templating:
> 
> ```
> ok: [gamma] => {
>     "apt__conf": "VARIABLE IS NOT DEFINED!"
> }
> ```
Did that and so far ok.

> After inspection, it seems that you wrote `ansible-domain`, but you should have used `ansible_domain` which would resolve to a proper variable. After fixing this issue, the task generates the file as expected in my environment.

It still doesn't work for me, even when removing the variable completely like in

```
apt__conf:
  - name: apt-cacher
    priority: '02'
    content: |
      Acquire::HTTP {
      Proxy "http://apt-cacher:9999";
      };
```

I am running debops from a virtualenv:

```
[debops]$ pip freeze
ansible==2.9.10
cffi==1.14.0
cryptography==2.9.2
-e git+https://github.com/debops/debops.git@bd249780c885bd24d3be643a94e3d0219407ebf4#egg=debops
distro==1.5.0
dnspython==1.16.0
future==0.18.2
Jinja2==2.11.2
MarkupSafe==1.1.1
netaddr==0.7.20
pycparser==2.20
PyYAML==5.3.1
six==1.15.0
```

Anything wrong with that?

**Comment by mbehrle** [comment]
It worked now for me, I had to run a full blown

$:~/projects/debops/debops/first_project$ debops -l majestix

instead of only

$:~/projects/debops/debops/first_project$ debops service/apt -l majestix

Thanks for your support!
