### ISSUE TITLE
initial debops site deploy fails on some VPS services with IPv6 enabled

### ISSUE THREAD

**Issue by jwaibel** [debops/debops#141]
ferm fails to start on some ipv6 enabled vps on various vps providers.

/var/log/syslog shows:
Starting Firewall: fermip6tables: Protocol wrong type for socket.

On the involved system i had to install a more recent kernel to get this problem solved.

**Comment by drybjed** [comment]
This could be handled with conditionally enabling and disabling [the `ipv6` domain in `debops.ferm`](https://github.com/debops/debops/blob/master/ansible/roles/debops.ferm/defaults/main.yml#L50-L61), after kernel update and reboot the role would just reconfigure the firewall with IPv6 enabled. I'm not sure what would be the good test for that though, presence/absence of `ansible_all_ipv6_addresses`, perhaps? Could you check what facts differ between the hosts with IPv6 enabled or not?

**Comment by drybjed** [comment]
@jwaibel This issue should be fixed by https://github.com/debops/debops/pull/255, can you confirm?

**Comment by drybjed** [comment]
This issue should be fixed, therefore I'm closing it. If it comes back, let me know.
