### ISSUE TITLE
debops.docker fails at Configure Docker systemd options

### ISSUE THREAD

**Issue by hohmanjl** [debops/debops#148]
`debops.docker` role fails at task Configure Docker systemd options.

```
TASK [debops.docker : Configure Docker systemd options] *************************************************************************************************************************
fatal: [host-01]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {{ ansible_local.resolver.search if (ansible_local|d() and ansible_local.resolver|d() and ansible_local.resolver.search|d()) else ansible_dns.search }}: 'dict object' has no attribute 'search'"}
```

When I look at host-01 `/etc/resolv.conf` there is no search field.

```
root@host-01:~# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver xxx.xxx.xxx.xxx
nameserver xxx.xxx.xxx.xxx
```

How can I get the search field in the `resolv.conf`? I tried adding var `dns_search: mydomain.com` to `main.yml`, but `resolv.conf` still doesn't have the search field. I also tried adding `ansible_dns.search` to `main.yml` but that also did not work.

If I add `search mydomain.com` to `resolv.conf` manually the task works.

Version info:
```
ansible 2.4.2.0
python version = 2.7.12
```

**Comment by drybjed** [comment]
This is usually done either via `/etc/network/interfaces` where you can specify `dns-search` parameter for a given interface, or by configuring a DHCP server to advertise a search domain.

I guess that I hadn't considered that there might be environment without a search domain defined, role will need to have that accounted for and optional in this case. Thanks for the bug report. :-)

**Comment by hohmanjl** [comment]
Right now what I've done is specify the `docker__dns_search` value in `inventory/group_vars/docker.yml`. That seems to be a valid workaround. 

Is there a correct way to configure `dns_search` in DebOps? Either via variable or role?

Thank you!

**Comment by drybjed** [comment]
It depends on your environment. Do you control your DHCP server? If yes, then you need to configure the `search` parameter there. If not, you can use `debops.ifupdown` to reconfigure network interfaces and specify the `dns_search` parameter.

**Comment by hohmanjl** [comment]
I'm using a VPS (static IP) so I don't control/use the DHCP server. I'll look into using `depops.ifupdown` to configure the search parameter.

**Comment by drybjed** [comment]
This issue should be fixed by https://github.com/debops/debops/commit/f19515785da63de37e3fa24fa6ac242b03d17d92, therefore I'm closing it.
