### ISSUE TITLE
[debops.users] My user isn't added to the admins group by ansible when running a customized playbook

### ISSUE THREAD

**Issue by devvmh** [debops/debops#1487]
Preface: I'm new to Ansible/debops, and I'm doing a bit of a loopy setup, so my setup is confusing. Any help you can offer is much appreciated!

I am setting up a custom ansible playbook that I can use for my personal server infrastructure. I am re-using most of debops as the basis for my playbooks to try to leverage the existing conventions defined to avoid re-inventing the wheel.

That said, I'm not using debops as designed and I'm also using ansible-pull, which is changing things up a bit for me.

I have a mostly working playbook ready to serve as my basic setup that I can then build applications on top of. However, I have one major issue:

When I run my playbook, the user account it creates ("devin") is not being added to the "admins" group. If I run `adduser devin admins` after running ansible-pull, everything works fine. But I can't figure out how to make it work.

I don't observe any difference when running on a fresh host vs running the playbook again on the same host - should I expect a difference?

Any advice on a) what might be going wrong or b) best strategies for debugging? As I said, I'm new to ansible so any tips would help. I got as far as editing /root/.ansible/collections/ansible_collections/debops/debops/roles/users/tasks/main.yml to see if I could figure it out but didn't make any progress after 30 minutes of trying things blindly.

Code I'm using https://github.com/devvmh/ansible-playbook-core/tree/devel

Specifically, this code is not functioning as expected:

```
    - role: debops.debops.system_groups
    - role: debops.debops.users
      vars:
        - users__accounts:
          - name: 'devin'
          - groups: ['admins']
```

Output I get:

```
TASK [debops.debops.users : Manage additional UNIX groups for UNIX accounts] *********************************************************
skipping: [localhost] => (item={u'state': u'present', u'gecos': u'', u'name': u'devin', u'groups': u''})
```

If I remove the when block from this step in tasks/main.yml, I get this output, but it still doesn't work:

```
TASK [debops.debops.users : Manage additional UNIX groups for UNIX accounts] *********************************************************
ok: [localhost] => (item={u'state': u'present', u'gecos': u'', u'name': u'devin', u'groups': u''})
```

Thanks for any help or tips you can provide!

**Comment by drybjed** [comment]
Interesting use case, let me know how the pull mode works out for you. I suspect that remote hosts will have `secret/` directories beside their inventory, at least.

Did you use SaltStack in the past? The code you pasted above resembles some of the configuration I see in some Salt formulas. Anyway, too many dashes. :-) Your code should look like this;
```yaml
- role: debops.debops.system_groups
- role: debops.debops.users
  vars:
    users__accounts:
      - name: 'devin'
        groups: ['admins']
```
Notice that the `vars:` key is a YAML dictionary, not a list, so the `users__accounts` is a dictionary key. The `users__accounts` variable contains a list of YAML dictionaries, with one item which defines the `name` and `groups` keys.

Also, if you are making an administrative account, the `system_users` role might be a better fit. Check it out.

**Comment by devvmh** [comment]
Dang, a syntax error! Thanks for looking and for the help! It works.

I've actually never used any kind of automation like ansible, saltstack, etc before. This is my first foray. 

Thanks for teaching me about yaml!
