### ISSUE TITLE
[docker_gen] Bad comment block generated

### ISSUE THREAD

**Issue by yethee** [debops/debops#1509]
Invalid nginx's config is generated by role `docker_gen`, after upgrade debops to version 2.1.*.

```
$ sudo nginx -t
nginx: [emerg] unexpected "{" in /etc/nginx/conf.d/docker-gen-upstreams.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
```

`docker-gen-upstreams.conf` content:
```
{# Copyright (C) 2015-2016 Maciej Delmanowski <drybjed@gmail.com>
 # Copyright (C) 2015-2016 DebOps <https://debops.org/>
 # SPDX-License-Identifier: GPL-3.0-only
 #}
upstream morphy_backend {
...
```

**Affected version**: 2.1.0 - 2.1.2

**Comment by drybjed** [comment]
Ah, I see what's up - that file is a `docker_gen` template, not a Jinja template. The `{# #}` section needs to be a real comment. I'll fix that as soon as possible and backport to the stable releases. Thanks for the report.
