### ISSUE TITLE
DebOps logo proposal

### ISSUE THREAD

**Issue by tasosalvas** [debops/debops#1541]
Hey all,

I'm wearing my branding hat so I thought I'd try my hand at the DebOps logo.

Lol someone mentioned _minetest_ (no link provided, you're welcome) in the last meetup and now I've finished a bunch of its more hardcore modes and I'm halfway into a book for modding it. Its community is full of anti-microsoft nuts refusing to use gh; pretty cool. :D

Hopefully your feedback will put me back on track before I end up living there.
It's hard to stay motivated when I'm working on my own. Gotta get me some clients... hehe.

![debops-proposal](https://user-images.githubusercontent.com/245478/97475727-46c30580-1956-11eb-8515-fb192f4866ec.png)

## Concept notes
The gear and spiral logo was the concept I had in mind. I like the interplay between the spiral and the concentric circles.

Final say goes of course to @drybjed, but I'm happy to hear everybody's ideas and proposals and provide you with inkscape source files if you want to turn this into a collab.

### Color
The green tint is complementary to Debian's red. I did not pick it as the main color as it would clash too much. 

I can see the blue variant working too, but hey, science.

I experimented a bit with the yellow starting with the idea of a copper gear that could potentially show a bit of green as oxidization -- But that looked even more busy on the smaller resolutions, and I liked how the orange tint made it look like a sun. Maybe an idea for a future high-res remix on blender.

The rest of the palette is analogous to the base yellow/orange in order to not introduce another hue.

I tend to go for pastel hues, bumped up the contrast a couple of times to be a bit more aggro, perhaps it could even use a bit more.

### Fonts
Apart from a few fonts I'd like opinions for, the sampler contains a couple of ideas:

* Using the first half of the Debian brand
* Using a hollow font for the _Ops_
* Using a hacky monospace font

The half-debian brand clashes with our preferred "DebOps" capitalization, but hey, so does "Debian".

Freemono was the hackiest I could find -- all my terminals and editors run Fira Code with ligatures and it looks too modern to even look mono in so few characters. :(

## Specs
The whole thing is SVG, and I think the original has enough detail to go on that [T-shirt](https://github.com/debops/docs/issues/221) @ypid wanted. (Oops, just realized I missed incorporating the slogan. Anyway.)

The current file I have is laid out for editing, if we decide to use it I will provide both the source file and SVGO optimized versions to use directly or create PNGs from. (`lib/images/` is the place, huh?)

There's also room for more shading, experimentation and remixes on the larger image, but I've refrained from putting in too many hours until we're good on the concept.

### Size and variants
I've darkened and enlarged the tinted backdrop on the 50px variant and I think it's moderately readable at that size, which is the smallest we currently have in the repo.

I've also darkened the outlines on both the 200px and 50px versions.

If you think it's called for, I can make an 8-tooth smaller version for 50px and maybe 16px versions when we've settled on the rest of the details.

## License
The image is derived from the Debian _Open Use_ Logo (which is the more recognizable one anyway), from the [Debian logos page](https://www.debian.org/logos/), Copyright (c) 1999 [Software in the Public Interest, Inc.](https://www.spi-inc.org/),
released: 
> under the terms of the GNU Lesser General Public License, version 3 or any later version, or, at your option, of the Creative Commons Attribution-ShareAlike 3.0 Unported License.

This is pretty much compatible with our usual GPL3, with the CC-BY-SA addition being common sense for visual stuff, so we're fully compatible releasing ours under the same terms and throwing in an attribution for the source image for good measure.

The fonts I've listed are all out of the Debian repos so I'm trusting them to be SIL or otherwise GPL compatible, I'll procure the specific license when we settle on one. 

## I hate it!
You're just the person I was looking for! Tell me why. ;)

**Comment by drybjed** [comment]
> I'm wearing my branding hat so I thought I'd try my hand at the DebOps logo.

Awesome! I created the current logo on a whim in Inkscape all these years ago, but I'm not sure where the original .svg sources are. It will be good to have a new base, and some refreshed look.

> The gear and spiral logo was the concept I had in mind. I like the interplay between the spiral and the concentric circles.

I really like the interplay as well. The Debian swirl is something that starts spinning the gear, and after a few turns the gear takes over and can "run" the swirl... That's what comes to mind at least. It's also interesting that you pulled back from the "box" (as in, a host, machine) concept, since we are in the Container Era at this point. Perhaps a new slogan would be in order as well.

> The green tint is complementary to Debian's red. I did not pick it as the main color as it would clash too much.

I'm sorry, but the first thougt I had when I saw the logo was - codiments, specifically [ketchup and mustard](https://www.google.com/search?q=ketchup%20mustard&tbm=isch). There's probably no way to avoid that comparsion with this color palette. Also think pizza.

I would of course stick with the red Debian swirl, but the gear itself could probably be better with a more metallic look. Something around light blue, perhaps? I'm not sure.

> I experimented a bit with the yellow starting with the idea of a copper gear that could potentially show a bit of green as oxidization -- But that looked even more busy on the smaller resolutions, and I liked how the orange tint made it look like a sun. Maybe an idea for a future high-res remix on blender.

Hmm, after looking at [copper gears](https://www.google.com/search?q=copper%20gear&tbm=isch), maybe some darker color would work better and evoke the "copper" more?

> Apart from a few fonts I'd like opinions for, the sampler contains a couple of ideas:
> 
> * Using the first half of the Debian brand
> * Using a hollow font for the _Ops_
> * Using a hacky monospace font
> 
> The half-debian brand clashes with our preferred "DebOps" capitalization, but hey, so does "Debian".
> 
> Freemono was the hackiest I could find -- all my terminals and editors run Fira Code with ligatures and it looks too modern to even look mono in so few characters. :(

Monospace font for the logo is probably a bad idea, these tend to look out of place with the rest of the text on the pages in a regular style.  And I wouldn't try to jam the Debian font and some other together, it will probably clash too much if it's not somewhat stylized which conflicts with use of the font in text form...

From the various proposals I think that I like Roboto Condensed and Quicksand the best. Roboto Condensed uses [the Apache 2.0 license](https://fonts.google.com/specimen/Roboto+Condensed#license), I wonder if we might have issues there... Quicksand is under [the Open Font License](https://fonts.google.com/specimen/Quicksand#license) which is [in the SPDX database](https://spdx.org/licenses/OFL-1.1.html) so we are covered there and can add it in the project. However, it seems that [Open Font License might not be GPL-compatible](https://github.com/FortAwesome/Font-Awesome/issues/1124) - the thread is long and convoluted, and I haven't found a definitive conclusion after cursory glance, so perhaps we should avoid Quicksand just to be on the safe side.

The serif variants of the logo don't do anything for me. I guess that's my bias towards screens vs printed media, where sans-serif fonts probably work better most of the time.

> The current file I have is laid out for editing, if we decide to use it I will provide both the source file and SVGO optimized versions to use directly or create PNGs from. (`lib/images/` is the place, huh?)

Yes, you can put the source files there. Check the [`.reuse/dep5 file](https://github.com/debops/debops/blob/master/.reuse/dep5#L42-L45) for details how to mark the copyright and license information.

> I've darkened and enlarged the tinted backdrop on the 50px variant and I think it's moderately readable at that size, which is the smallest we currently have in the repo.
> 
> I've also darkened the outlines on both the 200px and 50px versions.
> 
> If you think it's called for, I can make an 8-tooth smaller version for 50px and maybe 16px versions when we've settled on the rest of the details.

Smaller number of teeth on the small versions will probably make the logo easier to see, good idea.

> The image is derived from the Debian _Open Use_ Logo (which is the more recognizable one anyway), from the [Debian logos page](https://www.debian.org/logos/), Copyright (c) 1999 [Software in the Public Interest, Inc.](https://www.spi-inc.org/),
> released:
> 
> > under the terms of the GNU Lesser General Public License, version 3 or any later version, or, at your option, of the Creative Commons Attribution-ShareAlike 3.0 Unported License.
> 
> This is pretty much compatible with our usual GPL3, with the CC-BY-SA addition being common sense for visual stuff, so we're fully compatible releasing ours under the same terms and throwing in an attribution for the source image for good measure.

Sounds good to me.

> The fonts I've listed are all out of the Debian repos so I'm trusting them to be SIL or otherwise GPL compatible, I'll procure the specific license when we settle on one.

Ah, I just noticed this - see my notes about the Quicksand font license incompatibility, any thoughts on that?

> ## I hate it!
> You're just the person I was looking for! Tell me why. ;)

I love it... But I could love it more. :heart: :-)

**Comment by tasosalvas** [comment]
Yay feedback!

Heh, condiments didn't even cross my mind. _DebOps: high-tech sauce for your infra_. 

Talking of copper, [this query](https://www.google.com/search?q=copper+gear+patina&tbm=isch) has more of the color I was talking about. I mostly arrived at copper as an excuse to use that green accent which is the red's complemetary. Dark orange/brown could be too close to the swirl's red to reliably contrast across monitors or other media.

We generally want a main hue that's far from the deb red on the color wheel but not its complemetary, especially on the smaller scales, as it can create artifacts on bad screens or print. It's also a good idea for it to contrast in terms of ligthness, primarily for colorblind accessibility. That pretty much points us in the general direction of light hues of either yellow or blue.

I like boxen as a concept, but I was thinking more of the standardization an IaC approach provides in order to make them interoperable and allow us to use them as components to design systems thinking in high-level terms. Also I wanted to give the debian swirl a mohawk :)

I completely agree on Roboto/Quicksand. I was looking into the serifs mostly for the case of using half the debian brand, but even there I found the combo of serif deb/slab ops better.

I don't think the image we derive from the font has to comply with its license, as long as we don't distribute the font itself. It's lighter as an svg shape in presentation anyway, with alt text for screen readers. We're good listing the apt package (i.e. `fonts-quicksand`) somewhere as a build dependency for working with the logo's sources.

If we do need it i.e. for using as a font for headers on the website, wouldn't it be ok if we had it on the repo but kept it out of the packages? I haven't really looked if we're overriding the sphinx theme anywhere yet.

I'll play around with some color variants and the fonts we talked about and have some new images tomorrow.

**Comment by drybjed** [comment]
> Heh, condiments didn't even cross my mind. _DebOps: high-tech sauce for your infra_.

Hmm, well... I guess we mix different igredients together like a stew with DebOps being the recipe. :)

> Talking of copper, [this query](https://www.google.com/search?q=copper+gear+patina&tbm=isch) has more of the color I was talking about. I mostly arrived at copper as an excuse to use that green accent which is the red's complemetary. Dark orange/brown could be too close to the swirl's red to reliably contrast across monitors or other media.
> 
> We generally want a main hue that's far from the deb red on the color wheel but not its complemetary, especially on the smaller scales, as it can create artifacts on bad screens or print. It's also a good idea for it to contrast in terms of ligthness, primarily for colorblind accessibility. That pretty much points us in the general direction of light hues of either yellow or blue.

Sounds reasonable. How about the gear being black/gray/white with red Debian logo? Monochromatic is popular these days in various contexts, but perhaps using only one prominent color (red) might not be a good fit. Let's see what you will come up with.

> I like boxen as a concept, but I was thinking more of the standardization an IaC approach provides in order to make them interoperable and allow us to use them as components to design systems thinking in high-level terms. Also I wanted to give the debian swirl a mohawk :)

How about a Debian swirl with gear teeth then? But that that might not be as apparent as having a separate gear.

> I don't think the image we derive from the font has to comply with its license, as long as we don't distribute the font itself. It's lighter as an svg shape in presentation anyway, with alt text for screen readers. We're good listing the apt package (i.e. `fonts-quicksand`) somewhere as a build dependency for working with the logo's sources.

Sounds good. The logo should probably have its own page in the documentation then.

> If we do need it i.e. for using as a font for headers on the website, wouldn't it be ok if we had it on the repo but kept it out of the packages? I haven't really looked if we're overriding the sphinx theme anywhere yet.

Sure, the current logo is used in the ReadTheDocs/Sphinx site directly from the repository which is cloned for deployment. Logos are not included in the Python/Ansible Galaxy builds. The logo in the documentation side [is referenced in the `docs/conf.py` file](https://github.com/debops/debops/blob/master/docs/conf.py#L222) which probably could use a symlink from the `lib/images/` directory, or reference the file directly with `../lib/images/...` path. Needs to be tested.

In the past DebOps had a [landing page](https://github.com/drybjed/debops.github.io) designed by @nickjj. We could probably make a new one with a blog (via Jekyll, not sure about theme), links to other important sites, etc. If you feel creative, you could try the logo with some Jekyll themes to see what works well.

> I'll play around with some color variants and the fonts we talked about and have some new images tomorrow.

Looking forward to it. :)

**Comment by nickjj** [comment]
I really like the concept of the new logo. @drybjed's suggestion of using grey tones for the gear could help with it not feeling like MustardOps. Yellow is such a hard color to use.

Another suggestion might be to make the gear look more rusty, so more browns and oranges. Maybe that could blend in with the red swirl, but it might start to bleed in too much at smaller sizes.

Very cool initiative, thanks for taking the time out to make it.

For context, here's a link to the old landing page: https://web.archive.org/web/20150206072851/https://debops.org/

**Comment by ypid** [comment]
Big thanks also from me. I like the direction of it and only have one wish to add to the discussion:

> The half-debian brand clashes with our preferred "DebOps" capitalization, but hey, so does "Debian".

Please lets be consistent with the capitalization: "DebOps" :) Also, as a typography nerd with LaTeX background, mixing different fonts scares me.

**Comment by tasosalvas** [comment]
## DebOps: Gotta run them all!
![debops-copper](https://user-images.githubusercontent.com/245478/97541004-1c605f00-19cd-11eb-9201-6d950a3f2d6d.png)
![debops-cobalt](https://user-images.githubusercontent.com/245478/97541011-1e2a2280-19cd-11eb-91e2-60b427101e74.png)
![debops-steel](https://user-images.githubusercontent.com/245478/97540997-19fe0500-19cd-11eb-8dd8-c280743f9180.png)

Hrm, the struts on the PNGs aren't really consistent with what I have on the svg, I'll redo them once we've settled on one, probably something to do with instancing.

Also included are Roboto, Quicksand, plus a Roboto half-outline version we didn't really discuss. I'm open to other font suggestions too, if someone has one in mind.

> lets be consistent with the capitalization: "DebOps" :)

Fair enough, just threw the idea so we have something to talk about. How do you feel about the half-outline version? :)

> Another suggestion might be to make the gear look more rusty, so more browns and oranges. Maybe that could blend in with the red swirl, but it might start to bleed in too much at smaller sizes.

Yup, I first tried rusty copper, so greens too, and it was an absolute mess. Then I overcompensated with the yellow, I think :). The current copper version is readable at 50px though. Don't know about 16 yet.

> How about a Debian swirl with gear teeth then? But that that might not be as apparent as having a separate gear.

Yeah my first sketches on paper were exactly that, kinda like the punx not dead question mark. It was messy and read like just the debian logo. Then I liked the circles and spiral thing. Plus this will also be easier to extrude and 3d print :D. Also, unless you really want it that way, I'd rather not start over ;)

**Comment by drybjed** [comment]
That's a much better version! I think that the gradient helps a lot with the first impression. Finally I can see a copper cog wheel and not a pizza dough with cheese and ketchup on top. :+1: 

As for the colors... Copper is awesome, warm, I love it. I think it meshes well with the red Debian swirl. Cobalt and Steel, not so much - they feel cold and uninviting.

> Also included are Roboto, Quicksand, plus a Roboto half-outline version we didn't really discuss. I'm open to other font suggestions too, if someone has one in mind.

I think that Roboto is more close to the font used in the Debian logos than Quicksand, so I would vote for that one. I'm not a fan of the outline version, perhaps a two-colored variant would be interesting? Black 'Deb', dark copper 'Ops'?

> Then I liked the circles and spiral thing. Plus this will also be easier to extrude and 3d print :D.

Whoa... 3d-printed DebOps cogwheel with a clear stand you can plug it into *and it rotates*. I'll take eight!

> Also, unless you really want it that way, I'd rather not start over ;)

The current design is great, it stays. :-)

**Comment by tasosalvas** [comment]
> I think that the gradient helps a lot with the first impression. 

Yeah, I spent some more time touching it up since we'd cleared the concept, I'll work it a bit more now that we've settled on color and check if the 16px version stands as it is or if it needs 8 teeth.

I like the orange one best too, although steel looks pretty slick and I was afraid it would be the obvious sensible choice :) Warm is a good consideration, yeah.

Lol pizza is so outside my budget right now that you didn't even make me hungry with your food talk :p

> 3d-printed DebOps cogwheel with a clear stand you can plug it into and it rotates.

Just as I was worrying none of my friends have a dual head printer to do 2 colors at once, so it would need to be assembled, you up the stakes. It all begins with a vision, though... :)

> a two-colored variant

I think colors on the brand would limit how it can be used on its own. Orange would definitely need an outline or we'd always have to pay extra attention balancing the background's lightness against it. Maybe all outlined, red deb orange ops? I'll check it out and if it's not terrible I'll post samples. 

Ok, so, I'm going to bed because I'm keeping Hawaii time today, leave some time for feedback from everyone else, then I'll prepare the PR.

**Comment by nickjj** [comment]
I'm torn between the copper and steel one.

On one hand, the copper one does feel warm and it looks like a well operating gear. On the other hand, the steel one reminds me more of a server and it has a clean industrial look to it.

Debian's official colors tend to use blue and silver as secondary colors too based on their site https://www.debian.org/ but I don't know if that should be taken into account.

**Comment by ypid** [comment]
> I'm torn between the copper and steel one.

Same with me. The cobalt looks nice but I like the others better. I at first preferred the steel one but on second look, I guess I prefer the copper one overall. But I agree with @nickjj, the steel one probably has the highest acceptance because it has a clean look.

I played a bit and ended up putting the copper in [my timeline](https://me.ypid.de/timeline/) for testing. I also noticed for this size, it is probably better to have less but bigger teeth.

> The logo should probably have its own page in the documentation then.

As I have been searching for logos for the timeline often, I suggest the URL https://debops.org/brand but it could also be https://debops.org/DebOpsLogo to be more in line with Debian:

* https://wiki.debian.org/DebianLogo
* https://www.elastic.co/brand

It could redirect to the documentation as long as we don’t have a start page.

About fonts, I like Quicksand most. But this is not a strong preference. I cannot comment on licensing of fonts unfortunately.

I really appreciate how much thought you put into it!

For moving forward, @tasosalvas maybe post each variant in its own comment so that the reactions feature can be used by people who just peek over this issue.

**Comment by tasosalvas** [comment]
Still fiddling with details and tidying up the source file and misc meta stuff for the PR.


> I played a bit and ended up putting the copper in my timeline for testing

Oooh I really like how it looks there. The teeth are readable, but I'm making one with half the teeth for the 16px favicon anyway so we can decide which one to use for the 50 later.

I admit my ulterior motive is to have the debops icon in such a collection for my own site (okay, yeah, and a bragging post about having designed it) :) Mine's going to be more streamlined towards selling sites, although I'm constantly torn on whether it should also be my nerd blog or not.


> Debian's official colors tend to use blue and silver as secondary colors

I think Debian's aim was to balance their red with something as unobtrusive as possible. In our case it means deferring all color choice to Debian, and it might make the logo readable _as_ Debian at a glance.

Blue (referring to both Cobalt and the blue tint on Steel) is kinda the safe choice we give clients who have a hard time expressing opinions about their taste... there's a lot of blue going around ;) So speaking as a graphic artist I tend to appreciate the choices that add some character over those that are just safe. I do take care for all choices I present to be viable in the first place, of course.

I admit Cobalt might be suffering from the same issues yellow had in the beginning -- too little time spent on fine-tuning the color.


> About fonts, I like Quicksand most. But this is not a strong preference.

I like Quicksand too, pretty much for the reason listed above regarding the use of blue.


> A page on the website

In terms of our current structure, the place would be something like 
_https://docs.debops.org/en/master/meta/brand.html_

We can put a redirect if we make a landing page, but seeing as there's little standardization for this type of url I think menu positioning is the place to make it visible.

"Press" or "Press kit" is something journalists often look for, so these are some other names for this type of content. It could include the slogan, a quick mission statement, links to _philosophy_ and other similar pages, and any and all visual material and notes on their treatment.

I could see a few derivative wallpapers living there as well. It could be cool to have those as defaults in stuff for debops for desktops, as we were discussing at some point. Anyway, I'm getting waay ahead of myself. Wallpapers are easy, though, might do soon.

Ansible has an excruciatingly pedantic one I find funny, I guess put up when they registered their precious trademark
https://docs.ansible.com/ansible/latest/dev_guide/style_guide/trademarks.html


> I really appreciate how much thought you put into it!

Thank you! <3 I like to root as much of my work as possible on tangible concepts, primarily accessibility and color theory and leave "creation" for the possibility space between.


> post each variant in its own comment

Okay, I'll do a final round with 4 permutations between Copper, Steel, Roboto, Quicksand and aggressively tag whoever I know. I have touched up copper a bit since the last samples, but I think steel is simple enough to inherit the changes without too much fuss.

Soon™

**Comment by ypid** [comment]
> I admit my ulterior motive is to have the debops icon in such a collection for my own site

I see this as a nice "deal". Win win. I am happy that DebOps gets such a professionally designed logo and I am interested to learn more how you create it. I have like 12h background with Inkscape but no real creative work :)

**Comment by tasosalvas** [comment]
# Final voting round

Okay folks, time to set the final design so I only have to worry about licenses, naming and other bookkeeping stuff until the PR.

I might still add tweaks to the winning design, but nothing too radical; The images I'm posting are derived from the final assets.

(if you're not seeing 4 image posts yet just wait 5 mins, I'm uploading them)


## What you're looking at
Each of the samples is a 1024x1024 image containing:
* A large scale version based on the fully detailed source file
* A 200px version based on the fully detailed source file
* 50px and 16px versions based on the simplified source file
* 50px and 16px versions based on the 8-spoke alternate design

Do make sure you're looking at the images at exactly 100% scale, as the tiny versions are greatly affected by the slightest of zooms.


## Rules
We're voting for 3 things:
* Color scheme: Copper vs. Steel
* Font choice: Roboto Condensed vs. Quicksand
* Simplified icon version: 16 spoke vs 8 spoke

I'm only posting 4 permutations, so you'll have to use the reaction emojis for the last choice:
* :rocket: Use the 16-spoke version for both 50px and 16px
* :tada: Use the 16-spoke version for 50px and the 8-spoke version for 16px
* :eyes: Use the 8-spoke version for both 50px and 16px

Votes are cool and all, but as I see it the final choice stands with our BDFL and our opinions are just data points for him to make his decision ;)

If you have opinions or other feedback I'm definitely interested in hearing them. Especially if you have good reasons something should be changed, I'd rather hear it sooner rather than later. Also feel free to argue for your favorite choice.

**Comment by tasosalvas** [comment]
![debops-final-sampler-copper-quicksand](https://user-images.githubusercontent.com/245478/98025133-fcd49680-1e11-11eb-97cc-b1fdbc1440c0.png)

**Comment by tasosalvas** [comment]
![debops-final-sampler-copper-roboto](https://user-images.githubusercontent.com/245478/98025168-0827c200-1e12-11eb-9ba5-a31ac6f078fa.png)

**Comment by tasosalvas** [comment]
![debops-final-sampler-steel-quicksand](https://user-images.githubusercontent.com/245478/98031442-29d97700-1e1b-11eb-9364-5c79e2e99e4d.png)

**Comment by tasosalvas** [comment]
![debops-final-samplers-steel-roboto](https://user-images.githubusercontent.com/245478/98031490-3eb60a80-1e1b-11eb-8f40-143fb5025f63.png)

**Comment by hvisage** [comment]
I vote for the pink one, with blue dots and green stripes.
Or rather: I'll give @drybjed my proxy vote ;)

**Comment by nickjj** [comment]
Before voting I have 1 question:

In the 8 gear vs more gears variant the middle looks very different. For example the 8 gear variant is much lighter, especially in the steel version. The thin swirl is also positioned much differently.

Was this intentional?

Just asking because this is much more than a number of gears change between the 2 variants.

**Comment by AnBuKu** [comment]
Interesting approach of Debian logo + Gear wheel
Two remarks:
Keep it clear - Thin lines and shadows might work for billboard, but less for favicon
Avoid too many colors and no or modest contrast - Visual impaired people might be thankful; if logo works for b/w it's no disadvantage

cheers and keep up your good work. h.

**Comment by tasosalvas** [comment]
> the middle looks very different.

Dang, no, nice catch @nickjj, the lightness wasn't intentional... I had switched off the gradient overlay on the `simplified` version by mistake.

The positioning was, in order to get closer to a square shape and take advantage of more of the 16x16 area. Plus the outer circle is not as strongly implied by the 8 spokes, so the swirl follows the central circle more closely.

@AnBuKu, I'm testing every step of the way on greyscale, I believe the end result is generally accessible.
If you do have trouble discerning the shapes I will definitely take your word for it and bump up the contrast - by making the gear lighter as we're essentially anchored to the Debian red's Lightness

I'd also like to note that the steel gear is simply a greyscale version of the copper one and both have the exact same lightness values, so they should be equivalent in terms of colorblind accessibility.

**Comment by imrejonk** [comment]
Wow, thanks a lot for putting all this effort into the logo, @tasosalvas! I just cast my vote. May the best design win :1st_place_medal:

**Comment by tasosalvas** [comment]
Ok, @drybjed, call it? Or Monday? I think anyone who was going to see it has.

**Comment by drybjed** [comment]
@tasosalvas Sounds good to me. So the first version wins then. :)

**Comment by tasosalvas** [comment]
Ok, we got a tie between 16 spokes for all and 8 spokes for just the 16px.

Since both the small versions are different SVG files, I think it would be simpler to have 2 instead of 3 variants, but I have the files anyway so it's no problem to go either :tada: or :rocket:

It generally seems cleaner to me to commit the source files and a makefile that makes all the rest. However, it would need:
* `inkscape`, of which I'm currently using the latest version from the Flatpak they provide and as I understand at least their CLI significantly changed between this and the buster version. (`buster-backports` should be ok)
* [svgo](https://github.com/svg/svgo) which is an `npm` package that optimizes SVG for the web (185k to 55k for our large version). 

I will be including the source SVG files in any case and documenting those dependencies. I'm thinking though maybe just committing PNG and optimized SVG versions along with the Makefile that creates them would be better, since these applications have nothing to do with the rest of debops development (and I wouldn't wish the `Node.js` ecosystem on anyone).

**Comment by drybjed** [comment]
Sure, PNG and optimized SVG sound good, especially that they can be derectly used in the documentation site. Detailed instructions how to generate these in the documentation should suffice.

As for deciding between 16-spoke and 8-spoke versions... @ser, any preference? You are an outlier here. :)

**Comment by ypid** [comment]
I think @ser broke the tie :) So I guess "the 16-spoke version for 50px and the 8-spoke version for 16px" it is.

**Comment by drybjed** [comment]
Acutally there's a tie if you count @imrejonk choice of the 16-spoke version for both 50px and 16px. I think that we should go with that choice, it will result in 2 source files instead of 3 for the other version. More votes could help, but @tasosalvas has been waiting long enough. :)

**Comment by ypid** [comment]
I just rechecked the licenses so that I can give proper attribution when using it (in my [timeline](https://me.ypid.de/timeline/)).

From https://github.com/debops/debops/issues/1541#issue-731664910

> The image is derived from the Debian Open Use Logo (which is the more recognizable one anyway), from the Debian logos page, Copyright (c) 1999 Software in the Public Interest, Inc.,
released:

>>  under the terms of the GNU Lesser General Public License, version 3 or any later version, or, at your option, of the Creative Commons Attribution-ShareAlike 3.0 Unported License.

> This is pretty much compatible with our usual GPL3, with the CC-BY-SA addition being common sense for visual stuff, so we're fully compatible releasing ours under the same terms and throwing in an attribution for the source image for good measure.

I agree that anybody can "lock down" a work released under LGPL to GPL which was done here to be in line with the default DebOps license. But I am not sure if the same can be done with the CC license here. To be on the safe side, we should probably stick with the one that Debian uses: CC-BY-SA-3.0

Ref: https://docs.debops.org/en/master/meta/logo.html#copyright-and-licensing

@tasosalvas What do you say?
