### ISSUE TITLE
[debops.postfix] maincf configuration partially appied

### ISSUE THREAD

**Issue by francois-claude** [debops/debops#1544]
When using this configuration, options 'smtp_sasl_password_maps' and 'smtp_sasl_tls_security_options' are not applied to main.cf on the host. 

`postfix__maincf:

  - name: 'smtp_sasl_auth_enable'
    value: True

  - name: 'smtp_tls_security_level'
    value: 'encrypt'

  - name: 'smtp_sasl_tls_security_options'
    value: 'noanonymous'

  - name: 'relayhost'
    value: '[smtp.gmail.com]:587'

  - name: 'smtp_sasl_password_maps'
    value: [ 'hash:${config_directory}/smtp_sasl_password_maps' ]`

please advise

**Comment by francois-claude** [comment]
the missing values are added if state: 'present' is added to each variable

**Comment by drybjed** [comment]
Documentation has been amended, closing.
