### ISSUE TITLE
[etckeeper] Use py3-compatible version from buster-backports

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#1560]
`debops.etckeeper` installs etckeeper from the Debian Stable repository, which is currently at version 1.18.10-1 for Debian 10. This package however depends on Python 2. The role does not install etckeeper by default when a Python 2 environment is not present on the host (see [etckeeper__enabled](https://docs.debops.org/en/master/ansible/roles/etckeeper/defaults/main.html#envvar-etckeeper__enabled)).

I propose that, on Debian 10, we install etckeeper from buster-backports. The package in that repository (version 1.18.14-1~bpo10+1) depends on Python 3 instead. This should allow default installation of etckeeper on all hosts, not just the hosts that have a Python 3 environment.

Let me know what you think of this and I'll put some effort in.

**Comment by ypid** [comment]
As discussed, nice idea and thumps up for finding out that this is now solved via backports. Various other roles in DebOps install packages from backports so that is a common thing to do for issues like this.
