### ISSUE TITLE
slapd: backup script doesn't work if the back_monitor isn't loaded

### ISSUE THREAD

**Issue by Alphix** [debops/debops#1595]
If the back_monitor module isn't loaded, the backup script silently fails to backup any databases at all.

The reason seems to be the BACKUP_LDAP_SEARCH_FILTER in /usr/local/sbin/slapd-snapshot which includes a check for "(!(objectClass=olcMonitorConfig))", which appears to be undefined (rather than false) when back_monitor isn't loaded.

To be clear, this isn't severe (since the slapd role does load the module), but it does make the backup script a bit less universally useful and it's also a potential gotcha for the future (e.g. in case the slapd role would be changed to not load the module).

My LDAP-fu isn't good enough, so I'm not sure what the best way to address this is

```bash
root@vmtest:~# ldapsearch -LLLQ -Y EXTERNAL -H ldapi:/// -b cn=module{0},cn=config
dn: cn=module{0},cn=config
objectClass: olcModuleList
cn: module{0}
olcModulePath: /usr/lib/ldap
olcModuleLoad: {0}back_mdb

root@vmtest:~# /usr/local/sbin/slapd-snapshot latest
root@vmtest:~# ldapadd -Q -Y EXTERNAL -H ldapi:/// <<EOF
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: back_monitor
EOF
modifying entry "cn=module{0},cn=config"

root@vmtest:~# /usr/local/sbin/slapd-snapshot latest
slapd-snapshot: Creating a snapshot of the slapd:0 database
slapd-snapshot: Dumping the slapd:0 database
slapd-snapshot: Snapshot of the slapd:0 database created successfully
slapd-snapshot: Creating a snapshot of the slapd:1 database
slapd-snapshot: Enabling read-only mode in the slapd:1 database
slapd-snapshot: Dumping the slapd:1 database
5ff65183 mdb_monitor_db_open: monitoring disabled; configure monitor database to enable
slapd-snapshot: Disabling read-only mode in the slapd:1 database
slapd-snapshot: Snapshot of the slapd:1 database created successfully
```

**Comment by drybjed** [comment]
I set up a test instance of `slapd` with monitoring backend disabled. The good news is that `slapd-snapshot` script still managed to create the backup properly. The "monitoring disabled; configure monitor database to enable" message seems to be [an informational message from OpenLDAP developers](https://openldap-devel.openldap.narkive.com/kqP7QqMf/monitoring-disabled-message) and can be safely ignored.

So the question is, how did you determine that the script does not backup the database properly? Did you change anything from the DebOps `slapd` role that might point to a different issue? Did you try the `slapd-snapshot` script on a vanilla `slapd` installation?

**Comment by Alphix** [comment]
Yeah, I tried using the `slapd-snapshot` script on a vanilla `slapd` installation. Sorry if that wasn't clear.

So for anyone else reading: the `slapd-snapshot` script **does** work as expected with the `slapd` DebOps role. It just fails when `back_monitor` isn't loaded in `slapd` (e.g. with the vanilla `slapd` installation). Ideally the script should work whether the `back_monitor` module is loaded or not.

**Comment by drybjed** [comment]
Ummm... I didn't load the `back_monitor` module during my test, and the script still did the snapshots. Did you see the script exit with an error? Did you check that the snapshots are present in `/var/backups/slapd/` and they are not empty?

**Comment by drybjed** [comment]
@Alphix Sorry, my mistake - I just checked the script on vanilla `slapd` installation, and indeed it stops whem `olcMonitorConfig` is not enabled. Time to find a workaround.

**Comment by drybjed** [comment]
This issue will be fixed by https://github.com/debops/debops/pull/1599/commits/9993edbddeebb0dc2ebc00b1ac0bf5fe0a8e57a2 commit.
