### ISSUE TITLE
fix privacy issue for nextcloud webdav access

### ISSUE THREAD

**Issue by jankowa** [debops/debops#1626]
When accessing nextcloud via webdav the webdav link nextcloud provides in their settings is like:

`https://nextcloud.example.org/remote.php/dav/files/user@example.org/`

But if you access it under

`https://nextcloud.example.org/remote.php/dav/files/`

all users are listed - even if you don't have access rights. This is maybe a kind of nextcloud bug - because there are settings in nextcloud for not list users to other users via autocompletion nor in address book. But they are still all listed via webdav.

The way to suppress this are two lines in nginx config:
```
diff --git a/ansible/roles/owncloud/defaults/main.yml b/ansible/roles/owncloud/defaults/main.yml
index 56cd9f8cd..d0df68ff2 100644
--- a/ansible/roles/owncloud/defaults/main.yml
+++ b/ansible/roles/owncloud/defaults/main.yml
@@ -2207,6 +2207,14 @@ owncloud__nginx__dependent_servers:
         options: |
           deny all;
 
+      - pattern: '~ ^/remote.php/dav/(adressbooks|avatars|calendars|comments|files|principals|provisioning|trashbin|uploads|versions)/$'
+        options: |
+          return 403;
+
+      - pattern: '~ ^/remote.php/dav/(adressbooks|avatars|calendars|comments|files|principals|provisioning|trashbin|uploads|versions)$'
+        options: |
+          return 403;
+
       - pattern: '~ ^\/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy)\.php(?:$|\/)'
         options: |
           include fastcgi_params;

```
We need two lines because of trailing "/" - but maybe nginx experts know a better way. I didn't find one.

**Comment by drybjed** [comment]
I'm not sure if this should be solved on the `nginx` level. How would this impact shared folders/files between users? Do they still show up over WebDAV with `nginx` protection applied?

**Comment by jankowa** [comment]
If this should be fixed on nginx level is a good question. I'm also not shure about. On the one hand: in an organization where everybody can see everybodies UID this is not really a problem. But on the other hand it contradicts the idea of configuration option in nextcloud not to disclose IDs. 

Filesharing is not affected at all since it's not realized through access rights via webdav (is it possible at all? I think it isn't). While you acces files via webdav shared folders are just tranparently displayed inside your own user space - just like in the webfrontend.

Problem is described here: https://help.nextcloud.com/t/solved-hardening-security-mydomain-nextcloud-config-listing-files-in-browser/12356

There is not much documentation about at all.

**Comment by jankowa** [comment]
one more idea: Since one can change `owncloud__nginx__dependent_servers:` it's also possible to harden this in group or host config. But still maybe it's a good idea to harden this by default?

**Comment by drybjed** [comment]
I would go with hardening it by default then. @ypid, any thoughts on this?

**Comment by ypid** [comment]
I tried to reproduce this but I am not sure what you mean @jankowa 

```
cadaver 'https://cloud.example.com/remote.php/dav/files/'
Authentication required for Nextcloud on server `cloud.example.com':
Username: admin-user
Password: 
dav:/remote.php/dav/files/> ls
Listing collection `/remote.php/dav/files/': failed:
405 Method Not Allowed
dav:/remote.php/dav/files/> cd admin-user
dav:/remote.php/dav/files/admin-user/> ls
Listing collection `/remote.php/dav/files/admin-user/': succeeded.
Coll:   Documents                              0  Apr  2  2018
Coll:   Photos                                 0  Apr  2  2018
        Nextcloud Manual.pdf             4143532  Apr  2  2018
        Nextcloud.mp4                     462413  Apr  2  2018
        Readme.md                              1  Oct  3 18:30
dav:/remote.php/dav/files/admin-user/> cd ..
dav:/remote.php/dav/files/> cd existing_user
dav:/remote.php/dav/files/existing_user/> ls
Listing collection `/remote.php/dav/files/existing_user/': collection is empty.
dav:/remote.php/dav/files/existing_user/> cd ..
dav:/remote.php/dav/files/> cd sdfsd
Could not access /remote.php/dav/files/sdfsd/ (not WebDAV-enabled?):
404 Not Found
dav:/remote.php/dav/files/> 
```

* Authentication is needed before anything.
* Existing users are not listed.
* The only "privacy leak" I see is that one can brute force users to see if they exist.

Accessing this URL with a browser (authenticated) only shows "This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.".

Nextcloud 19.0.8

Webserver directory listing should already be disabled. For each new Nexctloud release I update the `defaults/main.yml` based on https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html

Can you demonstrate what you mean? Also, please check the official docs I posted. That is our reference and there needs to be a good reason when we should diverge from that. You are encouraged to diff the official config with ours to review this. More review cannot hurt.

**Comment by jankowa** [comment]
Hi @ypid ,

this is interesting because I can reproduce the behavior  also only in one of our nextcloud instances. Since normally they behave like you describe one is listing user names if you access `davs://cloud.example.com/remote.php/dav/files/` (e.g. in gnome file browser).

![davs03](https://user-images.githubusercontent.com/5942664/107225893-b054b480-6a19-11eb-9436-6f43dc2248c7.png)

The nginx-configurations are exactly the same (debops default). Both are behind reverse proxy, both are the same version (20.0.7). The only difference is: in the nextcloud showing all users the ldap auth backend is active.

The "405 Method Not Allowed" is produces in the nextcloud. Right? No in nginx. So my only idea is that under special circumstances and special configuration there is a bug in nextcloud.

**Comment by ypid** [comment]
I am not using LDAP with Nextcloud so it could be a bug in Nextcloud. When you confirmed that we use exactly the same Nginx config as the upstream example, I would say it is better to report this to Nextcloud. For good measure, you can [switch to Apache for testing](https://docs.debops.org/en/master/ansible/roles/owncloud/getting-started.html#switching-webservers) (that is the only reason I wrote the Apache role, when reporting/debugging Nextcloud as this is their supported platform ;-))

Note that the role does not officially support NC 20 yet. Please see #1593:

> NC 20 will need a bit more Nginx changes that is why I did not add support for it yet.

**Comment by jankowa** [comment]
Doesn't affect actual versions of nextcloud anymore.
