### ISSUE TITLE
"secrets" folder is created one up from current directory

### ISSUE THREAD

**Issue by julien-lecomte** [debops/debops#1653]
While running `debops service/nullmailer --limit nwn.roum.pw` in folder `~/src/lecomte.at/ansible-lecomte-playbook`, a folder called `secret` will be generated in `~/src/lecomte.at/`.

No folder should be created one folder above where the command is launched.

`.debops.cfg` is 

```
$ cat .debops.cfg 

# -*- conf -*-

[paths]
# data-home: /opt/debops

[ansible defaults]
display_skipped_hosts = False
retry_files_enabled = False
stdout_callback = yaml
timeout = 60

callback_whitelist = profile_tasks

nocows = 1

inventory = roster.yml

# remote_user = jdoe
# remote_tmp  = /tmp/.ansible-${USER}/tmp

[ansible inventory]
cache = no
enabled = roster
enable_plugins = roster
ignore_patterns = secret
host_pattern_mismatch = ignore

[ansible paramiko]
;record_host_keys=True

[ansible ssh_connection]
ssh_args = 
# ssh_args = -o ControlMaster=auto -o ControlPersist=600s
# pipelining = true
```

**Comment by drybjed** [comment]
By default the `secret/` directory is created relative to the Ansible inventory, one subdirectory up. You specified that the Ansible inventory is a file in the root of the DebOps project directory; if you want to do that you can redefine the path to the `secret/` directory by setting the `secret` variable yourself, in that inventory. Or, move the `roster.yml` file into a subdirectory, for example `ansible/inventory/roster.yml`.

**Comment by julien-lecomte** [comment]
Ansible thinks the inventory file is the root of the setup? That kinda sucks.

**Comment by drybjed** [comment]
No, you told it that the inventory is the `roster.yml` file. By default it would have been `ansible/inventory/` directory (specified by DebOps), which would then put the `secret/` directory in `ansible/secret/`. If you want to blame someone, blame me since I decided that the `secret/` directory should be created relative to the Ansible inventory to avoid specifying the absolute path each time. :-)
