### ISSUE TITLE
Debops failed after upgrade 

### ISSUE THREAD

**Issue by krystophe** [debops/debops#1664]
Hi,

I made an upgrade of my debops server with this command "pip3 install --upgrade debops".
Now i'm on Version: 2.2.1
After that I start a debops  -l my_vm but it's failed.

Thanks for you help.

here is the error message:

09:48:21 TASK [secret : Create secret directories on Ansible Controller] ****************
09:48:21 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/lib'
09:48:21 failed: [my_vm -> localhost] (item=pki/lib) => changed=false 
09:48:21   ansible_loop_var: item
09:48:21   item: pki/lib
09:48:21   module_stderr: |-
09:48:21     Traceback (most recent call last):
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402900.8271444-241555610006660/AnsiballZ_file.py", line 102, in <module>
09:48:21         _ansiballz_main()
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402900.8271444-241555610006660/AnsiballZ_file.py", line 94, in _ansiballz_main
09:48:21         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402900.8271444-241555610006660/AnsiballZ_file.py", line 40, in invoke_module
09:48:21         runpy.run_module(mod_name='ansible.modules.files.file', init_globals=None, run_name='__main__', alter_sys=True)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 205, in run_module
09:48:21         return _run_module_code(code, init_globals, run_name, mod_spec)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
09:48:21         mod_name, mod_spec, pkg_name, script_name)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
09:48:21         exec(code, run_globals)
09:48:21       File "/tmp/ansible_file_payload__5d__441/ansible_file_payload.zip/ansible/modules/files/file.py", line 940, in <module>
09:48:21       File "/tmp/ansible_file_payload__5d__441/ansible_file_payload.zip/ansible/modules/files/file.py", line 926, in main
09:48:21       File "/tmp/ansible_file_payload__5d__441/ansible_file_payload.zip/ansible/modules/files/file.py", line 662, in ensure_directory
09:48:21       File "/tmp/ansible_file_payload__5d__441/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1342, in set_fs_attributes_if_different
09:48:21       File "/tmp/ansible_file_payload__5d__441/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1109, in set_mode_if_different
09:48:21     PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/lib'
09:48:21   module_stdout: ''
09:48:21   msg: |-
09:48:21     MODULE FAILURE
09:48:21     See stdout/stderr for the exact error
09:48:21   rc: 1
09:48:21 ok: [my_vm -> localhost] => (item=pki/ca-certificates/by-host/my_vm)
09:48:21 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/ca-certificates/by-group/all'
09:48:21 failed: [my_vm -> localhost] (item=pki/ca-certificates/by-group/all) => changed=false 
09:48:21   ansible_loop_var: item
09:48:21   item: pki/ca-certificates/by-group/all
09:48:21   module_stderr: |-
09:48:21     Traceback (most recent call last):
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.277809-47981655764825/AnsiballZ_file.py", line 102, in <module>
09:48:21         _ansiballz_main()
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.277809-47981655764825/AnsiballZ_file.py", line 94, in _ansiballz_main
09:48:21         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.277809-47981655764825/AnsiballZ_file.py", line 40, in invoke_module
09:48:21         runpy.run_module(mod_name='ansible.modules.files.file', init_globals=None, run_name='__main__', alter_sys=True)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 205, in run_module
09:48:21         return _run_module_code(code, init_globals, run_name, mod_spec)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
09:48:21         mod_name, mod_spec, pkg_name, script_name)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
09:48:21         exec(code, run_globals)
09:48:21       File "/tmp/ansible_file_payload_66a7zf6w/ansible_file_payload.zip/ansible/modules/files/file.py", line 940, in <module>
09:48:21       File "/tmp/ansible_file_payload_66a7zf6w/ansible_file_payload.zip/ansible/modules/files/file.py", line 926, in main
09:48:21       File "/tmp/ansible_file_payload_66a7zf6w/ansible_file_payload.zip/ansible/modules/files/file.py", line 662, in ensure_directory
09:48:21       File "/tmp/ansible_file_payload_66a7zf6w/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1342, in set_fs_attributes_if_different
09:48:21       File "/tmp/ansible_file_payload_66a7zf6w/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1109, in set_mode_if_different
09:48:21     PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/ca-certificates/by-group/all'
09:48:21   module_stdout: ''
09:48:21   msg: |-
09:48:21     MODULE FAILURE
09:48:21     See stdout/stderr for the exact error
09:48:21   rc: 1
09:48:21 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/ca-certificates/by-group/debops_service_pki'
09:48:21 failed: [my_vm -> localhost] (item=pki/ca-certificates/by-group/debops_service_pki) => changed=false 
09:48:21   ansible_loop_var: item
09:48:21   item: pki/ca-certificates/by-group/debops_service_pki
09:48:21   module_stderr: |-
09:48:21     Traceback (most recent call last):
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.4885097-6974732047845/AnsiballZ_file.py", line 102, in <module>
09:48:21         _ansiballz_main()
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.4885097-6974732047845/AnsiballZ_file.py", line 94, in _ansiballz_main
09:48:21         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.4885097-6974732047845/AnsiballZ_file.py", line 40, in invoke_module
09:48:21         runpy.run_module(mod_name='ansible.modules.files.file', init_globals=None, run_name='__main__', alter_sys=True)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 205, in run_module
09:48:21         return _run_module_code(code, init_globals, run_name, mod_spec)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
09:48:21         mod_name, mod_spec, pkg_name, script_name)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
09:48:21         exec(code, run_globals)
09:48:21       File "/tmp/ansible_file_payload_ynu6l8pp/ansible_file_payload.zip/ansible/modules/files/file.py", line 940, in <module>
09:48:21       File "/tmp/ansible_file_payload_ynu6l8pp/ansible_file_payload.zip/ansible/modules/files/file.py", line 926, in main
09:48:21       File "/tmp/ansible_file_payload_ynu6l8pp/ansible_file_payload.zip/ansible/modules/files/file.py", line 662, in ensure_directory
09:48:21       File "/tmp/ansible_file_payload_ynu6l8pp/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1342, in set_fs_attributes_if_different
09:48:21       File "/tmp/ansible_file_payload_ynu6l8pp/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1109, in set_mode_if_different
09:48:21     PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/ca-certificates/by-group/debops_service_pki'
09:48:21   module_stdout: ''
09:48:21   msg: |-
09:48:21     MODULE FAILURE
09:48:21     See stdout/stderr for the exact error
09:48:21   rc: 1
09:48:21 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/realms/by-group/all/domain/external'
09:48:21 failed: [my_vm -> localhost] (item=pki/realms/by-group/all/domain/external) => changed=false 
09:48:21   ansible_loop_var: item
09:48:21   item: pki/realms/by-group/all/domain/external
09:48:21   module_stderr: |-
09:48:21     Traceback (most recent call last):
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.6977751-184158110586434/AnsiballZ_file.py", line 102, in <module>
09:48:21         _ansiballz_main()
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.6977751-184158110586434/AnsiballZ_file.py", line 94, in _ansiballz_main
09:48:21         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
09:48:21       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.6977751-184158110586434/AnsiballZ_file.py", line 40, in invoke_module
09:48:21         runpy.run_module(mod_name='ansible.modules.files.file', init_globals=None, run_name='__main__', alter_sys=True)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 205, in run_module
09:48:21         return _run_module_code(code, init_globals, run_name, mod_spec)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
09:48:21         mod_name, mod_spec, pkg_name, script_name)
09:48:21       File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
09:48:21         exec(code, run_globals)
09:48:21       File "/tmp/ansible_file_payload_ev6ectew/ansible_file_payload.zip/ansible/modules/files/file.py", line 940, in <module>
09:48:21       File "/tmp/ansible_file_payload_ev6ectew/ansible_file_payload.zip/ansible/modules/files/file.py", line 926, in main
09:48:21       File "/tmp/ansible_file_payload_ev6ectew/ansible_file_payload.zip/ansible/modules/files/file.py", line 662, in ensure_directory
09:48:21       File "/tmp/ansible_file_payload_ev6ectew/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1342, in set_fs_attributes_if_different
09:48:21       File "/tmp/ansible_file_payload_ev6ectew/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1109, in set_mode_if_different
09:48:21     PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/realms/by-group/all/domain/external'
09:48:21   module_stdout: ''
09:48:21   msg: |-
09:48:21     MODULE FAILURE
09:48:21     See stdout/stderr for the exact error
09:48:21   rc: 1
09:48:22 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/realms/by-group/all/domain/private'
09:48:22 failed: [my_vm -> localhost] (item=pki/realms/by-group/all/domain/private) => changed=false 
09:48:22   ansible_loop_var: item
09:48:22   item: pki/realms/by-group/all/domain/private
09:48:22   module_stderr: |-
09:48:22     Traceback (most recent call last):
09:48:22       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.918487-79186560196033/AnsiballZ_file.py", line 102, in <module>
09:48:22         _ansiballz_main()
09:48:22       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.918487-79186560196033/AnsiballZ_file.py", line 94, in _ansiballz_main
09:48:22         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
09:48:22       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402901.918487-79186560196033/AnsiballZ_file.py", line 40, in invoke_module
09:48:22         runpy.run_module(mod_name='ansible.modules.files.file', init_globals=None, run_name='__main__', alter_sys=True)
09:48:22       File "/usr/lib/python3.7/runpy.py", line 205, in run_module
09:48:22         return _run_module_code(code, init_globals, run_name, mod_spec)
09:48:22       File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
09:48:22         mod_name, mod_spec, pkg_name, script_name)
09:48:22       File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
09:48:22         exec(code, run_globals)
09:48:22       File "/tmp/ansible_file_payload_gvlask_r/ansible_file_payload.zip/ansible/modules/files/file.py", line 940, in <module>
09:48:22       File "/tmp/ansible_file_payload_gvlask_r/ansible_file_payload.zip/ansible/modules/files/file.py", line 926, in main
09:48:22       File "/tmp/ansible_file_payload_gvlask_r/ansible_file_payload.zip/ansible/modules/files/file.py", line 662, in ensure_directory
09:48:22       File "/tmp/ansible_file_payload_gvlask_r/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1342, in set_fs_attributes_if_different
09:48:22       File "/tmp/ansible_file_payload_gvlask_r/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1109, in set_mode_if_different
09:48:22     PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/realms/by-group/all/domain/private'
09:48:22   module_stdout: ''
09:48:22   msg: |-
09:48:22     MODULE FAILURE
09:48:22     See stdout/stderr for the exact error
09:48:22   rc: 1
09:48:22 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/realms/by-group/debops_service_pki/domain/external'
09:48:22 failed: [my_vm -> localhost] (item=pki/realms/by-group/debops_service_pki/domain/external) => changed=false 
09:48:22   ansible_loop_var: item
09:48:22   item: pki/realms/by-group/debops_service_pki/domain/external
09:48:22   module_stderr: |-
09:48:22     Traceback (most recent call last):
09:48:22       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402902.1301997-105488308422598/AnsiballZ_file.py", line 102, in <module>
09:48:22         _ansiballz_main()
09:48:22       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402902.1301997-105488308422598/AnsiballZ_file.py", line 94, in _ansiballz_main
09:48:22         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
09:48:22       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402902.1301997-105488308422598/AnsiballZ_file.py", line 40, in invoke_module
09:48:22         runpy.run_module(mod_name='ansible.modules.files.file', init_globals=None, run_name='__main__', alter_sys=True)
09:48:22       File "/usr/lib/python3.7/runpy.py", line 205, in run_module
09:48:22         return _run_module_code(code, init_globals, run_name, mod_spec)
09:48:22       File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
09:48:22         mod_name, mod_spec, pkg_name, script_name)
09:48:22       File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
09:48:22         exec(code, run_globals)
09:48:22       File "/tmp/ansible_file_payload_8kjdmkz9/ansible_file_payload.zip/ansible/modules/files/file.py", line 940, in <module>
09:48:22       File "/tmp/ansible_file_payload_8kjdmkz9/ansible_file_payload.zip/ansible/modules/files/file.py", line 926, in main
09:48:22       File "/tmp/ansible_file_payload_8kjdmkz9/ansible_file_payload.zip/ansible/modules/files/file.py", line 662, in ensure_directory
09:48:22       File "/tmp/ansible_file_payload_8kjdmkz9/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1342, in set_fs_attributes_if_different
09:48:22       File "/tmp/ansible_file_payload_8kjdmkz9/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1109, in set_mode_if_different
09:48:22     PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/realms/by-group/debops_service_pki/domain/external'
09:48:22   module_stdout: ''
09:48:22   msg: |-
09:48:22     MODULE FAILURE
09:48:22     See stdout/stderr for the exact error
09:48:22   rc: 1
09:48:22 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/realms/by-group/debops_service_pki/domain/private'
09:48:22 failed: [my_vm -> localhost] (item=pki/realms/by-group/debops_service_pki/domain/private) => changed=false 
09:48:22   ansible_loop_var: item
09:48:22   item: pki/realms/by-group/debops_service_pki/domain/private
09:48:22   module_stderr: |-
09:48:22     Traceback (most recent call last):
09:48:22       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402902.3346658-35976344494649/AnsiballZ_file.py", line 102, in <module>
09:48:22         _ansiballz_main()
09:48:22       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402902.3346658-35976344494649/AnsiballZ_file.py", line 94, in _ansiballz_main
09:48:22         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
09:48:22       File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1616402902.3346658-35976344494649/AnsiballZ_file.py", line 40, in invoke_module
09:48:22         runpy.run_module(mod_name='ansible.modules.files.file', init_globals=None, run_name='__main__', alter_sys=True)
09:48:22       File "/usr/lib/python3.7/runpy.py", line 205, in run_module
09:48:22         return _run_module_code(code, init_globals, run_name, mod_spec)
09:48:22       File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
09:48:22         mod_name, mod_spec, pkg_name, script_name)
09:48:22       File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
09:48:22         exec(code, run_globals)
09:48:22       File "/tmp/ansible_file_payload_oiffdzpe/ansible_file_payload.zip/ansible/modules/files/file.py", line 940, in <module>
09:48:22       File "/tmp/ansible_file_payload_oiffdzpe/ansible_file_payload.zip/ansible/modules/files/file.py", line 926, in main
09:48:22       File "/tmp/ansible_file_payload_oiffdzpe/ansible_file_payload.zip/ansible/modules/files/file.py", line 662, in ensure_directory
09:48:22       File "/tmp/ansible_file_payload_oiffdzpe/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1342, in set_fs_attributes_if_different
09:48:22       File "/tmp/ansible_file_payload_oiffdzpe/ansible_file_payload.zip/ansible/module_utils/basic.py", line 1109, in set_mode_if_different
09:48:22     PermissionError: [Errno 1] Operation not permitted: b'/opt/mypath/ansible/secret/pki/realms/by-group/debops_service_pki/domain/private'
09:48:22   module_stdout: ''
09:48:22   msg: |-
09:48:22     MODULE FAILURE
09:48:22     See stdout/stderr for the exact error
09:48:22   rc: 1

09:48:22 ok: [my_vm -> localhost] => (item=pki/realms/by-host/my_vm/domain/external)
09:48:22 ok: [my_vm -> localhost] => (item=pki/realms/by-host/my_vm/domain/internal)
09:48:23 ok: [my_vm -> localhost] => (item=pki/realms/by-host/my_vm/domain/private)

**Comment by drybjed** [comment]
It seems that you are using DebOps via Jenkins, and the project directory is `/opt/mypath`, correct? Check if the `jenkins` UNIX account has write access to the `/opt/mypath` directory on the Ansible Controller. It could be helpful if you show the output of command:
```
namei -om /opt/mypath/ansible/secret/pki'
```
This might indicate where the permission issue might be.

**Comment by krystophe** [comment]
Hello,

I 've already made chmod -R 777 on /opt/

**Comment by drybjed** [comment]
Well, did that help? Does the `PermissionError` exception still shows up?

**Comment by krystophe** [comment]
No that the same as the user jenkins.
But i solved my problem in my jenkins service to change it with root.
Now debops works with jenkins
