### ISSUE TITLE
Debops rsyslod service 

### ISSUE THREAD

**Issue by krystophe** [debops/debops#1665]
Hi,

When i run debops -l myserver i have this error

12:30:57 RUNNING HANDLER [global_handlers : Check and restart rsyslogd] *****************
12:30:57 fatal: [myserver]: FAILED! => changed=true 
12:30:57   cmd:
12:30:57   - rsyslogd
12:30:57   - -N
12:30:57   - '1'
12:30:57   delta: '0:00:00.050438'
12:30:57   end: '2021-03-22 12:30:57.728306'
12:30:57   msg: non-zero return code
12:30:57   rc: 1
12:30:57   start: '2021-03-22 12:30:57.677868'
12:30:57   stderr: |-
12:30:57     rsyslogd: version 8.1901.0, config validation run (level 1), master config /etc/rsyslog.conf
12:30:57     rsyslogd: error during parsing file /etc/rsyslog.d/00forward-logs.conf, on or before line 18: parameter 'target' contains whitespace, which is not permitted [v8.1901.0 try https://www.rsyslog.com/e/2207 ]
12:30:57     rsyslogd: error during parsing file /etc/rsyslog.d/00forward-logs.conf, on or before line 18: errors occured in file '/etc/rsyslog.d/00forward-logs.conf' around line 18 [v8.1901.0 try https://www.rsyslog.com/e/2207 ]
12:30:57   stderr_lines: <omitted>
12:30:57   stdout: ''
12:30:57   stdout_lines: <omitted>

the 00forward-logs.conf
# This file is managed remotely, all changes will be lost

#
# Forward logs to specified hosts
#
*.* action(
      type="omfwd"
      target="*.* @@myip:1514;RSYSLOG_SyslogProtocol23Format"
      port="6514"
      protocol="tcp"
      streamDriver="gtls"
      streamDriverMode="1"
      streamDriverAuthMode="x509/name"
      action.resumeRetryCount="100"
      queue.type="linkedList"
      queue.size="10000"
      streamDriverPermittedPeers="*.xyn.dev"
    )

I don't know why i have this.
In another Debian server I have these files

00-global.conf  10-local-modules.conf     20-templates.conf  50-default-rulesets.conf  log-nginx-graylog.conf  zz-stop.remote
05-common-defaults.conf  20-remote-forward.system  40-cron.system     50-default.system         mysql.conf

And in 20-remote-forward.system

# This file is managed remotely, all changes will be lost

#
# Forward logs to specified hosts
#
*.* @@ip_server:1514;RSYSLOG_SyslogProtocol23Format

**Comment by drybjed** [comment]
Did you define configuration variables for the `rsyslog` role in Ansible inventory? Can you show the defined variables?

**Comment by krystophe** [comment]
I have a rsyslog.yml and this is it's content

```
rsyslog__group_forward:
  - '*.* @@ip_server:1514;RSYSLOG_SyslogProtocol23Format'

rsyslog__conf_system_rules:

  - filename: '50-default.system'
    sections:
      - comment: 'Standard log files, split by facility'
        options: |-
          auth,authpriv.*                /var/log/auth.log
          *.*;cron,auth,authpriv.none    -/var/log/syslog
          cron.*                         -/var/log/cron.log
          daemon.*                       -/var/log/daemon.log
          kern.*                         -/var/log/kern.log
          lpr.*                          -/var/log/lpr.log
          mail.*                         -/var/log/mail.log
          user.*                         -/var/log/user.log

      - comment: 'Copy of the local log files to complete remote logs'
        options: |-
          auth,authpriv.*                ?RemoteHostAuthLog
          auth,authpriv.*                ?RemoteServiceAuthLog
          *.*;cron,auth,authpriv.none    -?RemoteHostSyslog
          cron.*                         -?RemoteHostCronLog
          cron.*                         -?RemoteServiceCronLog
          mail.*                         -?RemoteServiceMailLog

      - comment: |-
          Logging for the mail system. Split it up so that
          it is easy to write scripts to parse these files
        options: |-
          mail.info                      -/var/log/mail.info
          mail.warn                      -/var/log/mail.warn
          mail.err                       /var/log/mail.err

      - comment: 'Logging for INN news system'
        options: |-
          news.crit                      /var/log/news/news.crit
          news.err                       /var/log/news/news.err
          news.notice                    -/var/log/news/news.notice

      - comment: 'Some "catch-all" log files'
        options: |-
          *.=debug;\
                  auth,authpriv.none;\
                  mail,news.none          -/var/log/debug
          *.=info;*.=notice;*.=warn;\
                  auth,authpriv.none;\
                  cron,daemon.none;\
                  mail,news.none          -/var/log/messages
```

**Comment by krystophe** [comment]
In jenkins log I can see this, I don't understand why 

12:51:59 TASK [rsyslog : Remove custom config files when requested] *********************
12:51:59 ok: [myvm] => (item={'name': 'remote.input', 'state': 'absent'})
12:51:59 ok: [myvm] => (item={'name': 'remote.template', 'state': 'absent'})
12:51:59 ok: [myvm] => (item={'name': 'local-as-remote.ruleset', 'state': 'absent'})
12:51:59 ok: [myvm] => (item={'name': 'cron-session.remote', 'state': 'absent'})
12:52:00 ok: [myvm] => (item={'name': '50-dynamic-logs.remote', 'state': 'absent'})
12:52:00 ok: [myvm] => (item={'name': 'ruleset.remote', 'state': 'absent'})
12:52:00 ok: [myvm] => (item={'name': 'zz-stop.remote', 'state': 'absent'})
12:52:00 ok: [myvm] => (item={'name': '00-global.conf', 'state': 'absent'})
12:52:01 ok: [myvm] => (item={'name': '05-common-defaults.conf', 'state': 'absent'})
12:52:01 ok: [myvm] => (item={'name': '10-local-modules.conf', 'state': 'absent'})
12:52:01 ok: [myvm] => (item={'name': '20-templates.conf', 'state': 'absent'})
12:52:01 ok: [myvm] => (item={'name': '40-cron.system', 'state': 'absent'})
12:52:02 ok: [myvm] => (item={'name': '50-default-rulesets.conf', 'state': 'absent'})
12:52:02 ok: [myvm] => (item={'name': '50-default.system', 'state': 'absent'})

**Comment by drybjed** [comment]
The `rsyslog` role was updated some time ago; the multiple `absent` file tasks are meant to help with upgrades to the newer release (old config files created by the role are removed if found). Your Ansible inventory configuration might need to be updated, check the role documentation.

As for the issues with forwarding, I'm not sure yet. I'll check this sometime later and report back.

**Comment by krystophe** [comment]
It's working now
