### ISSUE TITLE
Debops /var/log/mysql/error.log

### ISSUE THREAD

**Issue by krystophe** [debops/debops#1666]
Hi,

I have a lot of error in my file /var/log/mysql/error.log and in 1 hour I'am out of space in my /var/log.
The file reached the maximum space of 3.5Go.
The mysql service is working.

I don't know how to solve this, here is the error 

thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Ma
Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:44 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Mar 22 13:37:34 thenameofvm mysql-error-default: Ma
Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm mysql-error-default: Mar 22 13:37:54 thenameofvm

Here is my mariadb.yml

mariadb_server__bind_address: '0.0.0.0'
mariadb_server__port: '3306'
mariadb_server__allow: [ 'mylan/24' ]
mariadb_server__options:

  - section: 'mysqld'
    comment: 'Global MariaDB server options'
    options:

      - name: 'skip_name_resolve'

      - name: 'key_buffer'
        value: '16M'

      - name: 'query_cache_type'
        value: '0'
        state: 'present'

mariadb_server__upstream_mirror: 'http://nyc2.mirrors.digitalocean.com/mariadb/repo/{{ mariadb_server__upstream_version }}/{{ ansible_distribution | lower }}'
mariadb_server__apt_key_map:

  'mariadb_upstream':
    - id: '199369E5404BD5FC7D2FE43BCBCB082A1BB943DB'
    - id: '177F4010FE56CA3336300305F1656F24C74CD1D8'
    - repo: 'deb {{ mariadb_server__upstream_mirror }} {{ ansible_distribution_release }} main'

mariadb_server__mysqld_performance_options:
  'innodb_buffer_pool_instances': '4'
  'innodb_buffer_pool_size': '5000M'
  'query_cache_type': '0'

**Comment by drybjed** [comment]
Well, the error log doesn't say much... Are you sure that you copied entire log lines and not just the part that was visible in the terminal window? Did you create and import any databases in the meantime?

**Comment by krystophe** [comment]
Hello,

Yes this the entire part from the /var/log/mysql/error.log.
This is a strange issue because this is a fresh install of a server, I haven't got any databases on this server

**Comment by krystophe** [comment]
it's work now
