### ISSUE TITLE
[hashicorp] GPG key need to be updated after Codecov Security Event

### ISSUE THREAD

**Issue by nqb** [debops/debops#1688]
Hello,

According to [Codecov Security Event and HashiCorp GPG Key Exposure post](https://groups.google.com/g/hashicorp-announce/c/J3WCN3p7O3Q/m/3MUMOfbqAAAJ) and [a post on HashiCorp forum](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512), GPG key used to sign hashes of HashiCorp products downloads has been rotated.

We need to update role `hashicorp` with new key, documentation also needs to be updated.

**Comment by drybjed** [comment]
Thanks, I'll look into it right away.
