### ISSUE TITLE
debops.postfix should install libsasl2-modules when using smtp_sasl_auth_enable

### ISSUE THREAD

**Issue by stefangweichinger** [debops/debops#169]
postfix: ['client']

should also install libsasl2-modules in a way.

Currently I can't find a way to configure debops.postfix so that the sasl-modules get installed, a grep in the debops-roles shows that only debops.saslauthd installs these modules.

IMO a postfix server with an upstream relayhost shouldn't need a local saslauthd.

Right now I define it within:

postfix__maincf:                                                                                                                                                               
   - smtp_sasl_auth_enable: 'yes'

which might be wrong or improveable?

**Comment by drybjed** [comment]
I think that the good place to put the SMTP client configuration would be in the `debops.postconf` role which currently handles SMTP server auth; this could be enabled via a capability defined in `postconf__capabilities`. I'll look at it when I have a bit more time on my hands. Thanks for reporting the issue.

**Comment by stefangweichinger** [comment]
postconf currently does not provide that as far as I see/grep ;-)
looking forward, thanks

**Comment by stefangweichinger** [comment]
postfix__packages: [ 'libsasl2-modules' ]

helped as workaround for now
