### ISSUE TITLE
resolvconf role 

### ISSUE THREAD

**Issue by krystophe** [debops/debops#1704]
Hi,

I think there is a problem with resolvconf role.
After execution of the role I checked on the host /etc/resolv.conf and I can see 

#Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver mydnsserver1
search mydomain

my vm is a clone of a base template vm which has the same resolvconf configuration but I want to update the configuration with debops.

here is my resolvconf.yml:

resolvconf__enabled: True
resolvconf__deploy_state: 'present'
resolvconf__static_enabled: True
resolvconf__base_packages: [ 'resolvconf' ]
resolvconf__static_content: |
  search mydomain
  nameserver mydnsserver1
  nameserver mydnsserver2
  nameserver mydnsserver3

Have you any idea the resolve this problem ?
Thanks

**Comment by drybjed** [comment]
As per the documentation, check if the `/run/resolvconf/interface/lo.static` exists with your configuration. You can also execute the `/usr/local/lib/resolvconf-static` script to "apply" the static configuration. This script should be executed automatically by the `resolvconf.service` unit, so check if the static configuration is present after a reboot.

**Comment by krystophe** [comment]
Hello,

It's seems that resolvconf.service wasn't start on certains vms, I don't know why.

Thanks
