### ISSUE TITLE
Failed TASK [php : Set PHP base paths]

### ISSUE THREAD

**Issue by krystophe** [debops/debops#1744]
Hi,

I have an problem when I run debops php role.
Here is the output 

18:37:54 fatal: [myvm]: FAILED! => 
18:37:54   msg: 'Version comparison: ''LooseVersion'' object has no attribute ''version'''

How can I fix this ?

**Comment by drybjed** [comment]
That doesn't tell much... Which task failed? Also, what Ansible and DebOps version are you using?

**Comment by krystophe** [comment]
Hi
I'm running the latest version of debops, installed with python3.

this failed is on the php role   php.yml    and  TASK [php : Set PHP base paths]

**Comment by krystophe** [comment]
I tried this parameter in the php.yml

php__reset: True

but same error

**Comment by drybjed** [comment]
Do you use your own playbook with the `php` role, or are you using the playbook included with the DebOps project? If you use your own, you need to include the [`main_env`](https://github.com/debops/debops/blob/master/ansible/playbooks/service/php.yml#L27-L31) "entry point" via the `pre_tasks` keyword to prepare the role environment which is used later by other roles.

**Comment by krystophe** [comment]
I only use playbook included with debops project

**Comment by drybjed** [comment]
Ah, that task is in the `main_env.yml` task file... Hmmm. What OS distribution and release are you using?

**Comment by krystophe** [comment]
Here is my os version

Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by drybjed** [comment]
Can you show the command you are using to run the playbook, as well as the Ansible output? Which tasks were skipped during the run?

**Comment by krystophe** [comment]
Yes my command 
debops service/php -l myvm --ssh-common-args -o StrictHostKeyChecking=no -u customuser

**Comment by krystophe** [comment]
I haven't any task that were skipped during the run only failed on this TASK [php : Set PHP base paths]

and this output:
msg: 'Version comparison: ''LooseVersion'' object has no attribute ''version'''

**Comment by krystophe** [comment]
Here is the debops php service run:


18:52:40 TASK [keyring : Get list of local GPG key fingerprints on Ansible Controller] ***
18:52:40 ok: [myvm]

18:52:41 
18:52:41 TASK [keyring : Install required packages] *************************************
18:52:41 ok: [myvm]

18:52:42 
18:52:42 TASK [keyring : Make sure that Ansible local fact directory exists] ************
18:52:42 ok: [myvm]

18:52:43 
18:52:43 TASK [keyring : Save keyring local facts] **************************************
18:52:43 ok: [myvm]

18:52:44 
18:52:44 TASK [keyring : Import specified GPG keys to APT keyring] **********************
18:52:44 ok: [myvm] => (item={'id': '1505 8500 A023 5D97 F5D1  0063 B188 E2B6 95BD 4743', 'repo': 'deb https://packages.sury.org/php/ buster main', 'state': 'absent'})

18:52:45 ok: [myvm] => (item={'id': 'DF3D 585D B8F0 EB65 8690  A554 AC0E 4758 4A7A 714D', 'state': 'absent'})
18:52:45 
18:52:45 TASK [keyring : Configure specified upstream APT repositories] *****************
18:52:45 ok: [myvm] => (item={'id': '1505 8500 A023 5D97 F5D1  0063 B188 E2B6 95BD 4743', 'repo': 'deb https://packages.sury.org/php/ buster main', 'state': 'absent'})

18:52:46 
18:52:46 TASK [keyring : Gather information about existing UNIX accounts] ***************
18:52:46 ok: [myvm]
18:52:46 
18:52:46 TASK [php : Reset PHP Ansible local facts] *************************************
18:52:46 ok: [myvm]

18:52:47 
18:52:47 TASK [php : Detect PHP version from available packages] ************************
18:52:47 ok: [myvm]
18:52:47 
18:52:47 TASK [php : Detect PHP long version from available packages] *******************
18:52:47 ok: [myvm]
18:52:47 
18:52:47 TASK [php : Set PHP version] ***************************************************
18:52:47 ok: [myvm]
18:52:47 
18:52:47 TASK [php : Set PHP base paths] ************************************************
18:52:47 fatal: [myvm]: FAILED! => 
18:52:47   msg: 'Version comparison: ''LooseVersion'' object has no attribute ''version'''
18:52:47 
18:52:47 PLAY RECAP *********************************************************************
18:52:47 myvm    : ok=12   changed=0    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0   
18:52:47 
18:52:47 Gathering Facts --------------------------------------------------------- 2.56s
18:52:47 Import specified GPG keys to APT keyring -------------------------------- 2.16s
18:52:47 Install required packages ----------------------------------------------- 1.08s
18:52:47 Configure specified upstream APT repositories --------------------------- 0.71s
18:52:47 Save keyring local facts ------------------------------------------------ 0.66s
18:52:47 Make sure that Ansible local fact directory exists ---------------------- 0.47s
18:52:47 Detect PHP version from available packages ------------------------------ 0.44s
18:52:47 Gather information about existing UNIX accounts ------------------------- 0.40s
18:52:47 Detect PHP long version from available packages ------------------------- 0.34s
18:52:47 Reset PHP Ansible local facts ------------------------------------------- 0.30s
18:52:47 Running Ansible playbooks:
18:52:47 /usr/local/lib/python3.7/dist-packages/debops/ansible/playbooks/service/php.yml
18:52:47 Build step 'Execute shell' marked build as failure

**Comment by drybjed** [comment]
I suspect that the Ansible version might be an issue here, which version do you use? You hadn't mentioned it. Are you using Ansible from Debian Stable (Buster), not backports? In that case it might be too old for DebOps, you might need to install Ansible from `buster-backports`, or from the PyPI repository.

**Comment by krystophe** [comment]
here is the output of ansible --version

ansible 2.9.4
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.7/site-packages/ansible
  executable location = /root/.local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by drybjed** [comment]
Looks like it was installed from PyPI. You could try to install the latest version - you need to uninstall the 2.9.4 version first for `pip3` to correctly install the new one.

**Comment by krystophe** [comment]
does I need to run pip3 uninstall ansible ?

**Comment by drybjed** [comment]
Yes.

**Comment by krystophe** [comment]
Now i'm running python3.9
Ansible 4.1.0

but debops --version 

Traceback (most recent call last):
  File "/usr/local/bin/debops", line 277, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/debops", line 252, in main
    gen_ansible_cfg(ansible_config_file, config, project_root, playbooks_path,
  File "/usr/local/bin/debops", line 150, in gen_ansible_cfg
    if (ver(ansible_version) >= ver("1.7") and
  File "/usr/local/lib/python3.9/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/usr/local/lib/python3.9/distutils/version.py", line 341, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by krystophe** [comment]
here is the output python -m pip list


Package        Version
-------------- -------
ansible        4.1.0
ansible-core   2.11.2
cffi           1.14.5
cryptography   3.4.7
debops         2.3.0
distro         1.5.0
dnspython      2.1.0
future         0.18.2
Jinja2         3.0.1
MarkupSafe     2.0.1
netaddr        0.8.0
packaging      20.9
passlib        1.7.4
pip            21.1.2
pyasn1         0.4.8
pyasn1-modules 0.2.8
pycparser      2.20
pyparsing      2.4.7
python-ldap    3.3.1
PyYAML         5.4.1
resolvelib     0.5.4
setuptools     49.2.1

**Comment by drybjed** [comment]
The `debops --version` does not work in this version of DebOps. Try running a playbook as usual, for example `debops service/core -l host`

**Comment by krystophe** [comment]
I run  debops service/php -l myvm --ssh-common-args -o StrictHostKeyChecking=no -u myuser

and here is the output:

20:29:10 Traceback (most recent call last):
20:29:10   File "/usr/local/bin/debops", line 277, in <module>
20:29:10     sys.exit(main(sys.argv[1:]))
20:29:10   File "/usr/local/bin/debops", line 252, in main
20:29:10     gen_ansible_cfg(ansible_config_file, config, project_root, playbooks_path,
20:29:10   File "/usr/local/bin/debops", line 150, in gen_ansible_cfg
20:29:10     if (ver(ansible_version) >= ver("1.7") and
20:29:10   File "/usr/local/lib/python3.9/distutils/version.py", line 70, in __ge__
20:29:10     c = self._cmp(other)
20:29:10   File "/usr/local/lib/python3.9/distutils/version.py", line 341, in _cmp
20:29:10     if self.version < other.version:
20:29:10 TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by drybjed** [comment]
The code that checks the Ansible version in the `debops` script was removed some time ago, it shouldn't be present in the v2.3.0 version. Perhaps you could uninstall the `debops` package as well and re-install it with `pip3 install --upgrade debops`.

**Comment by krystophe** [comment]
Ok now I can run 

debops --version
Running Ansible playbooks:
/usr/local/lib/python3.9/site-packages/debops/ansible/playbooks/site.yml
ansible-playbook [core 2.11.2]
  config file = /opt/xynpar2/ansible.cfg
  configured module search path = ['/opt/xynpar2/ansible/playbooks/library', '/opt/xynpar2/ansible/plugins/library', '/opt/xynpar2/ansible/library', '/opt/xynpar2/debops/ansible/playbooks/playbooks/library', '/opt/xynpar2/debops/ansible/playbooks/library', '/opt/xynpar2/debops/ansible/plugins/library', '/opt/xynpar2/debops/ansible/library', '/usr/local/lib/python3.9/site-packages/debops/ansible/plugins/library', '/usr/local/lib/python3.9/site-packages/debops/ansible/playbooks/library', '/nonexistent/library', '/usr/share/ansible/library']
  ansible python module location = /root/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.1 (default, Jun 22 2021, 20:04:35) [GCC 8.3.0]
  jinja version = 3.0.1
  libyaml = True

**Comment by krystophe** [comment]
I run php service and now here is the output :

20:49:19 TASK [php : Set PHP base paths] ************************************************
20:49:19 fatal: [pm-cef-re7-testdebops-2]: FAILED! => 
20:49:19   msg: Input version value cannot be empty

**Comment by drybjed** [comment]
It looks like the `php__version` variable was not set correctly. Can you show the contents of the `/etc/ansible/facts.d/php.fact` file on the remote host?

You could also add a task before the "Set PHP base paths" task in the role:
```yaml
- debug: var=php__version
```
To check if the variable is defined at runtime.

**Comment by krystophe** [comment]
There is absent on the remote host

**Comment by drybjed** [comment]
OK, the role didn't have a chance to set the fact file yet. Check the `php__register_version` and `php__register_long_version` variables using the `debug` module, as above.

**Comment by krystophe** [comment]
How can I do that?

**Comment by krystophe** [comment]
I run with -vvvv and here I can see this but in my hosts file my vm is in php7.2 and not in php7.3 group 

TASK [php : Set PHP version] *********************************************************************************************************************************************************************
task path: /usr/local/lib/python3.9/site-packages/debops/ansible/roles/php/tasks/main_env.yml:53
ok: [myvm] => changed=false
  ansible_facts:
    php__long_version: '7.3'
    php__version: ''

TASK [php : Set PHP base paths] ******************************************************************************************************************************************************************
task path: /usr/local/lib/python3.9/site-packages/debops/ansible/roles/php/tasks/main_env.yml:62
fatal: [myvm]: FAILED! =>
  msg: Input version value cannot be empty

**Comment by drybjed** [comment]
First of all, do you know where the DebOps roles are? If not, when you run a playbook with `debops` command, it emits the full path to the playbook you specified. If it's in `~/.local/lib/*`, you are using the DebOps roles and playbooks packaged with the Python package, if it's somewhere else, you installed DebOps monorepo somewhere. In either case, open the directory of that playbook and move two subdirectories up, you should find the `roles/php/tasks/main_env.yml` file somewhere. In there, find the "Set PHP base paths" task (it's the last one in the file), and before that task, add:
```yaml
- debug: var=php__register_version
- debug: var=php__register_long_version
```
These tasks should show what the two version detection tasks did. Show the output after running the role with the changes.

**Comment by krystophe** [comment]
Yes i think I found:

task path: /usr/local/lib/python3.9/site-packages/debops/ansible/roles/php/tasks/main_env.yml:53

**Comment by drybjed** [comment]
OK, so you installed DebOps from PyPI with `sudo`. Let me know what the variable contents are.

**Comment by krystophe** [comment]
Here is the output:

21:27:49 TASK [php : debug] *************************************************************
21:27:49 task path: /usr/local/lib/python3.9/site-packages/debops/ansible/roles/php/tasks/main_env.yml:63
21:27:49 ok: [myvm] => 
21:27:49   php__register_version:
21:27:49     changed: false
21:27:49     cmd: set -o nounset -o pipefail -o errexit && apt-cache madison php7.2 | awk '{print $3}' | sed -e 's/^.*://' -e 's/\+.*$//' -e 's/\d+\.\d+//' | awk -F'.' '{print $1"."$2}' | head -n 1
21:27:49     delta: '0:00:00.043898'
21:27:49     end: '2021-06-22 21:27:48.889925'
21:27:49     failed: false
21:27:49     rc: 0
21:27:49     start: '2021-06-22 21:27:48.846027'
21:27:49     stderr: ''
21:27:49     stderr_lines: []
21:27:49     stdout: ''
21:27:49     stdout_lines: []
21:27:49 
21:27:49 TASK [php : debug] *************************************************************
21:27:49 task path: /usr/local/lib/python3.9/site-packages/debops/ansible/roles/php/tasks/main_env.yml:64
21:27:49 ok: [myvm] => 
21:27:49   php__register_long_version:
21:27:49     changed: false
21:27:49     cmd: set -o nounset -o pipefail -o errexit && apt-cache madison php | awk '{print $3}' | sed -e 's/^.*://' -e 's/\+.*$//' -e 's/\-.*$//' | head -n 1
21:27:49     delta: '0:00:00.052651'
21:27:49     end: '2021-06-22 21:27:49.259705'
21:27:49     failed: false
21:27:49     rc: 0
21:27:49     start: '2021-06-22 21:27:49.207054'
21:27:49     stderr: ''
21:27:49     stderr_lines: []
21:27:49     stdout: '7.3'
21:27:49     stdout_lines:
21:27:49     - '7.3'

**Comment by krystophe** [comment]
I run like this with root python -m pip install --user --upgrade debops

**Comment by drybjed** [comment]
There's no PHP 7.2 in Debian Buster. The tasks that try to detect available versions try to look specifically for PHP 7.2 and don't find any available packages - that's why the `php__version` variable is empty and cannot be compared with a specific version.

What did you set in your inventory?

If you really want PHP 7.2, then you should also set the `php__sury: True` variable, this enables the additional repository which contains multiple PHP versions.

**Comment by krystophe** [comment]
ok thanks 

First the job was run with php5.6 and I update de yaml to php7.2 I was thought that was on debian 10 
I try with php7.3

**Comment by krystophe** [comment]
I try all the process of deployment but 
step debops bootstrap I have this error 

22:06:53 TASK [sudo : Ensure that '/etc/sudoers' includes '/etc/sudoers.d'] *************
22:06:53 fatal: [myvm]: FAILED! => 
22:06:53   msg: 'Version comparison failed: ''<'' not supported between instances of ''str'' and ''int'''

**Comment by drybjed** [comment]
Remove the `/etc/ansible/facts.d/sudo.fact` script from the host and re-run the playbook. Let me know if that fixed the issue.

**Comment by krystophe** [comment]
Thanks for help.

I revert to a snapshot of yesterday.
And just change the version of php 7.3 when I create the vm and it's work.

You right after search in apt repo of debian for php 5.6 7.1 and 7.2 nothing found

**Comment by drybjed** [comment]
Great! BTW, you don't need to explicitly specify the version of PHP that you want in the inventory. The `php` role is designed in such a way that it can find available versions of PHP on a given host and use the best suited one automatically.

**Comment by krystophe** [comment]
Ok thanks because sometimes developpers need php7.1  7.2 or 7.3 and 7.4 
No project for 8 for now.

**Comment by krystophe** [comment]
My ansible version is 2.9.4 can I upgrade via pip3 to the latest ?

Debops version is debops  2.3.0

**Comment by drybjed** [comment]
Yes, but not directly. You need to uninstall your current Ansible package to be able to install the latest one due to changes in `ansible` Python package dependencies.

**Comment by krystophe** [comment]
Hi,

I'm having the same issue after changing an host from php7.3 to 5.6.

I enable php reset in php.yml and change the host in group 5.6.

Here is the output:


18:12:14 TASK [php : Set PHP base paths] ************************************************
18:12:14 fatal: [myvm]: FAILED! => 
18:12:14   msg: 'Version comparison: ''LooseVersion'' object has no attribute ''version'''


Thanks for help

**Comment by krystophe** [comment]
Ok I solve the problem with apt.yml and add gpg key of repo sury
