### ISSUE TITLE
SKS keyserver pool is deprecated

### ISSUE THREAD

**Issue by mkulawik** [debops/debops#1745]
Hello, 
According to the documentation the debops.keyring role uses the SKS Keyserver pool to retrieve GPG keys. But according to https://sks-keyservers.net/: 

"This service is deprecated. This means it is no longer maintained, and new HKPS certificates will not be issued. Service reliability should not be expected.

Update 2021-06-21: Due to even more GDPR takedown requests, the DNS records for the pool will no longer be provided at all."

Are there plans to update debops.keyring role with a new server?

Great project btw, 
Regards,
Mark

**Comment by drybjed** [comment]
That's unfortunate news! Some of the cases can be handled via the `extrepo` role since the `extrepo-data` repository provides the GPG keys by itself, but of course we will have to find an alternative for the SKS keyserver pool. Do you know about any candidates?

**Comment by jankowa** [comment]
just checked out for sury:

```
TASK [extrepo : Update APT cache if required] ********************************************************************************************************************************************************************
fatal: [example.org]: FAILED! => changed=false 
  attempts: 3
  msg: 'Failed to update apt cache: W:Updating from such a repository can''t be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: https://packages.sury.org/php buster InRelease: The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>, E:The repository ''https://packages.sury.org/php buster InRelease'' is not signed.'
```

don'n know if this has has the same root cause but I don't think so. keys for extrepo are stored locally. It looks that this is just expired.

**Comment by mkulawik** [comment]
I'm sorry I don't have a candidate. We just setup a local keystore on our ansible controller (link below) and it seems to work well. Good luck!

https://docs.debops.org/en/master/ansible/roles/keyring/getting-started.html#local-key-store-on-the-ansible-controller
