### ISSUE TITLE
problem apt.yml

### ISSUE THREAD

**Issue by krystophe** [debops/debops#1752]
Hi,

I'm having a problem with apt.yml role.
I want to install pagerduty agent  

Here is th content of my apt.yml:
apt__enabled: True
apt__keys:
  - url: 'https://packages.pagerduty.com/GPG-KEY-pagerduty'

apt__repositories:
  - repo: 'deb https://packages.pagerduty.com/pdagent deb/'

Here is the output when the role failed:
12:37:39 TASK [apt : Configure APT distribution sources] ********************************
12:37:39 ok: [myvm]

12:37:40 FAILED - RETRYING: Configure custom APT keys (3 retries left).

12:37:46 FAILED - RETRYING: Configure custom APT keys (2 retries left).

12:37:52 FAILED - RETRYING: Configure custom APT keys (1 retries left).

12:37:57 
12:37:57 TASK [apt : Configure custom APT keys] *****************************************
12:37:57 failed: [myvm] (item={'url': 'https://packages.pagerduty.com/GPG-KEY-pagerduty'}) => changed=false 
12:37:57   ansible_loop_var: item
12:37:57   attempts: 3
12:37:57   item:
12:37:57     url: https://packages.pagerduty.com/GPG-KEY-pagerduty
12:37:57   msg: 'Failed to download key at https://packages.pagerduty.com/GPG-KEY-pagerduty: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

Thanks for response

**Comment by tumd** [comment]
As the error message says, it's failing to validate the certificate when fetching the apt-key.
Does `myvm` have internet-connection, without the need of a http-proxy?
Do your get any errors if you perform `curl https://packages.pagerduty.com/GPG-KEY-pagerduty` on the host `myvm` (given that curl is also installed on the vm)?

**Comment by krystophe** [comment]
Hello,

myvm has internet connection of course. I don't use proxy.

I solved my problem thanks
