### ISSUE TITLE
dnsmasq: default ferm firewall rules for dhcpv6 break on debian (at least bullseye)

### ISSUE THREAD

**Issue by SunStrom** [debops/debops#1760]
Hi,

i tried rolling out dnsmasq on an Debian/bullseye testing host and could not get ferm to work correctly.
To reproduce I can simply run:
`debobs -l TESTHOST`
with TESTHOST in groups "debops_service_dnsmasq" and "debops_service_ifupdown" (amongst others).
The command results in an error for task `[ferm : Restart ferm]`:

>     Unable to start service ferm: Job for ferm.service failed because the control process exited with error code.
>    See "systemctl status ferm.service" and "journalctl -xe" for details.

According to the log on TESTHOST this is because:
>  Jul 07 11:10:11 TESTHOST ferm[70577]: Starting Firewall: ferm
>  Jul 07 11:10:11 TESTHOST ferm[70710]: ip6tables v1.8.7 (legacy): invalid port/service `dhcpv6-client' specified
>  Jul 07 11:10:11 TESTHOST ferm[70710]: Try `ip6tables -h' or 'ip6tables --help' for more information.
>  Jul 07 11:10:12 TESTHOST ferm[70580]: Firewall rules rolled back.
>  Jul 07 11:10:12 TESTHOST ferm[70722]:  failed!

Running ferm manually for /etc/ferm/rules.d/140_rule_dhcpv6.conf results in the same error.

The problem seems to be located in 
https://github.com/debops/debops/blob/379eaeca0dab49577b6776428db757262fb86ec6/ansible/roles/dnsmasq/defaults/main.yml#L608

... which specifies TCP and UDP for the default rule. According to `/etc/services`, the Port/Protocol uses UDP only, hence iptables complains.

If I override the default dnsmasq role with an local copy and edit this line to 
`       protocol: [ 'udp' ]`
everything works as expected.

Thanks for your response/efforts.

**Comment by alinalexandru** [comment]
I do have the same problem on Ubuntu 20

**Comment by alinalexandru** [comment]
Reading a little bit from https://datatracker.ietf.org/doc/html/rfc3315#section-13, I don't see clear specifications that TCP is used.
