### ISSUE TITLE
[sudo] bug: 'Version comparison: ''<'' not supported between instances of ''str'' and ''int'''

### ISSUE THREAD

**Issue by julien-lecomte** [debops/debops#1775]
When running the sudo playbook on a fresh install, with no variables defined and host being a debops_all_hosts, the play will stop on
 
```
TASK [Ensure that '/etc/sudoers' includes '/etc/sudoers.d'] ****
fatal: [debops-testing.example.com]: FAILED! => 
  msg: 'Version comparison: ''<'' not supported between instances of ''str'' and ''int'''
```

Sudo version is 
```
julien@debops-testing:~$ sudo --version 
Sudo version 1.8.27
sudo: unable to resolve host debops-testing: Name or service not known
Sudoers policy plugin version 1.8.27
Sudoers file grammar version 46
Sudoers I/O plugin version 1.8.27
```

As you can see from the output, the sudo error "unable ..." (on stderr) is the reason the version compare fails.

The fix is to edit `/etc/hosts` and add a proper `127.0.1.1 hostname` line.

**Comment by julien-lecomte** [comment]
The output for the netbase role contains
```
TASK [netbase : Manage entries in /etc/hosts] *****
ok: [debops-testing.example.com] => (item={'127.0.0.1': ['localhost']})
ok: [debops-testing.example.com] => (item={'127.0.1.1': []})
```

**Comment by julien-lecomte** [comment]
A workaround is  to add `Defaults !fqdn` to a `/etc/sudoers.d/fqdn`

**Comment by trhr** [comment]
i also get this error, as well as #1789 - and I use netbase to write my hosts file.

**Comment by stefangweichinger** [comment]
same here

**Comment by imrejonk** [comment]
I would say this is not a bug in DebOps, but a domain name configuration error. The sudo version output rightfully changes behaviour when the configuration error is present. The sudo role expects a correctly configured DNS setup. Now if netbase fails to correctly configure /etc/hosts (@trhr), then this is definitely an issue (albeit in a different role so please create a new GitHub issue).

I think this issue should remain closed. If anyone thinks that this is in fact a bug in DebOps, feel free to reopen.
