### ISSUE TITLE
slapd writing invalid ferm/rules.d

### ISSUE THREAD

**Issue by trhr** [debops/debops#1789]
i'm not sure which playbook is configuring this, but when slapd writes the 005_rule_accept_ansible_controller.conf, the line it writes is:

`@def $SITEMS = ( @ipfilter( (10.0.X.X hostname.domain.tld) ) );`

this causes ferm.d to fail startup with a host/network not found error.
when i change the line to the following, startup is successful.

`@def $SITEMS = ( @ipfilter( (10.0.X.X) ) );`

fwiw, the fqdn is valid and defined in hosts; just not a supported format for the tables i suppose.

**Comment by trhr** [comment]
fixed with ferm__domains: ['ip']

should probably be noted in the documentation that if you're relying on /etc/hosts to serve dns, it won't be serving ipv6 unless you're some kind of deviant networking autist who defines hosts by their ipv4 AND ipv6 addresses.

**Comment by Alphix** [comment]
At the risk of sounding like a besserwisser, the docs say right [here](https://docs.debops.org/en/master/introduction/getting-started.html) that `An important part of the environment is correctly configured DNS.`

**Comment by imrejonk** [comment]
> should probably be noted in the documentation that if you're relying on /etc/hosts to serve dns, it won't be serving ipv6 unless you're some kind of deviant networking autist who defines hosts by their ipv4 AND ipv6 addresses.

This is a ridiculous and blatantly ignorant comment, not to mention disrespectful to people with autism. The debops.netbase role configures /etc/hosts exactly like this if the DNS lacks the IPv4/IPv6 configured on the primary network interface. As it should be imo.

Please do your homework before opening an issue. This is clearly not a bug.

**Comment by trhr** [comment]
Suit yourself @imrejonk, I spent three weeks in the documentation before dropping the debops platform entirely and going back to regular old ansible. You -say- that things work in a specific way; but really, that's only the case if everything else fits the highly-opinionated nature of the software. I was using the netbase role specifically as described, and it was not sufficient to actually configure the networking correctly. This problem, plus a chunk of other networking-related problems like denying ssh access to the ansible user, reappeared across a SIGNIFICANT number of roles with no rhyme or reason that I could discern, which suggested to me that there's some issue in a very core role, but I couldn't pinpoint exactly where.

Just some feedback from someone who really wanted to like this project as a migration target for a 42U bare metal blade server buildout, and this feedback is as invalid as you choose for it to be.
