### ISSUE TITLE
debops.librenms: template missing

### ISSUE THREAD

**Issue by stefangweichinger** [debops/debops#179]
TASK [debops.nginx : Create default welcome page if enabled]

[WARNING]: Unable to find 'lookup/ferm__fix_dependent_rules.j2' in expected paths.

original message: the template file lookup/ferm__fix_dependent_rules.j2 could not be found for the lookup

---

$ find ~/.local/share/debops/debops/ | grep fix_dep
~/.local/share/debops/debops/ansible/roles/debops.ferm/templates/lookup/ferm__fix_dependent_rules.j2

**Comment by drybjed** [comment]
This is an Ansible bug with Jinja >2.8, you need to downgrade to 2.8.

**Comment by stefangweichinger** [comment]
Fedora 27 here on my desktop, jinja (never heard of) from upstream, ansible from git-repo, now switched to ansible from F27. Same error. ok, maybe fedora-issue.

**Comment by drybjed** [comment]
Check which `jinja` version you use:
```
pip list | grep Jinja
```
I'm not sure about Fedora, but if you cannot downgrade to Jinja 2.8, then using `virtualenv` environment might be a good alternative.

**Comment by stefangweichinger** [comment]
Jinja2 (2.9.6)  ... (sure I heard of jinja, wrote templates myself. It was too late yesterday ;-))
A bit more information around your virtualenv suggestion would be great. Thanks.

**Comment by drybjed** [comment]
Instructions how to install DebOps in a `virtualenv` [are in the documentation](https://docs.debops.org/en/latest/user-guide/install.html#installation-in-a-python-virtualenv), but perhaps this could be moved to its own section with explanation for different operating systems.

**Comment by drybjed** [comment]
This bug should be finally fixed by https://github.com/debops/debops/pull/223, therefore I'm closing this issue.
