### ISSUE TITLE
ldap/init-directory doesn't work with Debian Bullseye (when starting from a minimal cdebootstrap install)

### ISSUE THREAD

**Issue by Alphix** [debops/debops#1793]
Tested on clean `bullseye` and `buster` VMs.

First a test run using `buster`:

```
~/debops$ fgrep -r ldap_ ansible/inventory
ansible/inventory/group_vars/all/ldap.yml:ldap__device_separate_domains: False
ansible/inventory/group_vars/all/ldap.yml:ldap__servers: [ 'vmtest.example.com' ]
ansible/inventory/group_vars/all/ldap.yml:ldap__admin_server_uri: "ldapi:///"
ansible/inventory/group_vars/all/ldap.yml:ldap__admin_delegate_to: "vmtest"

~/debops$ ./vmsetup vmtest buster
...

~/debops$ ssh root@vmtest
Warning: Permanently added the ECDSA host key for IP address..to the list of known hosts.
...
root@vmtest:~# exit
logout
Connection to vmtest closed.

~/debops$ debops bootstrap -l vmtest -e ansible_user=root
Running Ansible playbooks:
...

~/debops$ debops common -l vmtest
Running Ansible playbooks:
...

~/debops$ debops service/slapd -l vmtest
Running Ansible playbooks:
...

~/debops$ debops ldap/init-directory -e admin_plaintext_password=test123 -l vmtest
Running Ansible playbooks:
...

~/debops$ echo $?
0
```

Now, with `bullseye`:

```
~/debops$ ./vmsetup vmtest bullseye
...

~/debops$ ssh root@vmtest
Warning: Permanently added the ECDSA host key for IP address..to the list of known hosts.
...
root@vmtest:~# exit
logout
Connection to vmtest closed.

~/debops$ debops bootstrap -l vmtest -e ansible_user=root
Running Ansible playbooks:
...

~/debops$ debops common -l vmtest
Running Ansible playbooks:
...

~/debops$ debops service/slapd -l vmtest
Running Ansible playbooks:
...

~/debops$ debops ldap/init-directory -e admin_plaintext_password=test123 -l vmtest
Running Ansible playbooks:
...
TASK [ldap : Create personal account for <LOCAL_USER>] *************************************
fatal: [vmtest]: FAILED! => changed=false 
  censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'

~/debops$ debops ldap/init-directory -e debops__no_log=false -e admin_plaintext_password=test123 -l vmtest
Running Ansible playbooks:
...
TASK [ldap : Create personal account for <LOCAL_USER>] *************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ldap.CONNECT_ERROR: {'desc': 'Connect error', 'info': '(unknown error code)'}
fatal: [vmtest]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  details: '{''desc'': ''Connect error'', ''info'': ''(unknown error code)''}'
  msg: Cannot start TLS.

~/debops$ ssh root@vmtest journalctl -u slapd | tail -n6
Aug 10 12:48:20 vmtest slapd[16641]: conn=1133 fd=14 ACCEPT from PATH=/var/run/slapd/ldapi (PATH=/var/run/slapd/ldapi)
Aug 10 12:48:20 vmtest slapd[16641]: conn=1133 op=0 EXT oid=1.3.6.1.4.1.1466.20037
Aug 10 12:48:20 vmtest slapd[16641]: conn=1133 op=0 STARTTLS
Aug 10 12:48:20 vmtest slapd[16641]: conn=1133 op=0 RESULT oid= err=0 text=
Aug 10 12:48:20 vmtest slapd[16641]: conn=1133 fd=14 TLS established tls_ssf=256 ssf=256
Aug 10 12:48:20 vmtest slapd[16641]: conn=1133 fd=14 closed (connection lost)

~/debops$ debops ldap/init-directory -e ldap__start_tls=false -e admin_plaintext_password=test123 -l vmtest
Running Ansible playbooks:
...

~/debops$ echo $?
0
```

I'm not sure why the playbook returns `Cannot start TLS` on `bullseye` when the `journald` log seems to indicate that TLS was, in fact, established and why the same sequence of steps is succesful on `buster`.

**Comment by drybjed** [comment]
Thanks for the heads up. I have a Bullseye environment set up already, but I haven't done LDAP in it yet, I'll see what I can find.

**Comment by Alphix** [comment]
I've done some more digging, and the output from `journalctl` above is a bit misleading, the TLS session is started but `slapd`s certificate isn't trusted (`vmtest1` in this example is the VM running `slapd`):

```
root@vmtest1:~# ldapsearch -H ldapi:/// -D <ldap_admin_dn> -ZZ -W -d1
...
TLS: peer cert untrusted or revoked (0x42)
TLS: can't connect: (unknown error code).
...

root@vmtest1:~# slapcat -n0 | grep -i tls
olcTLSCACertificateFile: /etc/pki/realms/domain/CA.crt
olcTLSCertificateFile: /etc/pki/realms/domain/default.crt
olcTLSCertificateKeyFile: /etc/pki/realms/domain/default.key
olcTLSDHParamFile: /etc/pki/dhparam/set0
olcTLSCipherSuite: SECURE256:PFS:-VERS-SSL3.0:-VERS-TLS-ALL:+VERS-TLS1.2:-SH

root@vmtest1:~# ls -al /etc/pki/realms/domain/
total 32
drwxr-xr-x 8 root root     4096 Aug 12 10:57 .
drwxr-xr-x 3 root root     4096 Aug 12 10:57 ..
drwxr-x--- 2 root root     4096 Aug 12 10:57 acme
lrwxrwxrwx 1 root root       18 Aug 12 10:57 CA.crt -> public/trusted.pem
drwxr-xr-x 2 root root     4096 Aug 12 10:57 config
lrwxrwxrwx 1 root root       16 Aug 12 10:57 default.crt -> public/chain.pem
lrwxrwxrwx 1 root root       15 Aug 12 10:57 default.key -> private/key.pem
lrwxrwxrwx 1 root root       29 Aug 12 10:57 default.pem -> private/key_chain_dhparam.pem
drwxr-xr-x 2 root root     4096 Aug 12 10:57 external
drwxr-xr-x 2 root root     4096 Aug 12 10:57 internal
drwxr-x--- 2 root ssl-cert 4096 Aug 12 10:57 private
drwxr-xr-x 2 root root     4096 Aug 12 10:57 public
lrwxrwxrwx 1 root root       18 Aug 12 10:57 trusted.crt -> public/trusted.pem
```

**Comment by Alphix** [comment]
Hmm...

```
root@vmtest1:~# ls -al /etc/ldap/ldap.conf
ls: cannot access '/etc/ldap/ldap.conf': No such file or directory

root@vmtest1:~# echo "TLS_CACERT /etc/pki/realms/domain/CA.crt" >> /etc/ldap/ldap.conf

root@vmtest1:~# ldapsearch -H ldapi:/// -D <ldap_admin_dn> -ZZ -W
Enter LDAP Password: <ldap_admin_pw>
# extended LDIF
#
# LDAPv3
# base <> (default) with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# search result
search: 3
result: 32 No such object

# numResponses: 1
```

**Comment by drybjed** [comment]
That's weird, `/etc/ldap/ldap.conf` file should be created by the `libldap-common` Debian package, can you check if it's installed?

**Comment by Alphix** [comment]
`libldap-common` is not installed on `vmtest1` (note to self: the `ldap` role should further customise `ldap.conf` but only if it's not a dependent play).

The only plays I've done on `vmtest1` are `bootstrap`, `common`, `service/slapd` and `ldap/init-directory` (in that order).

That sequence works on `buster` but not on `bullseye`. I'll try to setup two VMs later today to find out what has changed.

**Comment by Alphix** [comment]
Ok, I'm using ``cdebootstrap --flavour=minimal`` to build the VMs which I run with ``systemd-nspawn``. For that reason, I'm including some extra packages (`--include=systemd-container,iproute2,procps,python3,openssh-server`).

In `buster`, there's this dependency chain: `systemd-container` -> `libcurl3-gnutls` -> `libldap-2.4-2` -> `libldap-common`, so `libldap-common` is included from the very beginning.

In `bullseye`, `libldap` only recommends `libldap-common`, so it's never installed.

One way to fix it in a backwards compatible manner would be to change `slapd__base_packages` to include `libldap-common` (I just tested it and it fixes the issue for me in a `bullseye` VM).

Shall I prepare a pull request?

**Comment by drybjed** [comment]
Sure, go ahead since it seems that it's requirement for `slapd` to work correctly. I think that on a standard Debian install it will be pulled fine, but for your case we can add it in the role.

**Comment by stefangweichinger** [comment]
In my current tests with a fresh bullseye VM `libldap-common` gets installed, but `service/slapd` fails anyway:

```
TASK [slapd : Load custom LDAP schemas] *********************************************************************************************************************************************
task path: [SOMEPATH..]debops/ansible/roles/slapd/tasks/main.yml:95
The full traceback is:
NoneType: None
failed: [services.my.tld] (item=/etc/ldap/schema/debops/debops.schema) => changed=true 
  ansible_loop_var: item
  item: /etc/ldap/schema/debops/debops.schema
  msg: non-zero return code
  rc: 1
  stderr: |-
    Shared connection to 172.32.99.201 closed.
  stderr_lines: <omitted>
  stdout: |-
    ! This tool is only intended to be with with a cn=config backend, cn=config could not be found in the LDAP at /usr/bin/ldap-schema-manager line 324.
  stdout_lines: <omitted>
```

I added the suggested patch from https://github.com/debops/debops/pull/1798 just to be sure, didn't make a change (sure, the package is there already).

**Comment by Alphix** [comment]
@stefangweichinger: That seems like a separate issue (that I can't reproduce).

`debops/ansible/roles/slapd/tasks/main.yml:95` calls `debops/ansible/roles/slapd/files/script/ldap-load-schema` on the remote host. The script calls `fusiondirectory-insert-schema` from the `fusiondirectory-schema` package on line `54`. `fusiondirectory-schema` calls `ldap-schema-manager` on line `38`, and that seems to be the tools that errors out for you.

`ldap-schema-manager` will run `ldapsearch -Y EXTERNAL -H ldapi:/// -b "cn=config" cn=config dn 2> /dev/null | grep dn:` and print the error message you get if there's no output.

One reason why there might be no output would be, for example, if `slapd` isn't running. Have you checked that `slapd` is running? Some `[c]debootstrap` installations will, for example, include packages like `cdebootstrap-helper-rc.d` that are meant to prevent automatic starting of servers (see if `/usr/sbin/policy-rc.d` is present).

If `slapd` *is* running, see if `/etc/ldap/slapd.d/cn=config` exists and try running the above `ldapsearch` invocation manually and verify that there is some output. Next, run `fusiondirectory-insert-schema` as root on your test VM (warning: will install extra schemas you probably don't want).

It should output several entries like this:
```
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
executing 'ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/fusiondirectory/core-fd.ldif'
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=core-fd,cn=schema,cn=config"
``` 

If you run it again, the output should instead be something like this:
```
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
core-fd already exists in the LDAP, skipping…
```

**Comment by stefangweichinger** [comment]
@Alphix thanks for your help. I started over X times now to get my small test cluster configured, so I am not exactly on that point anymore, but see similar issues. I will report back if I have valid output.
