### ISSUE TITLE
[debops.apt_proxy] The 'python3-future' package requires 'jessie-backports' Debian repository

### ISSUE THREAD

**Issue by drybjed** [debops/debops#181]
The `debops.apt_proxy` role contains a Python script which allows easy handling of unreachable APT caches, implented in https://github.com/debops/debops/commit/5bdb2c148c4. This script apparently relies on code provided by the `python3-future` APT package, which is available on Debian Jessie via the `jessie-backports` repository.

In certain situations, particularly initial host deployment, where the APT proxy support is enabled, playbook run can be aborted due to the `python3-future` package not being available when `jessie-backports` repository hasn't been configured yet. A solution would be to drop the `python3-future` from the script requirements.

**Comment by ypid** [comment]
My mistake. `python3-future` is not actually needed.

```Shell
$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import __future__
>>> __future__.__file__
'/usr/lib/python3.4/__future__.py'
$ dpkg -S /usr/lib/python3.4/__future__.py
libpython3.4-minimal:amd64: /usr/lib/python3.4/__future__.py
```
