### ISSUE TITLE
Problem with postgresql

### ISSUE THREAD

**Issue by krystophe** [debops/debops#1814]
Hi,

I'm having an issue with the postgresql role in debops.
It's failed with this log:

14:49:38 TASK [postgresql : Drop PostgreSQL roles if requested] *************************
14:49:38 failed: [pm-cja-re7-BDDCds -> None] (item=None) => changed=false 
14:49:38   censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'
14:49:38 failed: [pm-cja-re7-BDDCds -> None] (item=None) => changed=false 
14:49:38   censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'

I don't know why.
Thanks for help

**Comment by imrejonk** [comment]
Hi krystophe,

Try setting `debops__no_log` to `False` and running the role again. This will provide useful output, but will also print things like passwords and other sensitive information. Please remove any sensitive information before posting the output here.

**Comment by krystophe** [comment]
Hi,

I tried 
debops__no_log: 'true' in postgresql.yml and postgresql_server.yml doesn't work
no_log: 'False' in postgresql.yml and postgresql_server.yml doesn't work too

Where do I need to set this option ?

**Comment by krystophe** [comment]
Hi,

the service postgresql@11-main.service can't start here is the output:
Error: Could not open logfile /var/log/postgresql/postgresql-11-main.log
Error: /usr/lib/postgresql/11/bin/pg_ctl /usr/lib/postgresql/11/bin/pg_ctl start -D /var/lib/postgresql/11/main -l /var/log/postgresql/postgresql-11-main.log -s -o  -c config_file="/etc/postgresql/11/main/postgresql.conf"  exited with status 1:
 postgresql@11-main.service: Can't open PID file /run/postgresql/11-main.pid (yet?) after start: No such file or directory

**Comment by krystophe** [comment]
Hi,

It's seems like there is a bug with debops install of postgresql.
Install postgresql with apt install works, I can restart the cluster with pg_ctlcluster.

When I installed postgresql with debops , the service postgresql@11-main.service failed to restart

**Comment by imrejonk** [comment]
I suspect that you are running an older version of DebOps because `debops__no_log` was introduced in DebOps version 2.3.0. Please tell me what version of DebOps you run and if you have overridden any default role variables. Only then can I try to reproduce your issue and attempt to fix it.

**Comment by imrejonk** [comment]
Also, what does ‘sudo journalctl -u postgresql@11-main.service’ show?

**Comment by krystophe** [comment]
Hi,

I solve the problem.
