### ISSUE TITLE
Replace comma with dot in debops.users when condition

### ISSUE THREAD

**Issue by jrgoldfinemiddleton** [debops/debops#183]
https://github.com/debops/debops/blob/a34cdcaab6ca9e5154ab64116a75ed03c1cbd331/ansible/roles/debops.users/tasks/resources.yml#L35

https://github.com/debops/debops/blob/a34cdcaab6ca9e5154ab64116a75ed03c1cbd331/ansible/roles/debops.users/tasks/resources.yml#L52

`item,path|d()` should be `item.path|d()`

**Comment by drybjed** [comment]
Good catch! Want to do a PR with the change?
