### ISSUE TITLE
[resolvconf] Task "Install required packages" incoherent with others?

### ISSUE THREAD

**Issue by mathieumd** [debops/debops#1831]
The task `Install required packages` has  a condition `when: resolvconf__enabled|bool`.

But following tasks has the condition `when: resolvconf__enabled|bool and resolvconf__static_enabled|bool`.

Is there any meaning to setup resolvconf static configuration without installing `resolvconf`?

**Comment by drybjed** [comment]
No, but you don't need to set up static configuration when `resolvconf` is installed, that's why it is conditional. By default, static configuration is disabled and needs to be explicitly enabled for these tasks to execute.

**Comment by mathieumd** [comment]
OK, thanks. Sorry for the noise!
