### ISSUE TITLE
ansible-lint 4.3 couldn't resolve module/action 'dpkg_divert'

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#1853]
`make lint` fails on Debian 11 with this message:

```
CRITICAL Couldn't parse task at /home/imre/src/debops/debops/ansible/roles/pki/tasks/certbot.yml:20 (couldn't resolve module/action 'dpkg_divert'. This often indicates a misspelling, missing collection, or incorrect module path.)
{ 'dpkg_divert': { '__file__': '/home/imre/src/debops/debops/ansible/roles/pki/tasks/certbot.yml',
                   '__line__': 22,
                   'path': '/etc/letsencrypt/cli.ini',
                   'state': 'present'},
  'name': 'Divert the original certbot configuration file'}
make: *** [Makefile:184: test-ansible-lint] Error 3
```

This is most likely a configuration issue, as the dpkg_divert module is present in `ansible/roles/ansible_plugins/library/dpkg_divert.py`.

I'm using the 'ansible' and 'ansible-lint' packages from Debian 11, versions `2.10.7+merged+base+2.10.8+dfsg-1` and `4.3.7-1` respectively.

**Comment by drybjed** [comment]
This should be fixed in `ansible-lint` from upstream. You can try installing it from PyPi.

**Comment by imrejonk** [comment]
That seems to be the issue, thanks for pointing it out. Too bad we can't use the `ansible-lint` from Stable though. I hope that a more recent version makes it to Testing soon, so that I can try backporting it.
