### ISSUE TITLE
[etckeeper] First run fails on Unstage task.

### ISSUE THREAD

**Issue by schmidthausen** [debops/debops#1897]
etckeeper role task main.yml, first run failure. Suspected issue with line 155: extra empty tag. Is there supposed to be another tag there or are the dashes there by mistake? Subsequent runs do not produce this failure.

TASK [etckeeper : Unstage and remove ignored files from Git index] ***********************************************************************************
fatal: [debtest]: FAILED! => changed=false 
  cmd: set -o nounset -o pipefail -o errexit && etckeeper vcs ls-files -i --exclude-standard -z | xargs -0 --no-run-if-empty etckeeper vcs rm --cached --
  delta: '0:00:00.042079'
  end: '2021-10-26 21:00:18.935315'
  msg: non-zero return code
  rc: 128
  start: '2021-10-26 21:00:18.893236'
  stderr: 'fatal: ls-files -i must be used with either -o or -c'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

**Comment by schmidthausen** [comment]
This only happens on bookworm/testing. So for current stable/oldstable this change isn't required. Passing -c fixes it for bookworm and doesn't seem to harm the play for buster and bullseye. I will check the logs to see what it does for each release.

**Comment by ser** [comment]
It happens to me as well, on debian/sid.

```
TASK [etckeeper : Unstage and remove ignored files from Git index] *********************************************************************************************************************************
fatal: [myhost]: FAILED! => {"changed": false, "cmd": "set -o nounset -o pipefail -o errexit && etckeeper vcs ls-files -i --exclude-standard -z | xargs -0 --no-run-if-empty etckeeper vcs rm --cached --", "delta": "0:00:00.057257", "end": "2022-02-02 17:36:39.401304", "msg": "non-zero return code", "rc": 128, "start": "2022-02-02 17:36:39.344047", "stderr": "fatal: ls-files -i must be used with either -o or -c", "stderr_lines": ["fatal: ls-files -i must be used with either -o or -c"], "stdout": "", "stdout_lines": []}
```

could you please try to deploy the PR?
