### ISSUE TITLE
[sshd] Default LoginGraceTime conflicts with UseDNS setting

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#1904]
The default LoginGraceTime, the time after which the OpenSSH server disconnects the client if it fails to present a valid key or password, is 30 seconds in DebOps. The upstream default is 120 seconds. I think the rationale here was that a shorter LoginGraceTime better prevents against a type of DoS attack where the attacker opens up many SSH connections without actually authentication, thereby starving the server.

The `debops.sshd` role by default also enables UseDNS, which tells the server to attempt verifying the remote host name through DNS. This is disabled by upstream by default. I am not sure why we enabled this feature, it could have something to do with the pam_access configuration (although I am not sure if the use of UseDNS actually has any effect there given that PAM is not OpenSSH).

A problem occurs when the DNS resolvers don't respond or are slow to respond. The default configuration in `<resolv.h>` in glibc is to wait five seconds before a different resolver is attempted, and retry each resolver once more before an error is returned. This is configurable through [resolv.conf(5)](https://manpages.debian.org/resolv.conf.5). If you have three resolvers configured (the glibc maximum), the worst-case scenario is that the glibc resolver returns an error after a full 30 seconds. The LoginGraceTime has now expired and the server disconnects you. If the server you are trying to get into provides its own DNS resolver, you now have a nice catch-22 to deal with. Ask me how I know ;)

So this is a kind of RFC, I propose that we set the LoginGraceTime to 60 seconds (30 seconds feels really short to me). This makes the LoginGraceTime the same as the default console LOGIN_TIMEOUT which is configured in /etc/login.defs. Administrators who are targeted by the kind of DoS attacks described above can always shorten it themselves.
I also propose that we disable the UseDNS setting, unless there is a good reason to keep it enabled.

**Comment by drybjed** [comment]
Changing LoginGraceTime to 60 seconds sounds good to me.

UseDNS set to `yes` is required by PAM to recognize the DNS domain used by the client. The default configuration created by the `sshd` role via the `pam_access` role permits access from hosts on the same DNS domain. I would like for this to be enabled by default, since DNS timeouts shouldn't happen in a properly configured environment. And if they do happen, looking at DNS should be done first before changing DNS client configuration.

**Comment by imrejonk** [comment]
Ah okay, so UseDNS does have an effect on the PAM configuration. Let's keep it enabled.

I'll make a PR for the LoginGraceTime change.
