### ISSUE TITLE
Bug nginx.yml ? 

### ISSUE THREAD

**Issue by krystophe** [debops/debops#1906]
Hi,

The nginx role failed 
with  location:
            # BOSH for subdomains
          "'~ ^/([^/?&:'"]+)/http-bind'": |
            set $subdomain "$1.";
            set $subdir "$1/";
            set $prefix "$1";
            rewrite ^/(.*)$ /http-bind;

I tried this, but it doesn't work too
          # BOSH for subdomains
          '"~ ^/([^/?&:'"]+)/http-bind"': |
            set $subdomain "$1.";
            set $subdir "$1/";
            set $prefix "$1";
            rewrite ^/(.*)$ /http-bind;

I need to customize nginx vhost for jitsi

Here is the output:

13:40:51 The error appears to be in '/mypath/myvm/nginx.yml': line 65, column 12, but may
13:40:51 be elsewhere in the file depending on the exact syntax problem.
13:40:51 
13:40:51 The offending line appears to be:
13:40:51 
13:40:51           # BOSH for subdomains
13:40:51           '~ ^/([^/?&:'"]+)/http-bind': |
13:40:51            ^ here
13:40:51 We could be wrong, but this one looks like it might be an issue with
13:40:51 unbalanced quotes. If starting a value with a quote, make sure the
13:40:51 line ends with the same set of quotes. For instance this arbitrary
13:40:51 example:
13:40:51 
13:40:51     foo: "bad" "wolf"
13:40:51 
13:40:51 Could be written as:
13:40:51 
13:40:51     foo: '"bad" "wolf"'

**Comment by imrejonk** [comment]
Please read the error message and try to understand it before creating a bug report. Ansible even points you to the exact problem. This is a syntax error in the "/mypath/myvm/nginx.yml" file, you most likely need to escape one or more quote characters.

Closing as this is not a DebOps issue.
