### ISSUE TITLE
when statements should not include jinja2 templating delimiters

### ISSUE THREAD

**Issue by wernerkrauss** [debops/debops#191]
Got a warning running the gitlab playbook:

> TASK [debops.redis : Divert the original Redis config files] 
> 
> [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found:
> ('/etc/redis/{{ item }}.dpkg-divert' not in redis__register_diversions.stdout_lines)
>

**Comment by drybjed** [comment]
Thanks, there are a few of these in different roles, they will be cleaned up when role linting is enabled.

**Comment by drybjed** [comment]
This issue should be solved now due to use of `ansible-lint` in DebOps tests. Closing as resolved.
