### ISSUE TITLE
Let's Encrypt still uses the expired R3 certificate

### ISSUE THREAD

**Issue by pdobrigkeit** [debops/debops#1937]
Hello, I am using DebOps to configure a server including the ACME scripts for SSL. It seems that I now have problems with the expired R3 certificate from Let's Encrypt. Usure how to solve this. 

In my /etc/pki/realm it looks like this:

    lrwxrwxrwx 1 root root       53 May 25  2021 root.pem -> /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt

**Comment by reixd** [comment]
Take a look at https://github.com/debops/debops/issues/1860

**Comment by imrejonk** [comment]
Yes, this was fixed in https://github.com/debops/debops/issues/1860, which is currently in master and the stable branches. An official release that contains this fix has not been released yet (will probably be January 2022).

**Comment by pdobrigkeit** [comment]
Yeah, thanks. Manually changing it and deleting the realm to recreate it solved the issue.
