### ISSUE TITLE
PKI regression

### ISSUE THREAD

**Issue by bleuchtang** [debops/debops#1946]
Commit https://github.com/debops/debops/commit/078ae6295b43c540f7206d9e5dd9518a89311d1e introduce a new variable `acme_type` in config/realm.conf file config. This variable is only setup at the creation of the LE certificate, so LE certificates generated before are not working anymore (because of  https://github.com/debops/debops/blob/master/ansible/roles/pki/files/usr/local/lib/pki/pki-realm#L1352)

I think a workaround is to set `acme_type` variable as `acme-tiny` by default when we whant LE certificats.

cc @julien-lecomte

**Comment by julien-lecomte** [comment]
What's the value of `pki_acme_type` in your inventory? and of config['pki_acme'] from the config file?

**Comment by bleuchtang** [comment]
Default value for `pki_acme_type` (acme-tiny)

and

```
/etc/pki# rgrep pki_acme  
realms/domain/config/realm.conf:config['pki_acme']='true'
realms/domain/config/realm.conf:config['pki_acme_library']='openssl'
```

**Comment by thoemy** [comment]
I can confirm this. I made the following change to `pki-realm`

```patch
--- pki-realm	2021-12-21 09:33:07.505691980 +0000
+++ pki-realm.fixed	2021-12-21 09:32:37.873761393 +0000
@@ -222,7 +222,7 @@
     config["acme_default_domain"]="$(get_dnsdomainname)"
     config["acme_default_subdomains"]="www/ftp/mail/smtp/imap"
 
-    config["acme_type"]=""
+    config["acme_type"]="acme-tiny"
     config["acme_subject"]=""
     config["acme_domains"]=""
     config["acme_subdomains"]=""
```

**Comment by julien-lecomte** [comment]
I haven't had much time lately, but I guess a possible fix would be changing in https://github.com/debops/debops/blob/master/ansible/roles/pki/files/usr/local/lib/pki/pki-realm#L1352 :

~~~
if [ "${config['acme_type']}" == "acme-tiny" ]; then
~~~
to
~~~
if [ "${config['acme_type']}" == "acme-tiny" ] || [ "${config['acme_type']}" == "" ] ; then
~~~

I'd really like to test before doing a PR, but I haven't got a setup that can be configured with a default acme setup
(edited)

**Comment by thoemy** [comment]
The `test` command doesn't seem to like `||`.
```
$ /usr/local/lib/pki/pki-realm run -n example.com
/usr/local/lib/pki/pki-realm: line 1352: [: missing `]'
/usr/local/lib/pki/pki-realm: line 1352: : command not found
```
Changing it to the bash `[[` keyword fixes it.
```
if [[ "${config['acme_type']}" == "acme-tiny" || "${config['acme_type']}" == "" ]]; then
```
I confirmed that the above line works on Debian Buster (10) and Bullseye (11).

**Comment by julien-lecomte** [comment]
Yes, you're right; my PR is correct, unlike my comment.

**Comment by drybjed** [comment]
Should be fixed by https://github.com/debops/debops/pull/1960, closing.
