### ISSUE TITLE
Design the GitLab CI test infrastructure using LXC

### ISSUE THREAD

**Issue by drybjed** [debops/debops#2]
GitLab CI can be used with Docker to test roles and playbooks, but Docker containers are very limited since there's no real service management. LXC containers seem to be better suited to test DebOps environments, since they can behave like normal hosts with multiple services, an init system, etc.

There's an existing GitLab Runner [LXC executor proposal](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/merge_requests/436) which might be useful in the future. For now, DebOps could develop its own scripts used with the GitLab Runner `shell` executor to manage the LXC containers and run jobs in them manually.

Todo:

- [x] Review the `debops.lxc` role and update it to work properly on Debian Stretch
- [x] Develop the test scripts that prepare the LXC container test environment
- [x] Update all the DebOps roles needed to self-host the LXC container test environment

**Comment by drybjed** [comment]
DebOps tests can now be performed using LXC containers using `debops.lxc` role, GitLab Runners and the `vagrant-lxc` plugin. Closing the issue as resolved.

**Comment by nqb** [comment]
@drybjed,

for my information, do you still use the `shell` executor on GitLab ?

**Comment by drybjed** [comment]
@nqb Yes. That's why new PRs to the repository are not pushed directly to GitLab, only after the code is reviewed and merged. I don't think that there's an LXC executor available yet in GitLab Runners... Quick googling shows https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/436 but it's not merged.

Well, it's the same as I linked before, so I guess nothing changed in that regard during all this time.

**Comment by nqb** [comment]
Thanks !
