### ISSUE TITLE
debops.nsswitch/debops.libvirt: add support for libvirt and libvirt_guest services for nsswitch hosts database

### ISSUE THREAD

**Issue by quiescentnexus** [debops/debops#200]
It would be nice to have built-in support for the `libvirt` and `libvirt_guest` services for the nsswitch hosts database. They're the most effort-free way of letting a hypervisor resolve hostnames of VMs that use the built-in dnsmasq-based NAT provided by libvirt.

Upstream documentation: https://libvirt.org/nss.html

Both services are provided by the `libnss-libvirt` package in Stretch.

A configuration I am using now to enable the `libvirt` service:
```---
nsswitch__group_database_map:
    'hosts':
      - 'files'
      - 'libvirt'
      - 'dns'
      
nsswitch__group_services: [ 'libvirt' ]
```
It works, but overrides the default `hosts` map, which is more feature-rich and could change in the future. The point of including them in the role would be to remove the need for a map override, and to ensure that the `libnss-libvirt` package is installed when these services are enabled.

As it's up to the user to decide if they need the `libvirt` or the `libvirt_guest` service (or both) for their deployment, both should probably be disabled by default even for `debops_service_libvirt` hosts.

**Comment by drybjed** [comment]
Sounds good. It could probably be added bedore `dns` and after `mdns` entries in `/etc/nsswitch.conf`. I'll setup a `libvirt` environment to test if this works when I have some time.
