### ISSUE TITLE
[sysctl] pid_max too high on 32-bit architectures

### ISSUE THREAD

**Issue by prahal** [debops/debops#2051]
For 32 bits arch pid_max maximum value is 32768. With current debops value of 4194304 sysctl errors out.

[arm 32bit: Couldn't write '4194304' to 'kernel/pid_max': Invalid argument #12604](https://github.com/systemd/systemd/issues/12604)  "
For 32bit systems pid_max maximum value is 32768,
from man 5 proc

 On 32-bit platforms, 32768 is the maximum value for pid_max.
"

Sadly ansible_architecture looks like the only filter to set the value based on 32 bits or not. I found ansible_userspace_bits but based on [ ansible_userspace_bits fact is incorrect when running 32bit python on 64bit architecture #5510 ](https://github.com/ansible/ansible/issues/5510) it seems it cannot be relied upon to detect architecture word size.

On armhf a box I get:
```
$ sudo systemctl status systemd-sysctl.service
● systemd-sysctl.service - Apply Kernel Variables
     Loaded: loaded (/lib/systemd/system/systemd-sysctl.service; static)
     Active: failed (Result: exit-code) since Thu 2022-03-17 17:13:34 CET; 4s ago
       Docs: man:systemd-sysctl.service(8)
             man:sysctl.d(5)
    Process: 3019 ExecStart=/lib/systemd/systemd-sysctl (code=exited, status=1/FAILURE)
   Main PID: 3019 (code=exited, status=1/FAILURE)
        CPU: 23ms

Mar 17 17:13:34 uruk systemd[1]: Starting Apply Kernel Variables...
Mar 17 17:13:34 uruk systemd-sysctl[3019]: Couldn't write '4194304' to 'kernel/pid_max': Invalid argument
Mar 17 17:13:34 uruk systemd[1]: systemd-sysctl.service: Main process exited, code=exited, status=1/FAILURE
Mar 17 17:13:34 uruk systemd[1]: systemd-sysctl.service: Failed with result 'exit-code'.
Mar 17 17:13:34 uruk systemd[1]: Failed to start Apply Kernel Variables.
phn@uruk:~$ sudo /lib/systemd/systemd-sysctl
Couldn't write '4194304' to 'kernel/pid_max': Invalid argument
```

the culprit:
```
$ cat /etc/sysctl.d/50-pid-max.conf 
# This file is managed remotely, all changes will be lost

# This file is part of systemd.
#
# systemd is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# See sysctl.d(5) and core(5) for documentation.
#
# To override settings in this file, create a local file in /etc
# (e.g. /etc/sysctl.d/90-override.conf), and put any assignments
# there.

# Bump the numeric PID range to its maximum of 2^22 (from the in-kernel default
# of 2^16), to make PID collisions less likely.
kernel.pid_max = 4194304

```

**Comment by drybjed** [comment]
We can use `ansible_architecture` to select the pid_max value, sure. Can you list the architectures that are affected, so we can select the proper value conditionally?

Also, do you have the `50-pid-max.conf` file on the original installation in these systems? I'm curious if it's commented out or not, and what's the default value on these architectures included in the Debian package.

**Comment by prahal** [comment]
Debian bullseye systemd packages ships the /usr/lib/sysctl.d/50-pid-max.conf on amd64, arm64, mips64el, ppc64el, s390x only, ie 64 bits only:
```
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

# See sysctl.d(5) and core(5) for documentation.

# To override settings in this file, create a local file in /etc
# (e.g. /etc/sysctl.d/90-override.conf), and put any assignments
# there.

# Bump the numeric PID range to its maximum of 2^22 (from the in-kernel default
# of 2^16), to make PID collisions less likely.
kernel.pid_max = 4194304
```
per https://packages.debian.org/search?suite=bullseye&arch=any&mode=path&searchon=contents&keywords=50-pid-max.conf

So this file is not shipped on 32 bits. Maybe we could do alike and thus code it so it is only shipped for a set of 64 architectures instead of checking for 32 bits an architecture.

I do not know ansible_architecture architectures values. With my boxes I can tell for 64 bits that amd64 is ansible_architecture is 'x86_64' and arm64 is 'aarch64'. For 32 bits my armhf is 'armv7l'.

I found that ansible_architecture and ansible_userspace_bits are set in ansible at https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/system/platform.py from python platform https://docs.python.org/3/library/platform.html , ie ansible_userspace_bits is extracted from python platform.architecture and ansible_architecture from platform.machine which is mostly uname's machine with a few tweaks for windows and mac.

Now I wonder if we should care about the python executable being 32 bit on a 64 bit box. Should we ship 50-pid-max.conf in this case ?
Else we could simply rely on a test of '64' equals to ansible_userspace_bits to decide if we ship it.
