### ISSUE TITLE
debops run bootstrap -l new-host -u bootstrapuser  ignores user for ssh connection

### ISSUE THREAD

**Issue by martin-huber** [debops/debops#2082]
We are using debops in the following version
```
ansible@ansible:~/debops$ debops --version
debops 3.0.2
ansible@ansible:~/debops$ ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.9 (default, Mar 15 2022, 13:55:28) [GCC 8.4.0]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
ansible [core 2.11.9]
  config file = /home/ansible/debops/ansible.cfg
  configured module search path = ['/home/ansible/debops/ansible/plugins/modules', '/home/ansible/.local/lib/python3.6/site-packages/debops/_data/ansible/collections/ansible_collections/debops/debops/plugins/modules', '/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/ansible/debops/ansible/collections:/home/ansible/.ansible/collections:/home/ansible/.local/lib/python3.6/site-packages/debops/_data/ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.6.9 (default, Mar 15 2022, 13:55:28) [GCC 8.4.0]
  jinja version = 2.11.3
  libyaml = True
```
We recently upgraded to 3.0 and to 3.0.2 today.

If we try to bootstrap a new machine, we are failing executing

```
debops run bootstrap -l new-host -u bootstrapuser
```
Doing an `ssh bootstrapuser@new-host` succeeds w/o password .

Switching on "-vvvv" shows, that the user, that **is** used to try the remote connection is the user `ansible`

Inspecting, what command line arguments are passed to `ansible-playbook` shows, that this still is called with `-u bootstrapuser`

If we execute
```
debops run bootstrap -l new-host -e 'ansible_user=bootstrapuser'
```
the bootstrap succeeds.

Is there anyhing broken with bootstrapping machines with another user than `ansible` / the local user on the ansible controller ?

**Comment by Alphix** [comment]
@martin-huber is ``ansible_user`` defined in the Ansible inventory for ``new-host``? If so, this behaviour seems to match the documentation...? (see the third example [here](https://docs.debops.org/en/stable-3.0/introduction/getting-started.html#bootstrap-a-new-host))

**Comment by martin-huber** [comment]
Indeed, it seems, that a colleague of mine introduced ansible_user in the inventory after switching to 3.0 and when moving from the `all` group to the `debops_all_hosts` group. Maybe he was of the impression, he would have to define `ansible_user` and `system_users__self_name` in addition . 
I guess, he saw this snippet in the docs
```
[debops_all_hosts]
server    ansible_host=server.example.com ansible_user=ansible-admin
server    system_users__self_name=ansible-admin
```
and introduced this in the inventory, such implementing the breaking difference.

Since our local user on the ansible controller is the user `ansible` who also should be the ansible_user everywhere, I will try remove the 2 definitions from our inventory and see, if it will fix the next bootstrap.

Thanks for the valuable hint !

**Comment by Alphix** [comment]
So....can the issue be closed?

**Comment by martin-huber** [comment]
I think, yes, you can close the ticket, because chances are very high, that it will solve the issue. We will test it asap, in the worst case, we will open another one, what I do not expect.

Thanks!

**Comment by Alphix** [comment]
> I think, yes, you can close the ticket, because chances are very high, that it will solve the issue. We will test it asap, in the worst case, we will open another one, what I do not expect.
> 
> Thanks!

Nah, I'll let you close the issue once you've done your testing

**Comment by martin-huber** [comment]
We tested it and it is working as expected. Thanks for your help!
I will close the ticket.
