### ISSUE TITLE
Minimum Ansible version?

### ISSUE THREAD

**Issue by Alphix** [debops/debops#2097]
Right now, there's a lot of roles that do stuff like:

```
foo__bar_enabled: '{{ ansible_local.foo.bar | bool
                      if (ansible_local|d() and ansible_local.foo|d() and ansible_local.foo.bar|d())
                      else False }}'
```

because Ansible didn't traditionally support nested variables together with the default filter in a sane way ([example bug report](https://github.com/ansible/ansible/issues/30944)).

Since version 2.8, Ansible does have native support for defaults with nested attributes ([original PR](https://github.com/ansible/ansible/pull/51768)).

So if we mandated Ansible 2.8+, it'd be possible to write much more compact roles, since the above can be simplified as:

```
foo__bar_enabled: '{{ ansible_local.foo.bar | d(False) | bool }}'
```

The closest thing to an official position on minimum Ansible versions that I've found is [this](https://docs.debops.org/en/stable-3.0/introduction/install.html#ansible-notes):

> The latest stable Ansible release is required to run DebOps playbooks and roles. Older Ansible releases may work for a time, but
> support for them is not guaranteed by the DebOps project.
> ...
> Debian
> On the current Debian Stable release, you might need to install the ansible package from the Backports repository. DebOps
> development follows the stable Ansible releases, because of that the version of Ansible included in a Debian Stable release might
> not be sufficient anymore.

Even if we ignore the latest stable Ansible release, then:

- Debian Buster (oldstable) has Ansible 2.7 (with a 2.9 backport); and
- Debian Bullseye (stable) has Ansible 2.10

So, @drybjed and @imrejonk, would it be ok to start submitting PRs based on the Ansible 2.8+ syntax?

**Comment by imrejonk** [comment]
Sure, go ahead. I've been using Ansible 2.9 for a while now. We have also been using the more compact syntax for some time and no one complained about it.

@drybjed I assume you are okay with this as well?

**Comment by drybjed** [comment]
Sure, Ansible v2.8+ is fine. DebOps is meant to work on current Ansible stable release from upstream, which means that version included with Debian Stable will not work after some time, but backports are available. So, Ansible v2.9 can be the current "target".
