### ISSUE TITLE
padlock always yields: gpg: WARNING: no command supplied

### ISSUE THREAD

**Issue by pniederlag** [debops/debops#210]
I have setup encfs support via debops-padlock as documented in https://docs.debops.org/en/latest/debops-tools/scripts/debops-padlock.html

Whenever I run the debops command there are some warnings from gpg displayed:

    gpg: WARNING: no command supplied.  Trying to guess what you mean ...

**Comment by drybjed** [comment]
This might be a result of latest changes, sorry. Are you using `encfs` on Debian Stretch without issues?

**Comment by pniederlag** [comment]
My ansible_controller (debops client) is on "bleeding edge" (buster/sid).

From my point of view it can't harm to add the explicit --decrypt command on any debian version. I have updated the PR to pass the psycode-style failures (line lenght)

**Comment by drybjed** [comment]
Ah, so it's just the `encfs` version in Stretch that is not cooperative, newer one (in Buster) works fine? I wonder if the maintainer would do a backport to `stretch-backports`, but that might need to pull some other libraries as well.
