### ISSUE TITLE
mitogen

### ISSUE THREAD

**Issue by 532910** [debops/debops#2133]
I'm impressed by [mitogen](https://mitogen.networkgenomics.com/ansible_detailed.html) I just tried!
debops.debops.common takes only 3 minutes (20min without)

The only issue it doesn't work with simplified module names: https://github.com/mitogen-hq/mitogen/issues/820

debops master uses FQCN except for own modules like `dpkg_divert` for example

I was able to successfully run it, but after:
```
sed -i -- 's/  dpkg_divert:$/  debops.debops.dpkg_divert:/g' **/*.yml
```

Should FQCN be used everywhere? It seems like ansible recommends so, isn't it?

#### To try it you need:
```
apt install ansible-mitogen
```
`ansible.cfg`:
```
strategy_plugins = /usr/lib/python3/dist-packages/ansible_mitogen/plugins/strategy
strategy = mitogen_host_pinned
```

**Comment by drybjed** [comment]
If this will make DebOps compatible with mitogen, then sure, lst's go with FQCNs everywhere. Can you make a PR for this?

**Comment by 532910** [comment]
> PR

Sure!

**Comment by 532910** [comment]
https://github.com/debops/debops/pull/2165

**Comment by 532910** [comment]
fixed
