### ISSUE TITLE
rspamd-dkim-keygen script: Deprecation Warning

### ISSUE THREAD

**Issue by mathieumd** [debops/debops#2147]
The script shipped by `rspamd` role to renew DKIM keys, which is launched by Cron `/etc/cron.d/rspamd-dkim-keygen`, has an stderr output:
```
/usr/local/sbin/rspamd-dkim-keygen:46: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
```

So every first day of each months, the user `_rspamd` is receiving the cron error output by mail.

(Which we do not actually receive: it's delivered locally. The role should set an alias `_rspamd` → `root`, in `/etc/aliases`, no?)

**Comment by Alphix** [comment]
> The script shipped by `rspamd` role to renew DKIM keys, which is launched by Cron `/etc/cron.d/rspamd-dkim-keygen`, has an stderr output:
> 
> ```
> /usr/local/sbin/rspamd-dkim-keygen:46: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
>   import distutils.spawn
> ```

Yeah, ``distutils.spawn.find_executable`` seems to be deprecated by [PEP632](https://peps.python.org/pep-0632/), I'll write up a patch which favours ``shutils.which`` and falls back to ``distutils``. I've mostly tested the role on Debian stable....which release are you using?

> So every first day of each months, the user `_rspamd` is receiving the cron error output by mail.
> 
> (Which we do not actually receive: it's delivered locally. The role should set an alias `_rspamd` → `root`, in `/etc/aliases`, no?)

That behaviour I cannot reproduce, the default setting in ``rspamd__dkim_update_default_configuration`` is to send emails to ``root`` ([see ``email_to`` here](https://docs.debops.org/en/v3.0.0/ansible/roles/rspamd/defaults/main.html#envvar-rspamd__dkim_update_method))

**Comment by Alphix** [comment]
@mathieumd : could you try PR #2160?

**Comment by mathieumd** [comment]
> which release are you using?

Ubuntu 22.04

> > So every first day of each months, the user `_rspamd` is receiving the cron error output by mail.
> > (Which we do not actually receive: it's delivered locally. The role should set an alias `_rspamd` → `root`, in `/etc/aliases`, no?)
> 
> That behaviour I cannot reproduce, the default setting in `rspamd__dkim_update_default_configuration` is to send emails to `root` ([see `email_to` here](https://docs.debops.org/en/v3.0.0/ansible/roles/rspamd/defaults/main.html#envvar-rspamd__dkim_update_method))

Yes, that is correct, but I am talking about the mail sent by cron, which runs as user `_rspamd` and therefore Cron send stderr output to that user email:

```
Return-Path: <_rspamd@host.example.com>
X-Original-To: _rspamd
Delivered-To: _rspamd@host.example.com
...
From: root@host.example.com (Cron Daemon)
To: _rspamd@host.example.com
Subject: Cron <_rspamd@host> /usr/local/sbin/rspamd-dkim-keygen
...
```

> @mathieumd : could you try PR #2160?

Looks good!

```bash
me@host:~$ sudo -u _rspamd /usr/local/sbin/rspamd-dkim-keygen 
me@host:~$ echo $?
0
```

Thanks.

**Comment by Alphix** [comment]
> > > So every first day of each months, the user `_rspamd` is receiving the cron error output by mail.
> > > (Which we do not actually receive: it's delivered locally. The role should set an alias `_rspamd` → `root`, in `/etc/aliases`, no?)
> > 
> > 
> > That behaviour I cannot reproduce, the default setting in `rspamd__dkim_update_default_configuration` is to send emails to `root` ([see `email_to` here](https://docs.debops.org/en/v3.0.0/ansible/roles/rspamd/defaults/main.html#envvar-rspamd__dkim_update_method))
> 
> Yes, that is correct, but I am talking about the mail sent by cron, which runs as user `_rspamd` and therefore Cron send stderr output to that user email:

Ah, gotcha. I'm using ``systemd-cron`` so didn't even consider those mails. I think that should be a separate issue though. I'll look into it.

> > @mathieumd : could you try PR #2160?
> 
> Looks good!
> 
> ```shell
> me@host:~$ sudo -u _rspamd /usr/local/sbin/rspamd-dkim-keygen 
> me@host:~$ echo $?
> 0
> ```
> 
> Thanks.

Great, thanks for testing the PR.

**Comment by Alphix** [comment]
The ``cron.d`` email issue is in issue #2162 now
