### ISSUE TITLE
dropbear_initramfs role missing in debops ansible-galaxy collection

### ISSUE THREAD

**Issue by jo-krk** [debops/debops#2216]
Hi,

I have fresh install of debops.debops:3.0.3 from ansible-galaxy and after defining roles paths in ansible.cfg:
```
roles_path = ~/my-debops/roles:~/.ansible/collections/ansible_collections/debops/debops/roles:~/.ansible/collections/ansible_collections/debops/roles01/roles:~/.ansible/collections/ansible_collections/debops/roles02/roles:~/.ansible/collections/ansible_collections/debops/roles03/roles
```
I'm still getting error that 'dropbear_initramfs' role is missing when running:
```
$ ansible-playbook ~/.ansible/collections/ansible_collections/debops/debops/playbooks/site.yml -l proxy-tests
```
Error:
```
ERROR! the role 'dropbear_initramfs' was not found in debops.debops:debops.roles01:debops.roles02:debops.roles03:ansible.legacy:/home/ansible/.ansible/collections/ansible_collections/debops/debops/playbooks/sys/roles:/home/ansible/my-debops/roles:/home/ansible/.ansible/collections/ansible_collections/debops/debops/roles:/home/ansible/.ansible/collections/ansible_collections/debops/roles01/roles:/home/ansible/.ansible/collections/ansible_collections/debops/roles02/roles:/home/ansible/.ansible/collections/ansible_collections/debops/roles03/roles:/home/ansible/.ansible/collections/ansible_collections/debops/debops/playbooks/sys

The error appears to be in '/home/ansible/.ansible/collections/ansible_collections/debops/debops/playbooks/sys/dropbear_initramfs.yml': line 23, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
```
while other roles are successfully found. I checked the specified paths myself and indeed - the 'dropbear_initramfs' role is not there, while it's in your git https://github.com/debops/debops/tree/stable-3.0/ansible/roles/dropbear_initramfs

At the same time, could you explain me relation between debops ansible-galaxy version and branches you use in git ? Is  'stable-3.0' in git represents code of debops.debops:3.0.0 in ansible-galaxy ?

Thanks

**Comment by stefangweichinger** [comment]
hitting this one also

**Comment by pescobar** [comment]
I am also hitting this problem with debops 3.0.3

**Comment by jo-krk** [comment]
Commenting out dropbear in _~/.ansible/collections/ansible_collections/debops/debops/playbooks/sys/all.yml_ :
```
...
#import_playbook: dropbear_initramfs.yml
```
works as workaround.

**Comment by jo-krk** [comment]
In debops 3.1.0 had to do the same (comment out dropbear) in `~/.ansible/collections/ansible_collections/debops/debops/playbooks/layer/sys.yml`
