### ISSUE TITLE
PKI acme-tiny isn't converting the intermediate cert to PEM correctly

### ISSUE THREAD

**Issue by Cadair** [debops/debops#2232]
I have two realms both using acme-tiny, and the `acme/intermediate.pem` certificate is not converted to the ascii-armoured PEM format correctly and therefore the chain and other files in `public/` are also broken.

**Comment by goetzk** [comment]
I believe #2198 should resolve this for you once merged.

**Comment by ypid** [comment]
Looks like the same as what I reported after you in #2250. #2250 has a bit more details so I close this issue. Hope that is ok for you.
