### ISSUE TITLE
Incompatibility with ansible-core 2.14: 'Unsupported parameters for (ansible.legacy.command) module: warn'

### ISSUE THREAD

**Issue by patatahooligan** [debops/debops#2247]
It seems that ansibe-core 2.14 has removed the `warn` as a parameter for `command`. I haven't found an announcement of the removal, but you can see it doesn't appear in the latest documentation [here](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html). Attempting to run a playbook which uses `warn` gives errors like the following.

```
TASK [debops.debops.sshd : Make sure the system-wide known_hosts file exists] ******
fatal: [local-vm]: FAILED! => changed=false 
  msg: 'Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: chdir, strip_empty_ends, executable, argv, stdin_add_newline, removes, creates, _raw_params, stdin, _uses_shell.'
```

If I understand correctly, `warn` can be plainly removed and no further action is necessary.

My versions that reproduce this

```
$ ansible --version
ansible [core 2.14.1]
$ debops --version
debops 3.0.3
```

I've checked and verified that `warn` is still used in current `master`. Downgrading ansible-core to 2.13.7 works with no errors or warnings.

**Comment by ypid** [comment]
Hi. Should be fixed by #2249. If that does not work for you feel free to comment.
