### ISSUE TITLE
debops.core role not found on fresh install

### ISSUE THREAD

**Issue by adituriya** [debops/debops#226]
Maybe my own ignorance, but I've had the same result each time I set up a new Debops controller. Basically Debops cannot run until I add `roles_path = /usr/local/lib/python2.7/dist-packages/debops/ansible/roles` to `.debops.cfg`.

How I got there:

1. Provision a new Debian stretch VPS
2. Create a `debops` user and grant NOPASSWD sudo access, login as that user
3. Install ansible from stretch-backports (version 2.4.3)
4. Install other deps listed on https://docs.debops.org/en/latest/user-guide/install.html
5. Install Debops globally with `sudo pip install debops`
6. Create a test project with `debops-init test`
7. `cd test` and run `debops`

Results in

```
ERROR! the role 'debops.core' was not found in /usr/local/lib/python2.7/dist-packages/debops/ansible/playbooks/service/roles:/home/debops/test/roles:/home/debops/test/ansible/roles:/home/debops/test/debops/ansible/roles:/roles:/nonexistent/roles:/etc/ansible/roles:/usr/local/lib/python2.7/dist-packages/debops/ansible/playbooks/service

The error appears to have been in '/usr/local/lib/python2.7/dist-packages/debops/ansible/playbooks/service/core.yml': line 13, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - role: debops.core
      ^ here
```

It works fine when I add the global debops roles path to the test project's `.debops.cfg`.

I realise there is a `debops.debops` role for setting up a new controller, however I thought this would be pretty straightforward to do manually (and I've never had this issue when using my laptop as a controller). Adding the line to `.debops.cfg` is easy, but seems like it shouldn't be necessary, and isn't documented anywhere. What am I missing?

**Comment by drybjed** [comment]
Sorry about that, this has been already fixed in the monorepo by https://github.com/debops/debops/commit/599520ee034f32803aa5e23362aa6e406a49ede5. I'm planning to release a new version near the end of March, then this issue should be solved in the package on PyPI.

**Comment by adituriya** [comment]
Ahh.. thanks so much for the reply!

**Comment by adituriya** [comment]
Confirmed - simply running `debops-update` fixes the issue. Thanks again.

**Comment by drybjed** [comment]
This will be fixed with the next release, therefore I'm closing this issue so that it does not block the milestone.
