### ISSUE TITLE
[sshd] "Include" isn't available on openssh-server sshd_config file on Debian 10

### ISSUE THREAD

**Issue by hungpr0** [debops/debops#2293]
Hello,

It seems `Include` isn't available on `sshd_config` of Debian 10 although Debian 11 doesn't complain about that.
Please check these articles:
https://stackoverflow.com/questions/43371489/ssh-config-line-1-bad-configuration-option-include
https://lists.debian.org/debian-user/2017/02/msg00096.html
https://www.openssh.com/txt/release-7.3

Tested with
```
ssh -V
OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1n  15 Mar 2022
```

Error message receive:
```
sudo sshd -t
/etc/ssh/sshd_config: line 12: Bad configuration option: Include
/etc/ssh/sshd_config: terminating, 1 bad configuration options
```

We should remove the line from the config
```
Include /etc/ssh/sshd_config.d/*.conf
```

**Comment by Alphix** [comment]
Indeed, in fact it's the only difference between the default `sshd_config` and the one currently in `sid`:

```
diff -u /home/david/buster-chroot/usr/share/openssh/sshd_config /usr/share/openssh/sshd_config
--- /home/david/buster-chroot/usr/share/openssh/sshd_config	2020-01-31 21:55:34.000000000 +0100
+++ /usr/share/openssh/sshd_config	2022-07-02 00:37:41.000000000 +0200
@@ -10,6 +10,8 @@
 # possible, but leave them commented.  Uncommented options override the
 # default value.
 
+Include /etc/ssh/sshd_config.d/*.conf
+
 #Port 22
 #AddressFamily any
 #ListenAddress 0.0.0.0
```

**Comment by Alphix** [comment]
@hungpr0: I've added a quick one-line PR (#2300), could you please test it?

**Comment by hungpr0** [comment]
@Alphix 
Sure. It works.
Thank you!
