### ISSUE TITLE
Overwrite the default editor

### ISSUE THREAD

**Issue by jankatins** [debops/debops#234]
(from https://github.com/debops/ansible-console/issues/46)

I've both vim and nano installed but want nano to be the default editor. I tried to do this in a var file:

```yaml
console_preferred_editors:
  - '/bin/nano'
```

But it seems this has not the desired effect that this is put in the first place of the list. would it be possible to add such a way?

**Comment by drybjed** [comment]
Agreed, the current design is not very flexible, the code that selects the active editor could be moved to a default variable so that it would be easier to set the preferred option.

I don't think that the editor selection needs a separate role, `debops.console` seems to be a good fit for now.

**Comment by jankatins** [comment]
Funnily I found a wa to overwrite the default editor (it's even described in https://docs.debops.org/en/latest/ansible/roles/debops.apt_install/defaults-detailed.html#id2):

```
apt_install__alternatives:
  - name: 'editor'
    path: '/bin/nano'
```

**Comment by drybjed** [comment]
Good find, I forgot that the alternatives can be configured in this role. It might be good idea to move the `editor` configuration there, I'll check it out.

**Comment by drybjed** [comment]
I checked if there's a way to change the `vim.basic` priority to be higher than `nano`, and there is, but Debian doesn't remember it after `vim` package is reinstalled. Bummer. I guess that editor will need to be selected manually, but I'll move the configuration to `debops.apt_install` - the role already installs `vim`, so the alternative selection at least will be in the same context.

**Comment by drybjed** [comment]
This should be covered by https://github.com/debops/debops/pull/280/commits/57fc54d98500eb204cd39c9ac2f4897307567585. @jankatins, can you check and confirm if it works for you?

**Comment by drybjed** [comment]
The functionality works without issues for some time now, closing the request as resolved.
