### ISSUE TITLE
Errors during creation of new LetsEncrypt account via acme.

### ISSUE THREAD

**Issue by Polichronucci** [debops/debops#242]
This is the actual error:
<pre>
$ cat /etc/pki/realms/REALM/acme/error.log             
Parsing account key...                                                         
Parsing CSR...                                                                 
Found domains: domain.ex                                            
Getting directory...                                                           
Directory found!                                                               
Registering account...                                                         
Traceback (most recent call last):                                             
  File "/usr/local/lib/pki/acme-tiny", line 197, in <module>                   
    main(sys.argv[1:])                                                         
  File "/usr/local/lib/pki/acme-tiny", line 193, in main                       
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/usr/local/lib/pki/acme-tiny", line 111, in get_crt                    
    account, code, acct_headers = _send_signed_request(directory['newAccount'], reg_payload, "Error registering")
KeyError: 'newAccount
</pre>

@egon0 found that this is an issue with the actual tiny-acme code. Telling the debops.pki role to use the tiny-acme version "4ed13950c0" fixes this issue.
<pre>pki_acme_tiny_version: '4ed13950c0'</pre>

**Comment by drybjed** [comment]
I suspect that Let's Encrypt with ACME v2 protocol now requires an explicit acceptance of terms and, maybe, a proper e-mail address for contact info. These could be added in `debops.pki` for `acme-tiny` support.

**Comment by drybjed** [comment]
This issue should be fixed by https://github.com/debops/debops/pull/250, can you check and confirm?

**Comment by isaiaholoyede** [comment]
@drybjed This is fixed for me. Thank you very much.

**Comment by ypid** [comment]
Can be closed I would say.
