### ISSUE TITLE
debops.docker: Unable to use the virtualenv

### ISSUE THREAD

**Issue by roddhjav** [debops/debops#243]
Hi,

After the installation of docker (from upstream) with `debops.docker`, I have tried to use Ansible modules to interact with Docker as explained in the [doc](https://docs.debops.org/en/latest/ansible/roles/debops.docker/docker-virtualenv.html#ansible-modules-and-docker-virtualenv). However, when I run the example [playbook](https://github.com/debops/debops/blob/master/docs/ansible/roles/debops.docker/examples/docker-redis.yml), I got the following error: 
```
TASK [Manage redis container] **************************************************************************
fatal: [test]: FAILED! => {"changed": false, "msg": "Failed to import docker-py - cannot import name NotFound. Try `pip install docker-py`"}
```

I have checked, docker-py is installed in the virtualenv, and the `ansible_python_interpreter` should be  set to  `/usr/bin/env docker-python`.

**Meta**
* Ansible version: `2.4.3.0`
* Python version (on the host): `2.7.14`
* Host: `archlinux`
* Test VM: `debian 9`

**Comment by drybjed** [comment]
Can you find the `docker-python` command in `$PATH`? It should be a symlink in `/usr/local/bin`, created by the role.

What if you change the `ansible_python_interpreter` to the `python` script inside of the virtualenv, does that make the playbook work?

**Comment by roddhjav** [comment]
Yes `docker-python` is in `$PATH` and the symlink is correct:
``` 
$ type docker-python
docker-python is /usr/local/bin/docker-python
```
With: `/usr/local/bin/docker-python -> /usr/local/lib/docker/virtualenv/bin/python`

I tried with `ansible_python_interpreter: '/usr/local/lib/docker/virtualenv/bin/python'` in the playbook; however, the error is the same.

**Comment by drybjed** [comment]
I just tested this setup in my own environment:

- Ansible Controller: Debian Jessie
- remote host: Debian Stretch
- Docker version 17.12.1-ce, build 7390fc6
- Ansible version 2.5.0rc3

And it apparently works fine with the example playbook, got the `redis` container running.

**Comment by roddhjav** [comment]
I have done a few test, it seems the `ansible_python_interpreter` variable does not do anything.

I added to the playbook:
``` 
 - name: Test Docker Python
   command: /home/vagrant/test.py
```

With in /home/vagrant/test.py to test the virtualenv:
```
#!/usr/bin/env python
import docker
c = docker.Client()
print(c.info())
```

When the env is `docker-python` it works fine, but as expected, when it's `python`, it does not. So the everything seems to be set up correctly but Ansible is not able to use `docker-python` as env.

Edit: I tested it with the last Ansible version, same result.

**Comment by roddhjav** [comment]
I have news here,  as you said, it works on a default debops config, I tested it with a new config (generated with debops-init) and with an empty inventory with only the following variables  set:
```
docker__upstream: True
docker__tcp: False
```

It works!. However, if I add, `docker__ferment: True` then it does not work, and I have the same error. So the source cause of my error was `docker__ferment: True`.

**Comment by drybjed** [comment]
The `ferment` script is not used with upstream Docker releases. What OS release are you using? Upstream Docker should be automatically enabled on Debian Stretch.

**Comment by roddhjav** [comment]
I use Debian Stretch; therefore it can explain the error. Thank for the help, it was very helpful.
