### ISSUE TITLE
ubuntu noble removes /etc/apt/sources.list file 

### ISSUE THREAD

**Issue by ser** [debops/debops#2454]
Ubuntu Noble 24.04 removes completely ` /etc/apt/sources.list ` and replaces it with `/etc/apt/sources.list.d/ubuntu.sources` in deb822 style. It must be accommodated into debops.

**Comment by goetzk** [comment]
v3.1.0 includes support for deb822 format https://docs.debops.org/en/stable-3.1/news/changelog.html#debops-v3-1-0-2023-11-29; hopefully that works for you.

**Comment by ser** [comment]
Yes deb822 format works well, but support is not enough to overcome the fact that debops playbooks are not ready to handle lack of `/etc/apt/sources.list` file and create it anyway.

**Comment by tripleo1** [comment]
Being nosy/correct me if I'm wrong, isn't that an ansible problem?

**Comment by drybjed** [comment]
I'm downloading Ubuntu Noble image at the moment to see how Ansible works in the new environment (distribution and release detection, for example). I update the role to handle the change after testing.

**Comment by drybjed** [comment]
@ser: I installed current Ubuntu Noble image, and it contains the `/etc/apt/sources.list` file, there's no `/etc/apt/sources.list.d/ubuntu.sources` present. Did something change, was the decision reverted? Do you know if there's a discussion somewhere about this change?

**Comment by ser** [comment]
OK, I am really sorry for this false report, it seems these were bugs in ubuntu and cloud-init which now are resolved:

https://github.com/canonical/cloud-init/issues/4691
