### ISSUE TITLE
debops.apache2 Add apache__*packages lists

### ISSUE THREAD

**Issue by gardouille** [debops/debops#246]
I think it might be useful (at least for me…) and allow this role to have the same behaviour/variables like almost other DebOps's roles.

In my case, i already use **apache__packages** in debops_service_php group_vars to automatically add _libapache2-mod-php_. And on another host i also need _libapache2-mod-perl2_.

**apache__group_packages** and **apache__host_packages** will be perfect.

**Comment by drybjed** [comment]
Sounds good to me. Want to create a PR with these additions?
