### ISSUE TITLE
nginx: add option for global ssl config 

### ISSUE THREAD

**Issue by jankowa** [debops/debops#266]
In my opinion it would be helpful to have the possibility to configure ssl configuration inside nginx.conf directly and not only inside the specific server configurations.

This e.g. would not only help to deploy also site-configurations not managed with ansible/debops but also define consistent ssl configurations which still can be overwritten by individual site configurations.

Maybe something like this?

```
--- a/ansible/roles/debops.nginx/templates/etc/nginx/nginx.conf.j2
+++ b/ansible/roles/debops.nginx/templates/etc/nginx/nginx.conf.j2
@@ -8,6 +8,7 @@ pid {{ nginx_run_path }}/nginx.pid;
 
 include /etc/nginx/modules-enabled/*.conf;
 
+
 # Default error_log
 error_log {{ nginx_http_error_log | default(nginx_log_path + '/error.log') }};
 
@@ -39,6 +40,16 @@ http {
         server_names_hash_bucket_size {{ nginx_http_server_names_hash_bucket_size | default('64') }};
         server_names_hash_max_size {{ nginx_http_server_names_hash_max_size | default('512') }};
 
+{% if nginx_http_ssl_config is defined and nginx_http_ssl_config | bool %}
+        # global ssl configuration
+        ssl_protocols             {{ nginx_default_tls_protocols | join(" ") }};
+        ssl_prefer_server_ciphers on;
+        ssl_ciphers               {{ nginx_ssl_ciphers[nginx_default_ssl_ciphers] }};
+        ssl_dhparam               {{ nginx_ssl_dhparam }};
+        ssl_ecdh_curve            {{ nginx_default_ssl_curve }};
+{% endif %}
+
+
 {% if nginx_http_options|d() and nginx_http_options %}
 {{ nginx_http_options | indent(8, true) | regex_replace("(?m)^\s*$", "") }}

```

or is it better to place it in the defaults/main.yml near by nginx_http_options?

Meanwhile I help myself with:
```

nginx__custom_config:
  - name: 'ssl-config'
    custom: |
        ssl_protocols             {{ nginx_default_tls_protocols | join(" ") }};
        ssl_prefer_server_ciphers on;
        ssl_ciphers               {{ nginx_ssl_ciphers[nginx_default_ssl_ciphers] }};
        ssl_dhparam               {{ nginx_ssl_dhparam }};
        ssl_ecdh_curve            {{ nginx_default_ssl_curve }};

```

**Comment by drybjed** [comment]
Sounds good to me, although I'd aim for a slightly different approach. Debian `nginx` packages introduced the `/etc/nginx/snippets/` directory, `debops.nginx` uses it currently to store the ACME challenge configuration which is then included in the server configuration files. I would do the same with the base SSL configuration which would be then included in the server configuration. I suspect that individual options could then be overridden from the `server { }` section itself, although I'm not sure if that works as expected.

Currently snippets [are configured via a task](https://github.com/debops/debops/blob/master/ansible/roles/debops.nginx/tasks/main.yml#L152-L161), exposing this through role default variables could be useful. You could define your own snippets in addition to the ones defined by the role, multiple variables could be merged together using `parse_kv_items` filter plugin, similarly to how for example `debops.sysctl` configuration is currently managed.

**Comment by drybjed** [comment]
Ah, you want to include it in the `/etc/nginx/nginx.conf` file directly? I'm not sure if that's a good idea, some of the services managed by DebOps, for example reprepro or preseeding configuration, rely on a plain HTTP service being present. Wouldn't setting SSL options in the main configuration file result in issues with that? I'm not sure, never tried it. I think that including a snippet in relevant server sections is better.

**Comment by drybjed** [comment]
This should be partially fixed by https://github.com/debops/debops/pull/269/commits/8cd380ae139c42e5780063fe1b9cb8e25dbf6325. The snippet is not currently included in the generated configuration files because `nginx` complains about duplicate parameters.
