### ISSUE TITLE
librenms: add variable base_url

### ISSUE THREAD

**Issue by stefangweichinger** [debops/debops#267]
Request to add the config.php-parameter

```
$config['base_url'] = "http://demo.librenms.org";
```

as variable. This helps to run LibreNMS behind a reverse proxy (webserver w/ librenms runs http only).

I'll try to provide the PR, this issue just as "reminder". Maybe even a short example for this in the docs?

**Comment by drybjed** [comment]
I'm gonna do a quick patch, so it gets in the next release. Stay tuned.

**Comment by stefangweichinger** [comment]
I somehow expected this ;-) thanks, great.
