### ISSUE TITLE
Cannot Use ACME When Installing Nextcloud

### ISSUE THREAD

**Issue by schrieveslaach** [debops/debops#275]
Hi, 

when I'm installing nextcloud through debops I ran twice into the issue that ACME cannot issue a letsencrypt certificate. Here is the log. 

```
Parsing account key...
Parsing CSR...
Found domains: example.com
Getting directory...
Directory found!
Registering account...
Registered!
Creating new order...
Order created!
Verifying example.com...
Traceback (most recent call last):
  File "/usr/local/lib/pki/acme-tiny", line 197, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/pki/acme-tiny", line 193, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/usr/local/lib/pki/acme-tiny", line 134, in get_crt
    with open(wellknown_path, "w") as wellknown_file:
IOError: [Errno 13] Permission denied: u'/srv/www/sites/acme/public/.well-known/acme-challenge/<challange-file-name>'
```

The directory `/srv/www/` access mask is 750 which is the reason for that permission denied error. If I change this to 755, the user `pki-acme` is able to create files in `/srv/www/sites/acme/public/.well-known/acme-challenge/`. 

BTW: How can I trigger an ACME renewal manually?

**Comment by drybjed** [comment]
Thanks for the report, it seems that somewhere the `/srv/www/` directory is created incorrectly. I'll try to find it out, @ypid would also be interested.

To trigger the ACME renewal just remove the entire `/etc/pki/realms/<realm>/` directory and re-run the `debops.pki` role, that should do the trick.

**Comment by ypid** [comment]
Thanks for reporting, #277 contains a fix for this. I never noticed the issue because have the data directory on a separate mount point.

**Comment by drybjed** [comment]
@ypid Thanks for finding this, any idea when #277 will be ready for merge? I guess a separate role that could prepare a webserver environment ie. create `/srv/www/sites` and the `webmasters` UNIX group could be useful, so that these are not duplicated between multiple roles. That's for the future though.

**Comment by ypid** [comment]
I plan to check it out and get back to you ~Wednesday~ someday on the weekend. Should be ready, at least considering the functionality.
