### ISSUE TITLE
debops.console remounting of /proc fails on lxc-container

### ISSUE THREAD

**Issue by jankowa** [debops/debops#28]
If the target host is an lxc-host the common playbook fails on the role debops.console. Remounting of /proc with "hidepid" option fails with read-only filesystem error.

The solution could be - as far as I understand - to check for lxc and either don't apply the hidepid option - or don't remount the /proc. For the latter we would wait for restarting lxc.

I don't know much about ansible but I think, not to apply hidepid on lxc could be achieved by following patch:

```yml
--- main.yml.orig	2017-11-05 18:29:16.995788357 +0100
+++ main.yml	2017-11-05 18:30:34.000000000 +0100
@@ -105,9 +105,10 @@
 
   # Enable hidepid= only on specific hosts
 - include: proc_hidepid.yml
-  when: (ansible_local|d() and ((ansible_local.root|d() and 'ignore-cap12s' in ansible_local.root.flags) or
-         (ansible_local.cap12s|d() and (not ansible_local.cap12s.enabled | bool or
-          (ansible_local.cap12s.enabled | bool and 'cap_sys_admin' in ansible_local.cap12s.list)))))
+  when: ( ansible_virtualization_type not in [ "lxc", "openvz" ] and 
+        (ansible_local|d() and ((ansible_local.root|d() and 'ignore-cap12s' in ansible_local.root.flags) or
+        (ansible_local.cap12s|d() and (not ansible_local.cap12s.enabled | bool or
+        (ansible_local.cap12s.enabled | bool and 'cap_sys_admin' in ansible_local.cap12s.list))))))
 
 - name: Make sure that Ansible fact directory exists
   file:
```

for having "hidepid" in fstab but not remount /proc in proc_hidepid.yml we maybe instead have to ensure to restart the whole container.

But the following does not work on debian. It's remounted anyway - but what is responsible for remounting? The remount should only should match on ubuntu. But on debian it's remounted anyway - but where the remount command is executed?

```yml
--- proc_hidepid.yml.orig	2017-10-29 20:58:18.000000000 +0100
+++ proc_hidepid.yml	2017-11-05 23:03:23.103390032 +0100
@@ -24,8 +24,9 @@
     line: 'mount -o remount,hidepid={{ console_proc_hidepid_level }},gid={{ console_proc_hidepid_group }} /proc'
     insertbefore: 'exit 0'
     state: 'present'
-  when: ((console_proc_hidepid is defined and console_proc_hidepid) and
-         (ansible_distribution in [ 'Ubuntu' ] and ansible_distribution_release in [ 'trusty' ]))
+  when: (ansible_virtualization_type not in [ "lxc", "openvz" ]) and
+        ((console_proc_hidepid is defined and console_proc_hidepid) and
+        (ansible_distribution in [ 'Ubuntu' ] and ansible_distribution_release in [ 'trusty' ]))
 
 - name: Create the systemd-logind configuration directory
   file:

```

Similar issue exists for debops.sysctl and the  shared memory options.

**Comment by drybjed** [comment]
This is probably due to the `cgroup` changes in the kernel, [this thread](https://github.com/debops/ansible-lxc/issues/15) probably also can provide some context. The `hidepid` stuff could probably be moved to a separate role at this point, that could make the activation code simplier.

BTW, did you check this on Debian Jessie, or on Debian Stretch? Jessie for me works just fine, but Stretch fails. Due to this I plan to remove the `hidepid` support from the `debops.lxc` role as well. I wonder if the Linux kernel from `stretch-backports` (the `linux-image-amd64` package) would fix some of the LXC issues...

**Comment by jankowa** [comment]
I tried it only on stretch but not yet with backport kernel.

**Comment by drybjed** [comment]
The hidepid functionality has been moved to a separate role, `debops.proc_hidepid` which should allow easy control over this feature. By default this functionality should be disabled inside an LXC container. I'm closing this thread as resolved.

**Comment by danielo515** [comment]
I'm having this very da e problem on a UBUNTU lxc container. Was this fixed? Maybe is a problem with my ansible not gathering facts correctly?
