### ISSUE TITLE
debops.apache ``index`` parameter is referenced but non-usable

### ISSUE THREAD

**Issue by gardouille** [debops/debops#288]
The documentation present ``index`` parameter https://docs.debops.org/en/latest/ansible/roles/debops.apache/defaults-detailed.html#common-webserver-options

But i can't find it in the debops.apache code.

**Comment by ypid** [comment]
You are right. The documentation was taken from the debops.nginx role and most of the parameters where implemented. Seems that one was missed by me.

**Comment by gardouille** [comment]
Thanks :)
