### ISSUE TITLE
Redis - Option to install from file

### ISSUE THREAD

**Issue by thiagotalma** [debops/debops#326]
Is there any chance of being implemented an option to install Redis Server by the ["official" installation method](https://redis.io/download), using the latest stable (or some specific release) file?  😉

**Comment by drybjed** [comment]
I would say, no. Redis upstream publishes unsigned tarballs, I don't see any mention of GPG signing anything. Redis developers publish [a repository with hashes of published tarballs](https://github.com/antirez/redis-hashes) but again, commits aren't signed, and there's no tags.

I don't see a sane way to automatically authenticate the upstream Redis tar packages, sorry.

if all you want is a newer Redis version, `stretch-backports` repository has [Redis 4.0.7 packages](https://packages.debian.org/pl/stretch-backports/redis-server) available. The backports repository is fair game in DebOps, and automatically enabled by `debops.apt` role. All you need to do is to tell APT to prefer `redis-server` and all of the related packages from `stretch-backports`, and `debops.redis` should happily install it for you. I have no idea if the newer version will be compatible with the configuration maintained by the role, you will need to check that yourself.

**Comment by thiagotalma** [comment]
I understand perfectly and I give you the reason.
No reliability, no business.

Thank you very much!!
