### ISSUE TITLE
[debops.sshd] using role standalone might lock you out of systems

### ISSUE THREAD

**Issue by FloRinke** [debops/debops#333]
After pulling the latest updates I got locked out of systems via ssh, because all groups except 'root' had been removed from sshd_config/AllowGroups.

Apparently the recent change to derive AllowGroups from local facts depends on debops.system_groups being also used, which I don't.

I suggest, this dependency should at least be mentioned in the documentation (e.g. in the example playbook). A check, if those facts are actually available, would also trigger if you don't read the whole documentation for all roles at every update and should be in line with ansible's "fail fast" philosopy.

**Comment by drybjed** [comment]
Agreed, leaving only `root` able to login can lead to lockouts. How about this then - if the `debops.system_groups` facts are not available, don't set `AllowGroups` by default at all? This way all accounts should be able to login. I'll look into that.
