### ISSUE TITLE
Status of debops.apache in Galaxy

### ISSUE THREAD

**Issue by mathieumd** [debops/debops#338]
The role [Apache](https://github.com/debops/debops/blob/master/ansible/roles/debops.apache/) has not been updated in [Galaxy](https://galaxy.ansible.com/debops/apache/) since 10 months.

I was particularly looking for the fix for https://github.com/debops/debops/issues/246 ([Galaxy](https://github.com/debops/ansible-apache/blob/master/tasks/main.yml#L18) vs. [Debops](https://github.com/debops/debops/blob/master/ansible/roles/debops.apache/tasks/main.yml#L18)).

Is it only a omission, or are there any changes since all roles are sync in main debops repo?

**Comment by drybjed** [comment]
Currently old roles in separate `git` repositories are not updated. The Ansible Galaxy team is planning to introduce support for multiple Ansible roles in a single repository at some point, and I'm waiting for that. When that happens, DebOps monorepo will be published on Galaxy and the old roles on GitHub will be archived.

For now I would suggest that you clone the DebOps monorepo (if you don't want to use the tooling) and add a path to `ansible/roles/` in the Ansible configuration file, `roles_path` parameter. That way you can use the DebOps roles from the monorepo in your own projects.

**Comment by mathieumd** [comment]
Thanks.
