### ISSUE TITLE
getting-started site does not exists

### ISSUE THREAD

**Issue by kmonticolo** [debops/debops#341]
https://docs.debops.org/en/latest/debops-playbooks/docs/guides/getting-started.html mentioned in readme and in the inventory does not exists.

**Comment by drybjed** [comment]
Right, thanks for the issue report. The link should point to https://docs.debops.org/en/master/debops-playbooks/guides/getting-started.html. Previously it was correct when the old version of the documentation was deployed at docs.debops.org, and after the new version built from the monorepo was implemented, this was not updated.

**Comment by kmonticolo** [comment]
Thanks Maciek for pointing me the right link. And I'd like to say big "thank you" for your great effort. Appreciate that.

**Comment by drybjed** [comment]
Thanks! As you can see, still a work in progress, but we are getting there. :-)
