### ISSUE TITLE
etc_aliases fails (under Python 3?)

### ISSUE THREAD

**Issue by Cadair** [debops/debops#353]
I am getting the following (very helpful) error while trying to use the etc_aliases role from Arch running ansible under Python 3. I can't work out the correct command to get the full traceback for this error:
```

TASK [debops.etc_aliases : Generate the /etc/aliases file] ************************************************************************************************************************************************************************************
fatal: []: FAILED! => {"changed": false, "msg": "NameError: name 'unicode' is not defined"}
```

```
ansible 2.5.3
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
```

**Comment by drybjed** [comment]
Hmm, not sure what could cause this, but it's probably something in the template. You could try and debuig it by "bisecting" the template file - remove almost everything and run the role, then add bits back until the error shows up. Then you will know what might trigger it.

**Comment by Cadair** [comment]
Well that was easy, looks like it was the first line:
```
{% set etc_aliases__tpl_filtered_recipients = (etc_aliases__combined_recipients | etc_aliases__parse_recipients) %}  
```

**Comment by drybjed** [comment]
So I guess it's the custom filter included in the role.

**Comment by Cadair** [comment]
Yeah looks like it's this: https://github.com/debops/debops/blob/master/ansible/roles/debops.etc_aliases/filter_plugins/etc_aliases__parse_recipients.py#L67

Are you using `six` or similar to handle things like this?

**Comment by drybjed** [comment]
No, I try to avoid it. You can look at the `debops.ansible_plugins` role to see how it was done there.
