### ISSUE TITLE
[debops.etherpad] SHA512 hashed passwords of non-admin users do not work

### ISSUE THREAD

**Issue by myrdd** [debops/debops#373]
The following line contains a bug:

https://github.com/debops/debops/commit/1dfe715b6b06481c6dde0dc63d232f10c064e123#diff-d5173f06d4a7743bf3ff160cc2b97481R146

```
      "hash": "{{ lookup('pipe', 'printf "%s\n" "' + lookup('password', secret + '/credentials/' + inventory_hostname + '/etherpad/users/' + name) + '" | sha512sum | cut -f1 -d" "') }}",
```

`printf "%s\n"` should be `printf "%s"`

The line for admin users ([line 136](https://github.com/debops/debops/commit/1dfe715b6b06481c6dde0dc63d232f10c064e123#diff-d5173f06d4a7743bf3ff160cc2b97481R136)) is correct.

This should be very easy to fix.

**Comment by drybjed** [comment]
Thanks, fix should be merged shortly.
