### ISSUE TITLE
greenfield installation on ubuntu 16.04 fails to build python-ldap

### ISSUE THREAD

**Issue by fermulator** [debops/debops#385]
was following https://docs.debops.org/en/master/user-guide/install.html#ansible-controller

```
$ cat /etc/issue
Ubuntu 16.04.4 LTS
```

Had completed dependency requirement for ansible, and was going the python venv route
https://docs.debops.org/en/master/user-guide/install.html#installation-in-a-python-virtualenv

_did_ note the "additional software" mentioned here, https://docs.debops.org/en/master/user-guide/install.html#additional-software, however since none seemed to apply to my scenario (yet), I ignored it

at the step
`pip install ansible debops`, things failed on python-ldap ;/

[debops_python-ldap_failure.txt](https://github.com/debops/debops/files/2174506/debops_python-ldap_failure.txt)

```
  Failed building wheel for python-ldap

Command "/home/fermulator/debops-venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-NyipaL/python-ldap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3BFRqO/install-record.txt --single-version-externally-managed --compile --install-headers /home/fermulator/debops-venv/include/site/python2.7/python-ldap" failed with error code 1 in /tmp/pip-install-NyipaL/python-ldap/
```

Quickly was able to uncover: https://stackoverflow.com/questions/4768446/i-cant-install-python-ldap#4768467

And resolved with workaround:
```
sudo apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev
```

----
need input if this dependency is expected, and if so, I can update the documentation as appropriate (once confirmation from owners, either fix yourselves or assign to me w/ relevant information and I'll submit a fix to the docs)

**Comment by drybjed** [comment]
Agreed, this is an oversight on my part. The `python-ldap` requirement was added kind of a last minute when one of the Travis tests failed without it. When you install the requirements via APT, installing the `-dev` packages is not necessary, but if you go with the virtualenv, the `python-ldap` install requires them.

Thanks for offering fixing the documentation, looking forward to it.

**Comment by drybjed** [comment]
This issue should be fixed by https://github.com/debops/debops/pull/390, closing.
