### ISSUE TITLE
Configure upstreams with role::nginx:servers

### ISSUE THREAD

**Issue by AlMaVizca** [debops/debops#410]
https://github.com/debops/debops/blob/3df212dea10325fc198d4764acd2204368743cd7/ansible/roles/debops.nginx/tasks/main.yml#L235

is it worth it to add the tag `role::nginx:servers` to setup the upstreams? or would it add another unwanted configurations?

Thanks in advance

**Comment by drybjed** [comment]
Sounds good. I added the tag for maps and upstreams.

**Comment by AlMaVizca** [comment]
Thank you very much :+1:
