### ISSUE TITLE
[debops.owncloud] Archive PGP key expired

### ISSUE THREAD

**Issue by sread** [debops/debops#426]
Hi, the key specified in 

https://github.com/debops/debops/blob/d05a7d949b104ea279e0779b6849ac2307ac518a/ansible/roles/debops.owncloud/tasks/system_package_management.yml#L26

expired on 2018-08-25, causing task "[debops.owncloud : Add ownCloud APT OpenPGP public key]" to fail.

**Comment by drybjed** [comment]
Thanks for the heads up. The role installs Nexcloud by default, that's why it was not picked up in the CI.
