### ISSUE TITLE
[debops.nginx] allow "/.well-known/"

### ISSUE THREAD

**Issue by myrdd** [debops/debops#428]
Suggestion: Change

```
        location ~ /\. {
                return 404;
        }
```

to

```
        location ~ /\.(?!well-known/) {
                return 404;
        }
```

in `ansible/roles/debops.nginx/templates/etc/nginx/sites-available/default.conf.j2`

See also:

- https://www.mnot.net/blog/2010/04/07/well-known
- https://tools.ietf.org/html/rfc5785
- https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers

**Comment by drybjed** [comment]
Sounds good to me. Want to make a PR with the change?

**Comment by myrdd** [comment]
Sure.
