### ISSUE TITLE
[debops.gitlab] needs to install 'git'

### ISSUE THREAD

**Issue by myrdd** [debops/debops#438]
`gitlab__base_packages` is missing the `'git'` package:

https://github.com/debops/debops/blob/4ea3e81a71bd16418cdb4b5a9494d8eaefcdae97/ansible/roles/debops.gitlab/defaults/main.yml#L124-L127

needed for cloning Gitlab CE:

https://github.com/debops/debops/blob/4ea3e81a71bd16418cdb4b5a9494d8eaefcdae97/ansible/roles/debops.gitlab/tasks/download_gitlab_ce.yml#L13

btw, what's the way the package names should be ordered?

**Comment by drybjed** [comment]
Sounds good, can you create a PR?

There's no special rules for ordering package names. If you want to reorder them alphabetically, go ahead.
