### ISSUE TITLE
[debops.owncloud] Nginx deny_hidden breaking chunked upload in Nextcloud

### ISSUE THREAD

**Issue by alo-is** [debops/debops#469]
Hi,

It seems that this block : 

https://github.com/debops/debops/blob/7cbc3df22718e4d379cab0814659454faf6f40ed/ansible/roles/debops.owncloud/defaults/main.yml#L1880-L1897

is missing `deny_hidden: False`, since Nextcloud is using URLs ending with `.file` with the desktop client & the webapp for large files (dav & chunked upload) :

```
MOVE /remote.php/dav/uploads/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/1234567890/.file HTTP/1.1" 404 4194 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)
```

Removing the following block from my Nginx config fixed the issue :

```
        # Disallow access to hidden files and directories
        location ~ /\. {
                return 404;
        }
```

**Comment by drybjed** [comment]
Thanks for the bug report! Do you want to make a PR with the fix?

**Comment by ypid** [comment]
Related to: https://github.com/debops/ansible-owncloud/issues/87

I have not tested this. @drybjed, if you think it is ok, you can merge. I will do my research when I upgrade my Nextcloud instances.

**Comment by alo-is** [comment]
Yup, same problem as mentioned here debops/ansible-owncloud#87. Also tried with Nextcloud 14, same outcome.
