### ISSUE TITLE
Dokuwiki lacks php-xml package

### ISSUE THREAD

**Issue by mflis** [debops/debops#487]
After installing dokuwiki  according to instructions in  [getting started guide](https://docs.debops.org/en/latest/debops-playbooks/guides/getting-started.html#example-application-dokuwiki) and going to `.../install.php` to finish installation page shows:

>The installer found some problems, indicated below. You can not continue until you have fixed them.
>
>    PHP function utf8_encode is not available. Maybe your hosting provider disabled it for some reason?
>    PHP function utf8_decode is not available. Maybe your hosting provider disabled it for some reason?

Dokuwiki describes solution to this problem in [requirements page](https://www.dokuwiki.org/requirements):
> PHP 7.0 installation (on Ubuntu 16.04 or debian 9) need the php-xml package installed. (Fixes error: Uncaught Error: Call to undefined function utf8_decode() )

Manually installing package by apt solved issue.  It would be nice to add this package to defaults installed along with dokuwiki.

Background info:
- system: Debian 9
- debops version: 0.8.0 (through `pip`)
- python version: 2.7.15

**Comment by drybjed** [comment]
Thanks, just confirmed that it happens on Stretch. Fix will be merged shortly.
