### ISSUE TITLE
`postgresql__delegate_to` incorrect (?)

### ISSUE THREAD

**Issue by myrdd** [debops/debops#510]
correct me if I'm wrong, but I think the `or not` part as well as `omit` in the `postgresql__delegate_to` definition are incorrect:

https://github.com/debops/debops/blob/16dfbc21ac91b86833a4124db86368c5876b0b74/ansible/roles/debops.postgresql/defaults/main.yml#L92-L95

and should be rather like `mariadb__delegate_to`:

https://github.com/debops/debops/blob/16dfbc21ac91b86833a4124db86368c5876b0b74/ansible/roles/debops.mariadb/defaults/main.yml#L48-L51

that is, remove the `or not` branch of the condition and replace `omit` by `inventory_hostname`.

Many thanks for creating and maintaining debops!

**Comment by drybjed** [comment]
I think that you are correct. This change was intended to make task delegation conditional, but doing it using `omit` will most likely mess up the `debops.postgresql` facts. I'll test this to be sure what happens.
