### ISSUE TITLE
acl required but not installed (debops.gitlab, debops.users)

### ISSUE THREAD

**Issue by myrdd** [debops/debops#517]
Some roles use the `acl` ansible module:

```
> rgrep -l 'acl:' ansible/roles/*/tasks/
ansible/roles/debops.gitlab/tasks/main.yml
ansible/roles/debops.users/tasks/users.yml
```

but ~`apt`~ `acl` is installed only in these roles:

* `debops.apt_install`
* `debops.pki`
* `debops.preseed`

IMHO this is an issue. Still, I could simply put `debops.apt_install` at the top of each playbook. How should this be solved? :)

**Comment by drybjed** [comment]
I suppose that adding `acl` pacakge to each of the roles that uses the `acl` Ansible module is a good way to solve it. In that case the support is required, and installing `acl` shouldn't affect the system in any significant way. Want to make the PR? You can add it in all the roles that need it at once.

I guess this would require adding the `users__packages` and `users__base_packages` to the `debops.users` role along with the `apt` task.
