### ISSUE TITLE
debops.php/env not installed from galaxy

### ISSUE THREAD

**Issue by themouette** [debops/debops#534]
i just tried to installed `debops.php` and the example playbook for `owncloud` uses `php/env` role.

In my local installation (`ansible-galaxy install debops.php`), the `env` directory is not available.

**Comment by drybjed** [comment]
The installation via Ansible Galaxy is non-functional. Galaxy understands the layout of the DebOps monorepo (it interprets everything correctly, it seems), but the `ansible-galaxy` and `mazer` tools don't support monorepos correctly. You can see that inside of the installed role theire's `debops-v0.8.0/` subdirectory with contents of the entire repository.

I would suggest that you should install DebOps repository directly from GitHub. Then you can point Ansible to the roles by setting:
```
roles_path = path/to/debops/ansible/roles:/etc/ansible/roles
```
in the `ansible.cfg`. That should make things work as expected.

**Comment by themouette** [comment]
Thank you for the quick answer.
I'll do that :)
