### ISSUE TITLE
Vagrant: docs to use environment variable

### ISSUE THREAD

**Issue by nqb** [debops/debops#542]
Hello @drybjed,

I didn't find documentation on Vagrant usage for DebOps.

I read the Vagrantfile and didn't understand where you set up env variables, maybe like this:
```
export APT_HTTP_PROXY=http://10.0.0.1:3142
```
or did you use other tools ?

Thanks for your help.

**Comment by drybjed** [comment]
@nqb Sorry, the whole test pipeline is currently undocumented.

Yes, the variables in the `Vagrantfile` are taken from the current environment. The line you proposed should work fine, alternatively you can do it by hand like this:
```
APT_HTTP_PROXY=http://10.0.0.1:3142 vagrant up
```
The DebOps `Vagrantfile` is written more to be used by the Jane script (`lib/tests/jane`), but it should be also usable by hand, if you want to try out DebOps yourself.

**Comment by nqb** [comment]
Thanks for you quick reply.
