### ISSUE TITLE
Postfix can not connect to opendkim

### ISSUE THREAD

**Issue by alinalexandru** [debops/debops#551]
It seems that the socket path are not the same in postfix and opendkim

I made the following change in `/etc/default/opendkim`
```
old
#SOCKET="local:/var/run/opendkim/opendkim.sock"
new
SOCKET="local:/var/spool/postfix/opendkim/opendkim.sock"
```

I had this problem on  ubuntu 16 and ubuntu 18

**Comment by drybjed** [comment]
On Debian it seems that's not an issue, so only Ubuntu related. And you also created https://github.com/debops/ansible-opendkim/issues/6 in the `debops.opendkim` repository.

I guess managing the `/etc/default/opendkim` configuration file by the role is inevitable then. I'll look into it in a few days, looks like it will have to be diverted as well.
