### ISSUE TITLE
[infra] debops.org self signed cert 

### ISSUE THREAD

**Issue by mikenowak** [debops/debops#579]
Not necessary related to debops project per say, but more of the infrastructure consideration.

I noticed that starting this morning, debops.org, doc.debops.org present a self signed certificate, which of course produces a warning in any web browser.

```
$ openssl s_client -connect debops.org:443
CONNECTED(00000005)
depth=1 O = Debops, OU = Domain CA
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/CN=cornell.debops.org
   i:/O=Debops/OU=Domain CA
 1 s:/O=Debops/OU=Domain CA
   i:/O=Debops Certificate Authority
---
```

**Comment by drybjed** [comment]
Thanks, fixed. It seems that the `pki-realm` script could check if ACME request resulted in an error, and send the `error.log` file to the administrator. The issue was on the ACME server-side, maybe some work during the request, on 2nd of December; the certs were valid until yesterday.
