### ISSUE TITLE
Bootstrap: Variables from group_vars/all/bootstrap.yml not getting picked up

### ISSUE THREAD

**Issue by zenflip** [debops/debops#586]
Hi -

I've been trying for a few hours to get a bootstrap project going using a Vultr cloud server as per instructions here:
https://docs.debops.org/en/latest/ansible/roles/debops.bootstrap/getting-started.html

I expected to provide the password to the debops bootstrap command (see below) and to have my domain name change from ubuntu1 to ubuntu1.tc.test.com.

It doesn't, no matter what I try.

suggestions welcome.

----

macOS: 10.14.1
Python: 3.7.1
Ansible: 2.7.5
pipenv (package manager)
debops 0.8.0

Setup project
$ debops-init project1

Clone a local copy of the DebOps monorepo in project
$ debops-update project1

Add inventory file in project1/ansible/inventory/hosts which contains:
[debops_service_bootstrap]
ubuntu1 ansible_ssh_host=ubuntu1.tc.test.com ansible_ssh_private_key_file=~/.ssh/ubuntu
^ is a valid hosts group and yes have tried [debops_all_hosts] by itself and together.

/etc/hosts
XXX.XXX.XXX.XXX ubuntu1.tc.test.com

~/.ssh/config
Host ubuntu*
IdentityFile ~/.ssh/ubuntu
User root
Port 22
ServerAliveInterval 240

project1/ansible/inventory/group_vars/all/bootstrap.yml contains:
bootstrap__hostname_domain_config_enabled: True
bootstrap__domain: 'tc.test.com'
bootstrap__etc_hosts: True
...

$ debops bootstrap --limit ubuntu1 --user root --ask-pass

It all seems to run just fine and returns:
PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
ubuntu4 : ok=36 changed=0 unreachable=0 failed=0

Make sure essential software is installed ------------------------------- 3.29s
Manage entries in /etc/hosts -------------------------------------------- 3.05s
Ensure that requested UNIX system groups exist -------------------------- 2.73s
Remove tmpfiles configuration if not specified -------------------------- 2.57s
Remove sudo configuration if not specified ------------------------------ 2.21s
Update APT repositories, install core Python packages ------------------- 1.83s
Install requested APT packages ------------------------------------------ 1.83s
Install required packages ----------------------------------------------- 1.81s
Gathering Facts --------------------------------------------------------- 1.35s
Install ssh public key on admin accounts -------------------------------- 1.31s

Note: I ran bootstrap once already to make the changes. Then again to check changed = 0. Then changed the hostname and expected to see some changes. However no change of hostname.

Any thoughts much appreciated. Thanks. :)

**Comment by drybjed** [comment]
Is the entry you specified with Xes already present in the `/etc/hosts` file before you apply the bootstrap playbook? In that case I don't see a reason for Ansible modify it, so the role would result with no changes.

If you are using the `v0.8.0` version, perhaps you would want to switch to the `master` branch instead. There were huge changes with this functionality, namely the `bootstrap.yml` playbook now uses the [`debops.netbase`](https://docs.debops.org/en/master/ansible/roles/debops.netbase/index.html) to configure the `/etc/hosts` file and the hostname itself. You should try it out, perhaps this version will work better. I suspect that there might have been an issue with the hostname change in the old `debops.bootstrap` role which should be resolved with `debops.netbase` role.

**Comment by zenflip** [comment]
That's totally cool that you responded so quickly. Thanks so much!

The X's were for the local /etc/hosts Mac (also the controller) not on the remote ubuntu1 box. 

ubuntu1 /etc/hosts currently contains:

```
127.0.0.1	localhost

#The following lines are desirable for IPv6 capable hosts
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
```

And yes I am using the v0.8.0 version currently. Ok, I'll switch to the master branch instead and try that, thanks.

**Comment by zenflip** [comment]
I installed the master branch of debops with:
$ pipenv install -e git+https://github.com/debops/debops.git@master#egg=debops_master

Which adds this to my Pipfile:
debops-master = {editable = true,git = "https://github.com/debops/debops.git",ref = "master"}

After running this command again, no joy:
$ debops bootstrap --limit ubuntu1 --user root --ask-pass

This shows the relevant part not changed.

TASK [debops.netbase : Manage the hostname] **************************************************************************************************************************************************************************************************
ok: [ubuntu1]

TASK [debops.netbase : Manage entries in /etc/hosts] *****************************************************************************************************************************************************************************************
ok: [ubuntu1] => (item={'127.0.0.1': ['localhost']})
ok: [ubuntu1] => (item={'127.0.1.1': []})
ok: [ubuntu1] => (item={'::1': ['localhost', 'ip6-localhost', 'ip6-loopback']})
ok: [ubuntu1] => (item={'ff02::1': ['ip6-allnodes']})
ok: [ubuntu1] => (item={'ff02::2': ['ip6-allrouters']})
ok: [ubuntu1] => (item={'XX.XXX.XXX.XXX': []})
ok: [ubuntu1] => (item={'2001:19f0:7401:88cd:5400:1ff:fed3:1100': []})

Some questions:
1) Is the  debops-update project1 command installing the same debops package as would be installed by pip? If so, should I update that local version too?
2) I'm using Python 3.7.1. Does Debops work with this version or do I need to go back to 2.7.15?

Thanks.

**Comment by drybjed** [comment]
For `debops.netbase` to add entries to `/etc/hosts` automatically, you need to set the `netbase__domain` variable (similar to old `bootstrap__domain`). In the output you can see the hosts IPv4 and IPv6 address, so you are almost there. Check the defaults file of the `debops.netbase` role, there are some useful comments there, also included [in the role documentation](https://docs.debops.org/en/master/ansible/roles/debops.netbase/defaults.html#hostname-and-domain).

The `debops-update` command will pull the `master` branch from GitHub and update any changes. You can use it to get updates to the project, just keep an eye on the Changelog and/or upgrade notes if you are using DebOps in production.

DebOps should work with Python 3.x, although I don't use it in that environment at present - some other users do though. If you find any issues, please report them so that they can be fixed. I'm aiming for DebOps to support both Py2 and Py3 environment for the forseeable future.

**Comment by zenflip** [comment]
Ah ha!

TASK [debops.netbase : Manage entries in /etc/hosts] *****************************************************************************************************************************************************************************************
ok: [ubuntu1] => (item={'127.0.0.1': ['localhost']})
ok: [ubuntu1] => (item={'127.0.1.1': []})
ok: [ubuntu1] => (item={'::1': ['localhost', 'ip6-localhost', 'ip6-loopback']})
ok: [ubuntu1] => (item={'ff02::1': ['ip6-allnodes']})
ok: [ubuntu1] => (item={'ff02::2': ['ip6-allrouters']})
changed: [ubuntu1] => (item={'XXX.XXX.XXX.XXX': ['ubuntu1.tc.test.com', 'ubuntu1']})
changed: [ubuntu1] => (item={'2001:19f0:7401:88cd:5400:1ff:fed3:1108': ['ubuntu1.tc.test.com', 'ubuntu1']})

```
root@ubuntu4:~# hostname -f
ubuntu4.tc.test.com
```

root@ubuntu4:~# cat /etc/hosts

```
127.0.0.1	localhost

# The following lines are desirable for IPv6 capable hosts
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

XXX.XXX.XXX.XXX	ubuntu4.tc.test.com ubuntu4
2001:19f0:7401:88cd:5400:1ff:fed3:1108	ubuntu4.tc.test.com ubuntu4
```

**Comment by zenflip** [comment]
So far I'm not seeing any issues with Python 3.7.1 so am going to stick with that version.
It looks like the bootstrap version on 0.8.0 isn't working so well though and the docs need updating around this issue. Otherwise people new to the project like me may just give up at this hurdle.
I'm going to keep going because I think this project is an excellent idea! :)

**Comment by drybjed** [comment]
I guess a new release is in order then, I'll try to push it out as soon as `ansible-lint` issues are fixed. Not sure yet when though.

**Comment by zenflip** [comment]
Sounds good. It looks like you're right on the Ansible/devops cutting edge with this project and a new release would be a good idea to bring together all the disparate threads.
