### ISSUE TITLE
[debops.netbox] git version "master" breaks version comparison

### ISSUE THREAD

**Issue by cultcom** [debops/debops#597]
https://github.com/debops/debops/blob/2b68f94371990be86266fe6d2be7953b4c262261/ansible/roles/debops.netbox/defaults/main.yml#L141

without a proper version I get this exception:
´´´
TASK [debops.netbox : Remove old python2 based virtualenv] *******************************************************************************************
fatal: [vm01]: FAILED! => {"msg": "The conditional check '( netbox__virtualenv_version == '3' and netbox__register_virtualenv_version.stat.lnk_target|d() == 'python2' )' failed. The error was: An unhandled exception occurred while templating '{{ \"\" if netbox__git_version|replace(\"v\", \"\") is version(\"2.5\", \"<\") else \"3\" }}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: Version comparison: '<' not supported between instances of 'str' and 'int'\n\nThe error appears to have been in '/home/wigge/.local/share/debops/debops/ansible/roles/debops.netbox/tasks/main.yml': line 62, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Remove old python2 based virtualenv\n  ^ here\n"}
´´´

**Comment by drybjed** [comment]
The changes [seem to work fine in a test environment](https://gitlab.com/debops/debops/-/jobs/142195288)... @cultcom, what Ansible version are you using? Can you check with current stable release? Did you set any `netbox__*` variables in the inventory?

**Comment by cultcom** [comment]
ansible 2.7.2.post0
python version = 3.6.5

I left the variable set to "master" which failed. The I set it manually to "v2.5.2" and it worked.

Ansible is running with python3 in my venv so I guess that might be a reason?

**Comment by drybjed** [comment]
Yes, it looks like Python 3 is an issue in this case. We need a more specific condition, I'll check what can be done.
