### ISSUE TITLE
[debops.php] Support for buster-based distros (php7.3)

### ISSUE THREAD

**Issue by evilham** [debops/debops#659]
As you can see, I am already testing things for when buster becomes stable and would help making things work with it.

As far as I can tell, what would be needed for `debops.php` would be to update `php__release_included_map` and `php__version_preference` accordingly, is that correct?

(just tested by manually setting `php__version_preference` and `php__included_packages` manually and it appears to work just fine)

**Comment by drybjed** [comment]
Yes, although I think that version preference variable should be converted to a map as well. Debian Buster will use PHP 7.3 version, 7.1 and 7.2 are not present in the main Debian archive for older releases to use, however, Sury repository has them so they can be used when the Sury repository is enabled. Unfortunately when I recently tried to set up PHP 7.3 on Stretch via Sury repository, some of the package dependencies were broken. This could impact Stretch installs if you blindly add `php7.3` version to the version preference list, which I would want to avoid.

I'd say, create `php__version_preference_map` variable that has entries for Jessie, Stretch, Xenial and Bionic with only PHP 7.2 and lower, in the `php__version_preference` set the value:
```yaml
php__version_preference: '{{ php__version_preference_map[ansible_distribution_release]
                             | d([ "php7.3" ]) }}'
```
This could let us start the versioning from the beginning and add more as the time goes on and new OS releases happen. if the users overrode the version preference in the inventory, their choice should still work as expected.
