### ISSUE TITLE
Refactor roles to use debops.python to install python

### ISSUE THREAD

**Issue by alinalexandru** [debops/debops#693]
@drybjed said:
> Some of the roles still install python packages directly. they should use debops.python role instead and install py2 and py3 versions using it, then py2 could be disabled centrally at some point. you can check debops.netbox role and playbook to see how it should be done

**Comment by alinalexandru** [comment]
- [ ] sdasd
- [ ] a dfdf

**Comment by LeonardoAndrei** [comment]
@drybjed These are the roles that install python and need to be refactored. Would you want to remove/add something in the list of debops roles below?

dokuwiki
gitlab.
librenms
salt
unbound
docker
avahi
docker
libvirt
libvirtd
mariadb
mariadb_server
mosquito
postgresql
preseed

**Comment by drybjed** [comment]
Thanks for checking! The list sounds OK to me, we can deal with any stragglers later on.

It would be nice to have each change around a given role in a separate `git` commit. Remember to update the Ansible playbooks as well, not only of the specific roles, but also any playbooks that use a given role as a dependency.

The changes will probably also affect the order of the GitLab pipeline in `.gitlab-ci.yml` file, but we can deal with that later.

**Comment by alinalexandru** [comment]
@LeonardoAndrei, @drybjed I know that this was done. Are there other roles that needs to be updated?

**Comment by drybjed** [comment]
There are some roles that depend on packages that use Python2 but that's out of scope of this particular issue. All DebOps roles should now be converted to use `debops.python` role, so I'll close this one as fixed.
