### ISSUE TITLE
[bootstrap] dbus needed for netbase

### ISSUE THREAD

**Issue by tumd** [debops/debops#702]
Hi,

Just installed a very basic Buster install on a physical host.
Ran the bootstrap-playbook, and it failed at task;
`debops.netbase : Manage the hostname`
With the message;
`FAILED! => {"changed": false, "msg": "Command failed rc=1, out=, err=Failed to create bus connection: No such file or directory\n"}`

Installing the package `dbus` manually solves this.
I noted that `dbus` is in fact installed in `debops.bootstrap`, however this run after `debops.netbase` in the bootstrap-playbook.

**Comment by drybjed** [comment]
Thanks for the bug report. I suppose the `hostname` Ansible module depends on `dbus` so we cannot avoid it here. Do you want to make a PR that adds `dbus` to the list of APT packages installed by the `debops.netbase` role?
