### ISSUE TITLE
debops.netbase fails in Docker container

### ISSUE THREAD

**Issue by jrgoldfinemiddleton** [debops/debops#706]
When following the [documentation](https://docs.debops.org/en/latest/introduction/quick-start.html#run-the-debops-playbook-against-the-host) about running the **debops** command inside of the **debops/debops** Docker container, the play fails at the "Manage entries in /etc/hosts" task of the **debops.netbase** role.

Command:
`ansible@d1ba84d47e91:~/src/controller$ debops`

Error:
`TASK [debops.netbase : Manage entries in /etc/hosts] ***************************
ok: [localhost] => (item={u'127.0.0.1': [u'localhost']})
ok: [localhost] => (item={u'127.0.1.1': []})
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 16] Device or resource busy
failed: [localhost] (item={u'::1': [u'localhost', u'ip6-localhost', u'ip6-loopback']}) => {"changed": false, "item": {"id": 20, "name": "::1", "real_weight": 20, "section": "unknown", "state": "present",
"value": [{"id": 200, "name": "localhost", "real_weight": 200, "state": "present", "weight": 0}, {"id": 201, "name": "ip6-localhost", "real_weight": 201, "state": "present", "weight": 0}, {"id": 202, "nam
e": "ip6-loopback", "real_weight": 202, "state": "present", "weight": 0}], "weight": 0}, "msg": "Unable to make /tmp/tmpGJm1vu into to /etc/hosts, failed final rename from /etc/.ansible_tmpJagy96hosts: [E
rrno 16] Device or resource busy"}`

After some research, I discovered that [Docker doesn't allow modifying the /etc/hosts file](https://github.com/William-Yeh/docker-ansible/issues/4#issuecomment-149084120).

Was this historically working for folks?

**Comment by drybjed** [comment]
@jrgoldfinemiddleton Thanks for the bug report. The modification of `/etc/hosts` wasn't in the playbook when that documentation was written. However, this is a bug in the role and it should be fixed there. I'll add a check if the role is applied on a Docker container and skip this task in that case. That should solve the issue.

**Comment by ganto** [comment]
I guess this was fixed by #709?

**Comment by drybjed** [comment]
Yes, since I don't see any way to manage `/etc/hosts` from inside of the unprivileged container. I suppose that the issue can be closed.
