### ISSUE TITLE
Possible upstream bug with "loop" directive, revealed with netbase__combined_hosts variable

### ISSUE THREAD

**Issue by jrgoldfinemiddleton** [debops/debops#707]
Hi,

I believe there may be a bug with the Ansible **debug** module, but I would like to confirm the bug is real before taking it upstream.  It manifests when I run the **debops.netbase** role and add some debug tasks to the `main.yml` task file.

When I use the **debug** module to print out the `netbase__combined_hosts` list, the last two entries are shown with an empty array for the `value` key.

However, when I use the **debug** module with a `loop` directive to print out the same list one item at a time, the last two entries are shown with an array of length two for the `value` key.  The `value` key is defined with a dependency on Ansible local facts for the **debops.netbase** role.  I have found that if I manually set the fact `netbase__domain` to a non-empty string, like "localhost", the last two entries are shown with an array of length two for the `value` key.

Discovered using [debops/debops Docker image](https://github.com/debops/debops/blob/36bd2520d5f1219cbed5e0d450fecb1c3d20d931/Dockerfile)

[Variable definitions](https://docs.debops.org/en/v0.8.1/ansible/roles/debops.netbase/defaults.html) (using default values for demo)

**Ansible version:**
```bash
ansible@d1ba84d47e91:~/src/controller$ ansible --version
ansible 2.7.8
  config file = /home/ansible/src/controller/ansible.cfg
  configured module search path = [u'/home/ansible/src/controller/ansible/playbooks/library', u'/home/ansible/src/controller/ansible/plugins/library', u'/home/ansible/src/controller/ansible/library', u'/home/ansible/src/controller/debops/ansible/playbooks/playbooks/library', u'/home/ansible/src/controller/debops/ansible/playbooks/library', u'/home/ansible/src/controller/debops/ansible/plugins/library', u'/home/ansible/src/controller/debops/ansible/library', u'/home/ansible/.local/share/debops/debops/ansible/playbooks/playbooks/library', u'/home/ansible/.local/share/debops/debops/ansible/playbooks/library', u'/home/ansible/.local/share/debops/debops/ansible/plugins/library', u'/home/ansible/.local/share/debops/debops/ansible/library', u'/usr/local/lib/python2.7/dist-packages/debops/ansible/library', u'/usr/local/lib/python2.7/dist-packages/debops/ansible/playbooks/library', u'/home/ansible/.local/share/debops/debops/ansible/playbooks/library', u'/usr/share/ansible/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

**Relevant tasks added to `main.yml` file of **debops.netbase** role:**
```yaml
#- name: Set netbase__domain to localhost
#  set_fact:
#    netbase__domain: localhost

- name: Print netbase__combined_hosts var
  debug:
    var: netbase__combined_hosts

- name: Print netbase__combined_hosts var using msg
  debug:
    msg: '{{ netbase__combined_hosts }}'

- name: Print netbase__hostname var using msg
  debug:
    msg: '{{ netbase__hostname }}'

- name: Print netbase__domain var using msg
  debug:
    msg: '{{ netbase__domain }}'

- name: Print netbase__aliases var using msg
  debug:
    msg: '{{ netbase__aliases }}'

- name: Print netbase__domain_host_entry var using msg
  debug:
    msg: '{{ netbase__domain_host_entry }}'

- name: Print ansible_local.netbase facts
  debug:
    msg: '{{ ansible_local.netbase }}'

- name: Print netbase__combined_hosts var using loop
  debug:
    var: item
  loop: '{{ netbase__combined_hosts }}'

- name: Print netbase__combined_hosts var
  debug:
    var: netbase__combined_hosts
```

**Output:**
```bash
ansible@d1ba84d47e91:~/src/controller$ debops                                                                                                                                                    [660/54594]
Running Ansible playbooks:
/home/ansible/.local/share/debops/debops/ansible/playbooks/site.yml

PLAY [Security assertions] *********************************************************************************************************************************************************************************

TASK [Check for Ansible version without known vulnerabilities] *********************************************************************************************************************************************
ok: [localhost -> localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
 [WARNING]: Could not match supplied host pattern, ignoring: debops_service_core


PLAY [Prepare core environment] ****************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debops.core : Ensure that APT cache is valid] ********************************************************************************************************************************************************
ok: [localhost]

TASK [debops.core : Install required core packages] ********************************************************************************************************************************************************
ok: [localhost] => (item=libcap2-bin)

TASK [debops.core : Create root directories] ***************************************************************************************************************************************************************
ok: [localhost] => (item={u'path': u'/etc/ansible/facts.d', u'fact': u'facts'})
ok: [localhost] => (item={u'path': u'/usr/local/bin', u'fact': u'bin'})
ok: [localhost] => (item={u'path': u'/usr/local/etc', u'fact': u'etc'})
ok: [localhost] => (item={u'path': u'/usr/local/lib', u'fact': u'lib'})
ok: [localhost] => (item={u'path': u'/usr/local/sbin', u'fact': u'sbin'})
ok: [localhost] => (item={u'path': u'/usr/local/share', u'fact': u'share'})
ok: [localhost] => (item={u'path': u'/usr/local/src', u'fact': u'src'})
ok: [localhost] => (item={u'path': u'/srv', u'fact': u'data'})
ok: [localhost] => (item={u'path': u'/srv', u'fact': u'srv'})
ok: [localhost] => (item={u'path': u'/var/backups', u'fact': u'backup'})
ok: [localhost] => (item={u'path': u'/var/local', u'fact': u'home'})
ok: [localhost] => (item={u'path': u'/var/local', u'fact': u'app'})
ok: [localhost] => (item={u'path': u'/var/local', u'fact': u'var'})
ok: [localhost] => (item={u'path': u'/var/cache', u'fact': u'cache'})
ok: [localhost] => (item={u'path': u'/var/log', u'fact': u'log'})
ok: [localhost] => (item={u'path': u'/var/spool', u'fact': u'spool'})

TASK [debops.core : Read the host UUID] *******************************************************************************************************************************************************************$
ok: [localhost]

TASK [debops.core : Save local facts] *********************************************************************************************************************************************************************$
ok: [localhost] => (item=core)
ok: [localhost] => (item=resolver)
ok: [localhost] => (item=root)
ok: [localhost] => (item=tags)
ok: [localhost] => (item=uuid)

TASK [debops.core : Install local fact scripts] ***********************************************************************************************************************************************************$
ok: [localhost]
 [WARNING]: Could not match supplied host pattern, ignoring: debops_no_common


PLAY [Common configuration for all hosts] *****************************************************************************************************************************************************************$

TASK [Gathering Facts] ************************************************************************************************************************************************************************************$
ok: [localhost]

TASK [debops.netbase : Install required packages] *********************************************************************************************************************************************************$
ok: [localhost] => (item=netbase)
ok: [localhost] => (item=libcap2-bin)
ok: [localhost] => (item=dbus)

TASK [debops.netbase : Make sure that Ansible local facts directory exists] ********************************************************************************************************************************
ok: [localhost]

TASK [debops.netbase : Save netbase local facts] ***********************************************************************************************************************************************************
ok: [localhost]

TASK [debops.netbase : Print netbase__combined_hosts var] ***************************************************************************************************************************************[586/54594]
ok: [localhost] => {
    "netbase__combined_hosts": [
        {
            "127.0.0.1": [
                "localhost"
            ]
        },
        {
            "127.0.1.1": []
        },
        {
            "::1": [
                "localhost",
                "ip6-localhost",
                "ip6-loopback"
            ]
        },
        {
            "ff02::1": [
                "ip6-allnodes"
            ]
        },
        {
            "ff02::2": [
                "ip6-allrouters"
            ]
        },
        {
            "name": "172.17.0.2",
            "separator": true,
            "value": []
        },
        {
            "name": "",
            "value": []
        }
    ]
}

TASK [debops.netbase : Print netbase__combined_hosts var using msg] *****************************************************************************************************************************[546/54594]
ok: [localhost] => {
    "msg": [
        {
            "127.0.0.1": [
                "localhost"
            ]
        },
        {
            "127.0.1.1": []
        },
        {
            "::1": [
                "localhost",
                "ip6-localhost",
                "ip6-loopback"
            ]
        },
        {
            "ff02::1": [
                "ip6-allnodes"
            ]
        },
        {
            "ff02::2": [
                "ip6-allrouters"
            ]
        },
        {
            "name": "172.17.0.2",
            "separator": true,
            "value": []
        },
        {
            "name": "",
            "value": []
        }
    ]
}

TASK [debops.netbase : Print netbase__hostname var using msg] ***********************************************************************************************************************************[506/54594]
ok: [localhost] => {
    "msg": "d1ba84d47e91"
}

TASK [debops.netbase : Print netbase__domain var using msg] ************************************************************************************************************************************************
ok: [localhost] => {
    "msg": ""
}

TASK [debops.netbase : Print netbase__aliases var using msg] ***********************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "d1ba84d47e91"
    ]
}

TASK [debops.netbase : Print netbase__domain_host_entry var using msg] *************************************************************************************************************************************
ok: [localhost] => {
    "msg": []
}

TASK [debops.netbase : Print ansible_local.netbase facts] **************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "configured": true,
        "self_address": "172.17.0.2",
        "self_domain": "",
        "self_fqdn": "d1ba84d47e91",
        "self_local": true
    }
}

TASK [debops.netbase : Print netbase__combined_hosts var using loop] ****************************************************************************************************************************[473/54594]
ok: [localhost] => (item={u'127.0.0.1': [u'localhost']}) => {
    "item": {
        "127.0.0.1": [
            "localhost"
        ]
    }
}
ok: [localhost] => (item={u'127.0.1.1': []}) => {
    "item": {
        "127.0.1.1": []
    }
}
ok: [localhost] => (item={u'::1': [u'localhost', u'ip6-localhost', u'ip6-loopback']}) => {
    "item": {
        "::1": [
            "localhost",
            "ip6-localhost",
            "ip6-loopback"
        ]
    }
}
ok: [localhost] => (item={u'ff02::1': [u'ip6-allnodes']}) => {
    "item": {
        "ff02::1": [
            "ip6-allnodes"
        ]
    }
}
ok: [localhost] => (item={u'ff02::2': [u'ip6-allrouters']}) => {
    "item": {
        "ff02::2": [
            "ip6-allrouters"
        ]
    }
}
ok: [localhost] => (item={u'separator': True, u'name': u'172.17.0.2', u'value': [u'd1ba84d47e91.localhost', u'd1ba84d47e91']}) => {
    "item": {
        "name": "172.17.0.2",
        "separator": true,
        "value": [
            "d1ba84d47e91.localhost",
            "d1ba84d47e91"
        ]
    }                                                                                                                                                                                            [429/54594]
}
ok: [localhost] => (item={u'name': u'', u'value': [u'd1ba84d47e91.localhost', u'd1ba84d47e91']}) => {
    "item": {
        "name": "",
        "value": [
            "d1ba84d47e91.localhost",
            "d1ba84d47e91"
        ]
    }
}

TASK [debops.netbase : Print netbase__combined_hosts var] **************************************************************************************************************************************************
ok: [localhost] => {
    "netbase__combined_hosts": [
        {
            "127.0.0.1": [
                "localhost"
            ]
        },
        {
            "127.0.1.1": []
        },
        {
            "::1": [
                "localhost",
                "ip6-localhost",
                "ip6-loopback"
            ]
        },
        {
            "ff02::1": [
                "ip6-allnodes"
            ]
        },
        {
            "ff02::2": [
                "ip6-allrouters"
            ]
        },
        {
            "name": "172.17.0.2",
            "separator": true,
            "value": []
        },
        {
            "name": "",
            "value": []
        }
    ]
}
```

Why would **debug** with the `loop` directive find the Ansible fact `ansible_local.netbase.self_domain` when **debug** without the `loop` directive seems not to??  Is this a known issue or somehow expected behavior?  Is there something special about the variable that causes the **debug** module to behave this way?

**Comment by drybjed** [comment]
This is not a bug. The `netbase__default_hosts` list contains an entry for the IPv6 address of the host; your container does not have an IPv6 address therefore that entry is empty.

The `netbase__combined_hosts` list is filtered through the custom `parse_kv_config` Ansible filter plugin to allow modification of the entries via Ansible inventory without the need to copy everything over. To see the final configuration used in the role tasks and templates, add a task like this:
```yaml
- debug:
    msg: '{{ netbase__combined_hosts | parse_kv_config }}'
```
This should show you the filtered configuration entries; you can see that the final entry has an empty 'value' key and will be ignored in the tasks/templates. There's no need to worry, everything is under control. :-)

**Comment by jrgoldfinemiddleton** [comment]
Hi @drybjed, thank you for the quick reply.

I was initially confused by the IPv6 part being skipped during the /etc/hosts **lineinfile** task due to the empty string for the `name` key, but that's not the issue here.  The issue I'm seeing is that the **debug** tasks I have created named "**Print netbase__combined_hosts var**" and "**Print netbase__combined_hosts var using loop**" print a different `value` for the item with `name` == "172.17.0.2".  I don't think that should be happening.  The only difference is whether the `loop` directive is used in the **debug** module.

**Print netbase__combined_hosts var**:
Output of `value` for item with `name` == "172.17.0.2": 
```
            "value": []
```

**Print netbase__combined_hosts var using loop**:
Output of `value` for item with `name` == "172.17.0.2":
```
        "value": [
            "d1ba84d47e91.localhost",
            "d1ba84d47e91"
        ]
```

For the exact same variable, output is different.  In one task, the value must be incorrect.  In fact, the **Print netbase__combined_hosts var** task shows the incorrect value.

I'm not worried that the role (without my added tasks) isn't functioning correctly.  I believe there is an actual bug with the Ansible **debug** module.  What do you think?

**Comment by drybjed** [comment]
Ah, I see, you mean this bit:
```
ok: [localhost] => (item={u'separator': True, u'name': u'172.17.0.2', u'value': [u'd1ba84d47e91.localhost', u'd1ba84d47e91']}) => {
    "item": {
        "name": "172.17.0.2",
        "separator": true,
        "value": [
            "d1ba84d47e91.localhost",
            "d1ba84d47e91"
        ]
    }                                                                                                                                                                                            [429/54594]
}
ok: [localhost] => (item={u'name': u'', u'value': [u'd1ba84d47e91.localhost', u'd1ba84d47e91']}) => {
    "item": {
        "name": "",
        "value": [
            "d1ba84d47e91.localhost",
            "d1ba84d47e91"
        ]
    }
}
```
There shouldn't be any values there, right? That could suggest that the `loop` code doesn't properly reset on empty values, at least in a `debug` task... But I would first try and reproduce this in a minimal playbook, to be sure.

**Comment by jrgoldfinemiddleton** [comment]
Hi @drybjed, the output you included is what I'm referring to, yes.  But I believe the value of the `value` key should not be an empty array.  So in the segment you included, the output is correct.  I'm concerned that without using the `loop` directive, the **debug** module prints the variable incorrectly.  When the `loop` directive is used, the variable is printed correctly.  I'll try to create a minimal playbook that demonstrates the issue.

**Comment by jrgoldfinemiddleton** [comment]
@drybjed, after looking over the code further, I agree with your assessment that the expected value of the `value` key should be `[]`.  Instead, when the `loop` directive is present, we get an array of length two.  No idea how it's being populated.  Here's a way to reproduce the issue, using a fresh container and never setting the `netbase` local facts at all:

Run a fresh **debops/debops** container:
```bash
sudo docker run -it --rm debops/debops
```

Inside the container, execute the following commands:
```bash
sudo apt update
sudo apt install -y vim
sudo vim /home/ansible/.local/share/debops/debops/ansible/roles/debops.netbase/tasks/main.yml
cd ~/src/controller/
debops --tags role::netbase
```

For the vim step above, paste the following contents into the tasks file:
```yaml
---
  #- name: Set netbase__domain to 'localhost' (if uncommented, produces the array of length two even without loop directive)
  #  set_fact:
  #    netbase__domain: localhost

- name: Print ansible_local.netbase.self_domain var using msg
  debug:
    msg: '{{ ansible_local.netbase.self_domain if ansible_local|d() and ansible_local.netbase|d() and ansible_local.netbase.self_domain|d() else "" }}'

- name: Print netbase__domain var using msg
  debug:
    msg: '{{ netbase__domain }}'

    #- name: Set netbase__domain_host_entry (if uncommented, produces the empty array even with loop directive)
    #  set_fact:
    #    netbase__domain_host_entry: []

- name: Print netbase__domain_host_entry var using msg
  debug:
    msg: '{{ netbase__domain_host_entry }}'

- name: Print netbase__default_hosts var using loop
  debug:
    var: item
  loop: '{{ netbase__default_hosts }}'

- name: Print netbase__default_hosts var
  debug:
    var: netbase__default_hosts
```

Output of final command (truncated at end of `debops.netbase` role execution):
```
ansible@31900c44b50d:~/src/controller$ debops --tags role::netbase
Running Ansible playbooks:
/home/ansible/.local/share/debops/debops/ansible/playbooks/site.yml

PLAY [Security assertions] ********************************************************************************************************************************************************************************$
 [WARNING]: Could not match supplied host pattern, ignoring: debops_service_core


PLAY [Prepare core environment] ***************************************************************************************************************************************************************************$

TASK [Gathering Facts] ************************************************************************************************************************************************************************************$
ok: [localhost]
 [WARNING]: Could not match supplied host pattern, ignoring: debops_no_common


PLAY [Common configuration for all hosts] *****************************************************************************************************************************************************************$

TASK [Gathering Facts] ************************************************************************************************************************************************************************************$
ok: [localhost]

TASK [debops.netbase : Print ansible_local.netbase.self_domain var using msg] *****************************************************************************************************************************$
ok: [localhost] => {
    "msg": ""
}

TASK [debops.netbase : Print netbase__domain var using msg] ************************************************************************************************************************************************
ok: [localhost] => {
    "msg": ""
}

TASK [debops.netbase : Print netbase__domain_host_entry var using msg] *************************************************************************************************************************************
ok: [localhost] => {
    "msg": []
}

TASK [debops.netbase : Print netbase__default_hosts var using loop] ****************************************************************************************************************************************
ok: [localhost] => (item={u'127.0.0.1': [u'localhost']}) => {
    "item": {
        "127.0.0.1": [
            "localhost"
        ]
    }
}
ok: [localhost] => (item={u'127.0.1.1': []}) => {                                                                                                                                                 [78/58868]
    "item": {
        "127.0.1.1": []
    }
}
ok: [localhost] => (item={u'::1': [u'localhost', u'ip6-localhost', u'ip6-loopback']}) => {
    "item": {
        "::1": [
            "localhost",
            "ip6-localhost",
            "ip6-loopback"
        ]
    }
}
ok: [localhost] => (item={u'ff02::1': [u'ip6-allnodes']}) => {
    "item": {
        "ff02::1": [
            "ip6-allnodes"
        ]
    }
}
ok: [localhost] => (item={u'ff02::2': [u'ip6-allrouters']}) => {
    "item": {
        "ff02::2": [
            "ip6-allrouters"
        ]
    }
}
ok: [localhost] => (item={u'separator': True, u'name': u'172.17.0.2', u'value': [u'31900c44b50d.localhost', u'31900c44b50d']}) => {
    "item": {
        "name": "172.17.0.2",
        "separator": true,
        "value": [
            "31900c44b50d.localhost",
            "31900c44b50d"
        ]
    }
}
ok: [localhost] => (item={u'name': u'', u'value': [u'31900c44b50d.localhost', u'31900c44b50d']}) => {
    "item": {
        "name": "",
        "value": [
            "31900c44b50d.localhost",
            "31900c44b50d"
        ]                                                                                                                                                                                         [34/58868]
    }
}

TASK [debops.netbase : Print netbase__default_hosts var] ***************************************************************************************************************************************************
ok: [localhost] => {
    "netbase__default_hosts": [
        {
            "127.0.0.1": [
                "localhost"
            ]
        },
        {
            "127.0.1.1": []
        },
        {
            "::1": [
                "localhost",
                "ip6-localhost",
                "ip6-loopback"
            ]
        },
        {
            "ff02::1": [
                "ip6-allnodes"
            ]
        },
        {
            "ff02::2": [
                "ip6-allrouters"
            ]
        },
        {
            "name": "172.17.0.2",
            "separator": true,
            "value": []
        },
        {
            "name": "",
            "value": []
        }
    ]
}
 [WARNING]: flush_handlers task does not support when conditional
```

Same behavior with `netbase__default_hosts` variable as `netbase__combined_hosts` variable before.  I'm at a loss.  Where is Ansible getting the array of length two from?!

**Comment by drybjed** [comment]
@jrgoldfinemiddleton OK, I know now what's happening; tere's no bug.

The `debops.netbase` configuration has [two entries, one for IPv4 and one for IPv6](https://github.com/debops/debops/blob/master/ansible/roles/debops.netbase/defaults/main.yml#L180-L187). Both entries reference the `netbase__domain_host_entry`. That's what you see in the two entries, the second entry with an empty `name` parameter.

**Comment by jrgoldfinemiddleton** [comment]
@drybjed, I can see that both of the last two list items reference `netbase__domain_host_entry` but that doesn't explain why two **debug** tasks print out the same list variable (`netbase__default_hosts`) with the final two elements being different.  Notice how the second to last task shows the last two entries' `value` field as an array with two elements:
```
       [
            "31900c44b50d.localhost",
            "31900c44b50d"
        ]
```

On the other hand, the last task shows the same `value` field as the empty array: `[]`.

In the task **debops.netbase : Print netbase__domain_host_entry var using msg**, Ansible says that `netbase__domain_host_entry` is the empty array.  Why doesn't the second to last task show that as well?

**Comment by drybjed** [comment]
@jrgoldfinemiddleton Well, I set up your test case in a Docker container, and I get the same result. No idea where it comes from, it seems to me that each `loop` instance performs its own variable substitution and somehow `netbase__domain` being empty in the non-looped case has a value in the looped case. You can even see it by adding an entry to `netbase__default_hosts`:
```yaml
- name: 'netbase_domain'
  value: '{{ netbase__domain }}'
```
I currently have no idea why it happens like this. If you find out, let me know. This could affect some things or usage patterns.

**Comment by jrgoldfinemiddleton** [comment]
Okay, good to have confirmation that you're seeing it too.  Thanks for taking the time to look at this issue.  What especially concerns me about this is that I think the issue affects more than just the **debug** module.  I'm hoping it's something unique to the variables as they're defined in **debops**, but that seems very unlikely to me.

Here's a fresh **debops/debops** Docker image this time running the **debops.netbase** role with no changes to defaults or tasks:
```
TASK [Gathering Facts] ****************************************************************************************************************************************************************************[8/59363]
ok: [localhost]

TASK [debops.netbase : Install required packages] **********************************************************************************************************************************************************
changed: [localhost] => (item=netbase)
ok: [localhost] => (item=libcap2-bin)
changed: [localhost] => (item=dbus)

TASK [debops.netbase : Make sure that Ansible local facts directory exists] ********************************************************************************************************************************
ok: [localhost]

TASK [debops.netbase : Save netbase local facts] ***********************************************************************************************************************************************************
changed: [localhost]

TASK [debops.netbase : Update Ansible facts if they were modified] *****************************************************************************************************************************************
ok: [localhost]

TASK [debops.netbase : Manage entries in /etc/hosts] *******************************************************************************************************************************************************
ok: [localhost] => (item={u'127.0.0.1': [u'localhost']})
ok: [localhost] => (item={u'127.0.1.1': []})
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 16] Device or resource busy
failed: [localhost] (item={u'::1': [u'localhost', u'ip6-localhost', u'ip6-loopback']}) => {"changed": false, "item": {"id": 20, "name": "::1", "real_weight": 20, "section": "unknown", "state": "present",
"value": [{"id": 200, "name": "localhost", "real_weight": 200, "state": "present", "weight": 0}, {"id": 201, "name": "ip6-localhost", "real_weight": 201, "state": "present", "weight": 0}, {"id": 202, "nam
e": "ip6-loopback", "real_weight": 202, "state": "present", "weight": 0}], "weight": 0}, "msg": "Unable to make /tmp/tmpVNjBnT into to /etc/hosts, failed final rename from /etc/.ansible_tmprE7p7Uhosts: [E
rrno 16] Device or resource busy"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 16] Device or resource busy
failed: [localhost] (item={u'ff02::1': [u'ip6-allnodes']}) => {"changed": false, "item": {"id": 30, "name": "ff02::1", "real_weight": 30, "section": "unknown", "state": "present", "value": [{"id": 300, "n
ame": "ip6-allnodes", "real_weight": 300, "state": "present", "weight": 0}], "weight": 0}, "msg": "Unable to make /tmp/tmp5AOSpp into to /etc/hosts, failed final rename from /etc/.ansible_tmpvGIflmhosts:
[Errno 16] Device or resource busy"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 16] Device or resource busy
failed: [localhost] (item={u'ff02::2': [u'ip6-allrouters']}) => {"changed": false, "item": {"id": 40, "name": "ff02::2", "real_weight": 40, "section": "unknown", "state": "present", "value": [{"id": 400,
"name": "ip6-allrouters", "real_weight": 400, "state": "present", "weight": 0}], "weight": 0}, "msg": "Unable to make /tmp/tmplknJoW into to /etc/hosts, failed final rename from /etc/.ansible_tmp2yTFxFhos
ts: [Errno 16] Device or resource busy"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 16] Device or resource busy
failed: [localhost] (item={u'172.17.0.2': [u'b4b611268ee3.localhost', u'b4b611268ee3']}) => {"changed": false, "item": {"id": 50, "name": "172.17.0.2", "real_weight": 50, "section": "unknown", "separator"
: true, "state": "present", "value": [{"id": 500, "name": "b4b611268ee3.localhost", "real_weight": 500, "state": "present", "weight": 0}, {"id": 501, "name": "b4b611268ee3", "real_weight": 501, "state": "
present", "weight": 0}], "weight": 0}, "msg": "Unable to make /tmp/tmpkyBdE3 into to /etc/hosts, failed final rename from /etc/.ansible_tmpCnC016hosts: [Errno 16] Device or resource busy"}
```

It fails due to the issue I reported in #706  but you can see the last "lineinfile" item of the loop has the mysterious `value` array with the two elements: `(item={u'172.17.0.2': [u'b4b611268ee3.localhost', u'b4b611268ee3']})`.  So it really seems to me that this is a larger problem than the **debug** module.  Something is up with the `loop` directive.

**Comment by jrgoldfinemiddleton** [comment]
> @drybjed, after looking over the code further, I agree with your assessment that the expected value of the `value` key should be `[]`. Instead, when the `loop` directive is present, we get an array of length two. No idea how it's being populated. Here's a way to reproduce the issue, using a fresh container and never setting the `netbase` local facts at all:
> 
> Run a fresh **debops/debops** container:
> 
> ```shell
> sudo docker run -it --rm debops/debops
> ```
> 
> Inside the container, execute the following commands:
> 
> ```shell
> sudo apt update
> sudo apt install -y vim
> sudo vim /home/ansible/.local/share/debops/debops/ansible/roles/debops.netbase/tasks/main.yml
> cd ~/src/controller/
> debops --tags role::netbase
> ```
> 
> For the vim step above, paste the following contents into the tasks file:
> 
> ```yaml
> ---
>   #- name: Set netbase__domain to 'localhost' (if uncommented, produces the array of length two even without loop directive)
>   #  set_fact:
>   #    netbase__domain: localhost
> 
> - name: Print ansible_local.netbase.self_domain var using msg
>   debug:
>     msg: '{{ ansible_local.netbase.self_domain if ansible_local|d() and ansible_local.netbase|d() and ansible_local.netbase.self_domain|d() else "" }}'
> 
> - name: Print netbase__domain var using msg
>   debug:
>     msg: '{{ netbase__domain }}'
> 
>     #- name: Set netbase__domain_host_entry (if uncommented, produces the empty array even with loop directive)
>     #  set_fact:
>     #    netbase__domain_host_entry: []
> 
> - name: Print netbase__domain_host_entry var using msg
>   debug:
>     msg: '{{ netbase__domain_host_entry }}'
> 
> - name: Print netbase__default_hosts var using loop
>   debug:
>     var: item
>   loop: '{{ netbase__default_hosts }}'
> 
> - name: Print netbase__default_hosts var
>   debug:
>     var: netbase__default_hosts
> ```
> 
> Output of final command (truncated at end of `debops.netbase` role execution):
> 
> ```
> ansible@31900c44b50d:~/src/controller$ debops --tags role::netbase
> Running Ansible playbooks:
> /home/ansible/.local/share/debops/debops/ansible/playbooks/site.yml
> 
> PLAY [Security assertions] ********************************************************************************************************************************************************************************$
>  [WARNING]: Could not match supplied host pattern, ignoring: debops_service_core
> 
> 
> PLAY [Prepare core environment] ***************************************************************************************************************************************************************************$
> 
> TASK [Gathering Facts] ************************************************************************************************************************************************************************************$
> ok: [localhost]
>  [WARNING]: Could not match supplied host pattern, ignoring: debops_no_common
> 
> 
> PLAY [Common configuration for all hosts] *****************************************************************************************************************************************************************$
> 
> TASK [Gathering Facts] ************************************************************************************************************************************************************************************$
> ok: [localhost]
> 
> TASK [debops.netbase : Print ansible_local.netbase.self_domain var using msg] *****************************************************************************************************************************$
> ok: [localhost] => {
>     "msg": ""
> }
> 
> TASK [debops.netbase : Print netbase__domain var using msg] ************************************************************************************************************************************************
> ok: [localhost] => {
>     "msg": ""
> }
> 
> TASK [debops.netbase : Print netbase__domain_host_entry var using msg] *************************************************************************************************************************************
> ok: [localhost] => {
>     "msg": []
> }
> 
> TASK [debops.netbase : Print netbase__default_hosts var using loop] ****************************************************************************************************************************************
> ok: [localhost] => (item={u'127.0.0.1': [u'localhost']}) => {
>     "item": {
>         "127.0.0.1": [
>             "localhost"
>         ]
>     }
> }
> ok: [localhost] => (item={u'127.0.1.1': []}) => {                                                                                                                                                 [78/58868]
>     "item": {
>         "127.0.1.1": []
>     }
> }
> ok: [localhost] => (item={u'::1': [u'localhost', u'ip6-localhost', u'ip6-loopback']}) => {
>     "item": {
>         "::1": [
>             "localhost",
>             "ip6-localhost",
>             "ip6-loopback"
>         ]
>     }
> }
> ok: [localhost] => (item={u'ff02::1': [u'ip6-allnodes']}) => {
>     "item": {
>         "ff02::1": [
>             "ip6-allnodes"
>         ]
>     }
> }
> ok: [localhost] => (item={u'ff02::2': [u'ip6-allrouters']}) => {
>     "item": {
>         "ff02::2": [
>             "ip6-allrouters"
>         ]
>     }
> }
> ok: [localhost] => (item={u'separator': True, u'name': u'172.17.0.2', u'value': [u'31900c44b50d.localhost', u'31900c44b50d']}) => {
>     "item": {
>         "name": "172.17.0.2",
>         "separator": true,
>         "value": [
>             "31900c44b50d.localhost",
>             "31900c44b50d"
>         ]
>     }
> }
> ok: [localhost] => (item={u'name': u'', u'value': [u'31900c44b50d.localhost', u'31900c44b50d']}) => {
>     "item": {
>         "name": "",
>         "value": [
>             "31900c44b50d.localhost",
>             "31900c44b50d"
>         ]                                                                                                                                                                                         [34/58868]
>     }
> }
> 
> TASK [debops.netbase : Print netbase__default_hosts var] ***************************************************************************************************************************************************
> ok: [localhost] => {
>     "netbase__default_hosts": [
>         {
>             "127.0.0.1": [
>                 "localhost"
>             ]
>         },
>         {
>             "127.0.1.1": []
>         },
>         {
>             "::1": [
>                 "localhost",
>                 "ip6-localhost",
>                 "ip6-loopback"
>             ]
>         },
>         {
>             "ff02::1": [
>                 "ip6-allnodes"
>             ]
>         },
>         {
>             "ff02::2": [
>                 "ip6-allrouters"
>             ]
>         },
>         {
>             "name": "172.17.0.2",
>             "separator": true,
>             "value": []
>         },
>         {
>             "name": "",
>             "value": []
>         }
>     ]
> }
>  [WARNING]: flush_handlers task does not support when conditional
> ```
> 
> Same behavior with `netbase__default_hosts` variable as `netbase__combined_hosts` variable before. I'm at a loss. Where is Ansible getting the array of length two from?!

I believe it is safe to close this issue.  I'm not seeing the issue anymore.  :)
