### ISSUE TITLE
[debops.ifupdown] Remove full dependency on systemd

### ISSUE THREAD

**Issue by evilham** [debops/debops#718]
Hello,

I just noticed `Check systemd version` would fail in `debops.ifupdown/tasks/ifup_systemd` on non-systemd systems.

This wasn't the case before and I wasn't able to pinpoint the exact cause of change in behaviour. 

However, since the file name is systemd-centric, I figured it shouldn't run at all when it's not the service manager/init system, having a conditional include in the `main` tasks file makes this more robust and also simplifies `ifup_systemd`.

Creating issue to foster further discussion in case the incoming PR is not deemed appropriate.

**Comment by drybjed** [comment]
You don't need to create a separate issue as a "companion" to a pull request - pull requests on GitHub can contain comments. :-)
