### ISSUE TITLE
[debops.lvm] Disable lvmetad should also disable socket

### ISSUE THREAD

**Issue by ganto** [debops/debops#720]
I'm using the `debops.lvm` rule with the setting `lvm__global_use_lvmetad: False` on a Debian Stretch which properly disables the lvmetad in the configuration file. However, after doing so every LVM command would print out a warning like:
```
root@prometheus:~# lvs
  WARNING: Not using lvmetad because config setting use_lvmetad=0.
  WARNING: To avoid corruption, rescan devices to make changes visible (pvscan --cache).
[...]
```
The cause is that LVM still detects that the lvmetad service/socket are active but not used. Shouldn't the role also disable/enable the service/socket according to those setting? Or is there an easy way to do this with another role?

I'm happy to provide a patch but not sure if this is what you want.

**Comment by drybjed** [comment]
I wasn't aware that this is happening, thanks for the heads up. It sounds like a task in the `debops.lvm` role that checks the state of `lvm__global_use_lvmetad` variable and accordingly enables/disables the socket is a good solution to that. Want to work on a PR?

**Comment by ganto** [comment]
Sure
