### ISSUE TITLE
mailname should be current domain

### ISSUE THREAD

**Issue by computerlyrik** [debops/debops#732]
In
https://github.com/debops/debops/blob/06dc499adcdace64bb9f0bf48c1ab3b28ff6cfc6/ansible/roles/debops.postfix/defaults/main.yml#L96
The /etc/mailname is set to the current hostname.

If i am right, the mailname should be set to the servers mailaddress destination, e.g. on mx01.web.de should be set to web.de.

Workaround:
```postfix__mailname: mydomain.com``` on debops call

**Comment by drybjed** [comment]
Agreed. After reviewing [Debian documentation related to `/etc/mailname` file](https://wiki.debian.org/EtcMailName) I agree that this should be a domain, not a full FQDN. Documentation mentions both versions and how the file is interpreted by various MTAs, but it seems that in a larger environment the domain version should do the right thing - outgoing mail from a host has only the domain part, and the incoming mail can be redirect to the correct MX server via the DNS.

I'll change the default to be the domain in `debops.posfix` and `debops.nullmailer` roles after checking that everything works as expected. Thanks for the heads up. :-)

**Comment by computerlyrik** [comment]
@drybjed Thank for that fast reaction. Great process.
I will still stay on debops 0.8.1 - you know anything about a release cycle implementing this change?

**Comment by drybjed** [comment]
@computerlyrik It's a tricky question... At the moment tagged DebOps releases seem to happen roughly 6 months apart, perhaps that's an optimal release cycle for now. Latest one was in February, if this cycle continues next DebOps release is scheduled around August. The Debian Buster release will probably happen around that time as well, I estimate, similarly to Debian Stretch.

Although there are now many changes in the current `master` branch. At the moment I'm working on re-implementing the LDAP support across existing DebOps roles, I'd like to make a new release after that's done. A month, two perhaps? You could always try out the `master` branch to see if anything breaks in a test environment - you would have to do it for the next release anyway.
