### ISSUE TITLE
[debops.ferm] Can't turn off hashlimit for rule "filter_icmp_flood"

### ISSUE THREAD

**Issue by simonsystem** [debops/debops#734]
~~I think this line should be replaced:
https://github.com/debops/debops/blob/master/ansible/roles/debops.ferm/defaults/main.yml#L455
from `enabled` to `rule_state`
Similar to the other default rules.~~

Edit:
I tried to add `ferm__filter_icmp: False`, like described in the documentation. But it has no effect. I can still find a `mod hashlimit` line in the corresponding file:

`/etc/ferm/rules.d/015_rule_filter_icmp_flood.conf`
```
# This file is managed remotely, all changes will be lost

domain (ip ip6) table filter chain INPUT {
    protocol icmp @subchain "hashlimit-filter_icmp_flood" {

        mod hashlimit    hashlimit 10/second
                         hashlimit-burst 10
                         hashlimit-mode srcip
                         hashlimit-name filter_icmp_flood
                         hashlimit-htable-expire 3600000

            ACCEPT;

        &log("ipt-hashlimit-filter_icmp_flood: ");

        DROP;
    }
}
```

**Comment by drybjed** [comment]
The icmp filter was missed during the role rewrite, thanks for the bug report. I'll fix it right away.
