### ISSUE TITLE
403 on mailing list url

### ISSUE THREAD

**Issue by bbichero** [debops/debops#739]
There is a 403 error on the mailing list [website](https://lists.debops.org/mailman/listinfo/debops-users)

**Comment by drybjed** [comment]
Sorry about that. The Mailman installation limits what referers are allowed to access the website, to avoid bots spamming people with signup requests. If you open the website directly, or just click on the address bar in the web browser and press `Enter` it should open correctly.

**Comment by bbichero** [comment]
My bad I didn't try the root url !
Thanks for the info.
