### ISSUE TITLE
Split 'debops.nginx' role into frontend and backend roles

### ISSUE THREAD

**Issue by drybjed** [debops/debops#74]
At present, the `debops.nginx` role is used in multiple application playbooks (ownCloud/Nextcloud, phpIPAM, phpMyAdmin, NetBox, GitLab and more). The way it's used forces the application servers to be installed and running on the same host as the `nginx` server. Separating the webserver and application server into two hosts, to for example set up multiple backend intances behind one `nginx` central server, or even multiple load balanced `nginx` servers acting as proxies, is possible but requires creation of separate playbooks for different hosts.

I think that separating the existing `debops.nginx` role into `debops.nginx_frontend` and `debops.nginx_backend`, similar to how the MariaDB and PostgreSQL roles are designed, might be benefical. The purpose of the new roles would be:

- The `debops.nginx_frontend` acts as a server role. It can be installed either on the same host as the application server (current situation) or on a separate host. If the server is located on a separate host, connection to backend `nginx` servers (or applications that support it themselves) is protected by the [proxy over TLS connections](https://www.nginx.com/resources/admin-guide/nginx-tcp-ssl-upstreams/). The frontend role manages the main `nginx` configuration, that is `/etc/nginx/nginx.conf`, dynamic modules, support for Passenger, etc. The server host can support multiple separate application backends.

- The `debops.nginx_backend` role acts as a client role. This role is used in the playbook as a dependency for the application roles. It can detect if `nginx-as-frontend` is installed on the same host and back off from the main configuration, or configure a very simple and streamlined `nginx` instance to act as a proxy server with TLS support for the applications that don't support TLS connections directly. This role manages upstream and server configuration for a particular application, either locally or on the remote frontend server using Ansible's `delegate_to` mechanism. The role should support delegating to multiple hosts, so that load-balanced `nginx` frontend servers can have the same configuration.

I'm not sure about the specific naming yet, but I would like to avoid collisions with terms used frequently in the `nginx` context, like `server`, `upstream`, `client`, etc.

This is currently just a proposal. There are probably some issues that need to be ironed out. More extensive modification of the `debops.nginx` role will most likely happen after the DebOps `v1.0.0` is released, so there's still time for discussion.

**Comment by mortn** [comment]
IMHO it sounds like this would somewhat break the role in transitioning it away from what I thought was the master logic in Ansible: Keep your system/inventory specific variables in host_vars/group_vars (in your inventory, basically) and then the generic setup/config routines in the roles which calls for the role to be able to deal with non-standard cases like the one you describe.
Wouldn't it be equally smooth if the app. server playbook gets a "when: (nginx_host is not defined)" attached to the nginx role, explicitly telling nginx to _not_ be installed with an application server where the nginx_host is defined pointing to a different host.
Perhaps then the nginx server working as a front-end for the application server could be configured from this group_var.

**Comment by drybjed** [comment]
@mortn Yeah, after thinking about this more I don't see the benefit of multiple `debops.nginx` roles anymore. Making the webserver optional on the playbook level as you suggest might be a better solution to this.

**Comment by drybjed** [comment]
This idea is shelved for now, perhaps a different solution will be designed in the future. Closing.
