### ISSUE TITLE
Feature request: start / stop service

### ISSUE THREAD

**Issue by davemcphee** [debops/debops#753]
Using debops.resources I'm able to very simply ensure a service and all it's config files are installed - but I can't assert that it's started, without writing my own role. 

Is there some debops role to interface with systemd services?

**Comment by drybjed** [comment]
This will be handled by the `debops.resources` itself after the above PR is merged. This functionality can be used for simple stuff, but it lacks Ansible integration like handlers, service restarts on file changes, etc. For this, you should create a full Ansible role instead.

**Comment by davemcphee** [comment]
Holy crap :D

Thank you @drybjed !
