### ISSUE TITLE
OwnCloud playbook results in an infinite redirect loop

### ISSUE THREAD

**Issue by ofosos** [debops/debops#765]
Hi,
I just ran the owncloud playbook and this results in an infinite redirect loop, when I try to access the nextcloud app. 

My owncloud.yaml:

```
---
owncloud__variant: nextcloud
owncloud__redis_enabled: True
owncloud__fqdn: cloud.ofosos.org
owncloud__domain: ofosos.org
```

**Comment by ofosos** [comment]
I don't even get entries in nextcloud.log, php7.0-fpm.log is silent and the nginx server only records a redirect.

**Comment by drybjed** [comment]
I can open https://cloud.ofosos.org/, obviously didn't try to log in... Did you try in a different browser, on in incognito mode? Or from a different computer?

**Comment by ofosos** [comment]
misconfigured cloudflare :(
