### ISSUE TITLE
[debops.fail2ban] Add 'fail2ban__usedns' setting

### ISSUE THREAD

**Issue by htgoebel** [debops/debops#766]
Please add a setting to configure fail2ban's usedns usedns parameter for the jails to allow disabling use of DNS. Consider make it the default.

**Comment by gardouille** [comment]
Hello @htgoebel,

I set Debian's default value (**warn**). Can you tell us advantages/disadvantages if i set ``no`` by default ? No possible issue, misconfiguration,… ?
I will wait for @drybjed before overwrite Debian's value :)

**Comment by drybjed** [comment]
Fixed by https://github.com/debops/debops/pull/1321, closing.
