### ISSUE TITLE
ansible_python_interpreter: python3 breaks ferm - can't log in any longer

### ISSUE THREAD

**Issue by htgoebel** [debops/debops#768]
Setting
```
ansible_python_interpreter: /usr/bin/python3
```
breaks ferm, resp. the ssh login.

**How to reproduce:**
1. Set up some simple test-server using vagrant:
```
vagrant destroy --force
vagrant up ; vagrant provision
debops common --limit test-server
```
2. Set `ansible_python_interpreter: /usr/bin/python3` for this host.
3. Run above commands again
   --> After processing quite some tasks, debops.ferm will fail to login again

```
TASK [debops.ferm : Restart ferm] ****************************************************
changed: [test-server]

TASK [debops.ferm : Clear iptables rules if ferm is disabled] ************************
skipping: [test-server]

TASK [debops.ferm : Remove deprecated ifupdown hook] *********************************
ok: [test-server]

TASK [debops.ferm : Disable ferm after changes when requested] ***********************
skipping: [test-server]

TASK [debops.ferm : Ensure that Ansible local facts directory exists] ****************
fatal: [test-server]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange", "unreachable": true}
```

**This one passes**
1. Set up some simple test-server using vagrant (see above)
2. Set `ansible_python_interpreter: /usr/bin/python3` for this host.
3. Only run `debops common --limit test-server` again --> This one passes!

Using debops 0.8.1, ansible-2.7.10, Python 3

**Comment by drybjed** [comment]
Are you sure that it's `ferm` and not something else? You could try setting `ferm__enabled: False` in the inventory for that host and running the common playbook against it.

I don't see any apparent differences between two steps you gave as examples, whats the catch?

**Comment by htgoebel** [comment]
When running with `ferm__enabled: False`, the "fail" case passes.

The difference is this:

step | Fails | Passes
---- | ----- | ------
0 | vagrant destroy --force ; vagrant up --provision | vagrant destroy --force ; vagrant up --provision
1 | run "common" with default ansible_python_interpreter (which is python2) | run "common" with  ansible_python_interpreter=python3
2 | run "common" with ansible_python_interpreter=python3 | run "common" with  ansible_python_interpreter=python3
result | 2nd run *fails* | 2nd run *passes*

**Comment by drybjed** [comment]
Ah, I see. In the failed case you ster the interpreter after the host has been provisioned previously. I'll check that out, thanks. Not sure yet what's happening here.

**Comment by drybjed** [comment]
I tested this scenario against an LXC container with Debian Stretch, on an AMD64 server, and running the `debops.ferm` role worked fine, no error at the same step you mention.

Can you tell more about the environment? Are you using Debian Stable in the Vagrant VM or something else? Perhaps you could provide the `Vagrantfile` you are using to configure the VM, if it's not the one provided with DebOps?

**Comment by htgoebel** [comment]
Debian Stable in the Vagrant VM. I've send you the Vagrant file via e-mail.

Please keep in mind that I'm running the complete "common" playbook in all cases. So the cause might be another role.

**Comment by drybjed** [comment]
@htgoebel Sorry, I tried a few times but still I cannot reproduce the bug in my environment.

Perhaps we could schedule a Teamviewer/Hangouts session so that I could see it on your infrastructure and help debug it there? I'm usually free in the evenings/weekends, let me know if you're interested.

**Comment by htgoebel** [comment]
@drybjed I tried reproducing yet another time and failed, too. Looks like I changed some (unrelated) things in the config and the error vanished. Unfortunately I hadn't made a copy of the inventory when it failed.

Sorry for wasting your valuable time!

**Comment by drybjed** [comment]
Good to hear it works. If it happens again, let me know. :-)

**Comment by drybjed** [comment]
Good to hear it works. If it happens again, let me know. :-)

**Comment by drybjed** [comment]
Glad it works now. If the issue shows up again, let me know. :)

**Comment by avoine** [comment]
I have the same issue, I think the problem is that core.fact template is not working with python3:

> ~$ python3 /etc/ansible/facts.d/core.fact
> Traceback (most recent call last):
>   File "/etc/ansible/facts.d/core.fact", line 52, in <module>
>     if isinstance(output['admin_users'], basestring):
> NameError: name 'basestring' is not defined

**Comment by htgoebel** [comment]
@avoine Well spotted! Thanks!
