### ISSUE TITLE
apt_install now depends on needrestart existing

### ISSUE THREAD

**Issue by davemcphee** [debops/debops#772]
Since the change in this commit: https://github.com/debops/debops/commit/f6a0df67abceae3fc02722e37ea43e8c2b8c884c

The apt_install role fails during task `Disable kernel hints about pending upgrades`:

`fatal: [host00123]: FAILED! => changed=false 
  checksum: e0ec4a3e4d0b056a5d275616cb4b9214ff825e69
  msg: Destination directory /etc/needrestart/conf.d does not exist
`

**Comment by drybjed** [comment]
Hmm, so you don't install `needrestart` in that case? I suppose that task could check if `needrestart` is in the list of the APT packages installed by the role, that should be enough.

**Comment by davemcphee** [comment]
Ah, I see, it's from `apt_install__conditional_packages` which I do override. 

In light of that I think you can close this if you want; I have a root cause and work around, and if your position is "needrestart is required" then I'll accept that :)

**Comment by drybjed** [comment]
I would say it's recommended, but it should be possible to disable it if you don't need/want it. I'll look into making the role not add an override if it's disabled.
