### ISSUE TITLE
Mazer install failing

### ISSUE THREAD

**Issue by mikelkew** [debops/debops#789]
Hi there, I'm trying to install Debops via mazer, but it fails with:
`404 Client Error: Not Found for url: https://galaxy.ansible.com/api/v2/collections/debops/debops/`

Have you come across this before?

**Comment by drybjed** [comment]
Just now. Ansible Galaxy is is transforming to use collections instead of multi-role repositories. Looks like I need to implement that soon, otherwise lots of people will report this. :-)

**Comment by drybjed** [comment]
Update: it seems that the current version of `mazer` has support for Ansible Collections, but they are not yet implemented in Ansible Galaxy, and will be available in June 2019. For now I would suggest other installation methods, for example via PyPI or directly from the GitHub repository.

**Comment by mikelkew** [comment]
Ok, thanks @drybjed.

**Comment by nqb** [comment]
See #790

**Comment by nqb** [comment]
It looks like there is some collections now available on [Galaxy](https://galaxy.ansible.com/search?deprecated=false&keywords=&order_by=-relevance)

**Comment by drybjed** [comment]
@nqb Yes, and when I try to import a collection based on DebOps I have issues. I'm trying to ask guys on `#ansible-galaxy` IRC channel to help me with it, but it's going slow for now. I'll get back to that in a week, currently taking a short break.

**Comment by drybjed** [comment]
This should be solved after DebOps v2.0.1 has been published on Ansible Galaxy. You can also switch to the `ansible-galaxy` client to install DebOps, `mazer` has been discontinued. More details can be found in the [DebOps installation documentation](https://docs.debops.org/en/master/introduction/install.html#installation-from-ansible-galaxy).
