### ISSUE TITLE
debops.postgresql_server broken on ansible galaxy

### ISSUE THREAD

**Issue by philippe-rero** [debops/debops#797]
I may be doing it wrong, in this case just close the issue but I needed the debops.postgresql_server and the doc tells to install it via ansible-galaxy.

The package there is broken, it contains a debops.0.8.1 directory in it and the task dir is missing most of the functionnalities... it doesn't install postgresql_server software... This one on github is working fine.

Best regards

**Comment by drybjed** [comment]
DebOps development has been moved to the monorepo some time ago, and the roles on Ansible Galaxy were removed. They are now distributed as a single repository, called a multi-role repository, which is not supported by `ansible-galaxy` command. The `mazer` command supported that for a while but now the support has been removed and in June a new method called Ansible Collections will be introduced.

For now I would suggest that you either install DebOps roles via PyPI (`pip install --user debops[ansible]`) or directly from GitHub repository, and point your Ansible `roles_path` variables to them. This should do the trick. See the [DebOps installation instructions](https://docs.debops.org/en/master/user-guide/install.html) for more details.

**Comment by torvitas** [comment]
"it's not a bug, it's a feature"

**Comment by philippe-rero** [comment]
Thank drybjed, pip is fine and yes it's a kind of feature :-)
