### ISSUE TITLE
[debops.system_users] bootstrap doesn't have yadm installed

### ISSUE THREAD

**Issue by tumd** [debops/debops#811]
Hi,

While running the bootstrap playbook on a fresh machine, `debops.system_users` fails on task `Manage system users dotfiles` because yadm isn't installed.

I would propose that dotfiles-handling may be skipped when running `debops.system_users` from the bootstrap-playbook? Motivated by dotfiles shouldn't be a necessity to get a system bootstrapped and ready for future Ansible runs.

**Comment by drybjed** [comment]
Agreed. I thought that I covered that use case happening but apparently not. I'll try to replicate it on my setup and make a fix. Thanks for the bug report. :)

**Comment by drybjed** [comment]
This should be fixed now in `master`, I'll also include the fix in the `stable-1.0` branch.
