### ISSUE TITLE
debops.nginx there is no way to create a custom log_format

### ISSUE THREAD

**Issue by le9i0nx** [debops/debops#83]
The current configuration does not allow changing the format of the log.
Because format must be specified before the line indicating the path to the log.
```
log_format main '$remote_addr - $remote_user [$time_local] '
                '"$request_method $scheme://$host$request_uri $server_protocol" '
                '$status $body_bytes_sent "$http_referer" '
                '"$http_user_agent" "$http_x_forwarded_for"';
access_log /var/log/nginx/access.log main;
```
I think I can create a variable with the right conditions.
in this file https://github.com/debops/debops/blob/9222ec6dee11033a8c31ca7c09e3593250a2d369/ansible/roles/debops.nginx/templates/etc/nginx/nginx.conf.j2#L40-L44

**Comment by drybjed** [comment]
Sure, sounds like good idea. Although, perhaps the log formats could be managed globally in `nginx.conf`, and then referenced in the server configuration? That way role could manage a few different, default log formats for different outputs. And you can add another variable for custom log formats defined by the user.

**Comment by le9i0nx** [comment]
I think that here it is not quite rightly written. If you look at the official documentation.
When I checked it must be always a string of log_format and it should be higher access_log.

https://nginx.ru/en/docs/http/ngx_http_log_module.html
https://github.com/debops/debops/blob/1250d75c915ce32cbec1ecf1ff8be740774ef5df/ansible/roles/debops.nginx/templates/etc/nginx/sites-available/default.conf.j2#L208-L219

**Comment by drybjed** [comment]
The `log_format` directive is allowed only in the `http { }` section of the `nginx` configuration, not in `server { }` block. So, these entries will need to be defined outside of the server configuration. They could be defined in a separate file in `/etc/nginx/conf.d/` directory, maybe that would be a better choice than putting everything in `/etc/nginx/nginx.conf`.

**Comment by le9i0nx** [comment]
if log_format is created in the folder conf.d, then this line should be higher access_log
https://github.com/debops/debops/blob/32b2c202732a4c860f080452bde89502101f360e/ansible/roles/debops.nginx/templates/etc/nginx/nginx.conf.j2#L89
https://github.com/debops/debops/blob/32b2c202732a4c860f080452bde89502101f360e/ansible/roles/debops.nginx/templates/etc/nginx/nginx.conf.j2#L42
