### ISSUE TITLE
debops.org and docs.debops.org site / subsite are both down. Do you have alternative docs?

### ISSUE THREAD

**Issue by shaneholloman** [debops/debops#831]
[debops.org](https://debops.org) and [docs.debops.org](https://docs.debops.org) site / sub-site are both down.  
Do you have alternative docs?

Sorry if I missed these somewhere : )

**Comment by drybjed** [comment]
Sorry about that, my VPS provider has maintenance windows from time to time, they usually last 2-3 hours. The documentation should be back up by now.

DebOps documentation is hosted on [ReadTheDocs](https://readthedocs.org/), and you can reach it directly by going to https://debops.readthedocs.io/ website.

You can also build it locally by running `make docs` in the root directory of the repository. You will have to install `python-sphinx` and `python-sphinx-rtd-theme` packages for this command to work. You can then read the documentation in your web browser by accessing `file://<path/to>/debops/docs/_build/html/index.html` page.

**Comment by shaneholloman** [comment]
@drybjed Cheers Maciej!
