### ISSUE TITLE
[doc] latest point to 0.8.1

### ISSUE THREAD

**Issue by nqb** [debops/debops#833]
Hello,

When I go to https://docs.debops.org/en/latest/, HTML title reports DebOps v0.8.1-149-gb43d5d06.

IMO, we should point to `master` branch or to `stable-1.0`.

**Comment by drybjed** [comment]
Hmm, I'm not sure if the `latest` branch was that great of an idea, to be honest, epecially that we have a real stable branches now with official releases. And I don't want to create ten different documentation branches, so I think that we should limit the available documentation to `master`, corresponding to the `master` branch, and `stable-1.0` corresponding to the latest `v1.0.x` tag and updated over time. I will remove the rest of the various tagged documentations and `latest`. Do you think that's a good idea?

**Comment by nqb** [comment]
> so I think that we should limit the available documentation to `master`, corresponding to the `master` branch, and `stable-1.0` corresponding to the latest `v1.0.x` tag and updated over time

Completely agreed. It's a good idea.

However, we need to update many links in `master` branch that point to `latest`:
```console
# on master branch
$ grep -rl "docs.debops.org/en/latest" docs/ --exclude-dir=_build
docs/ansible/roles/debops.owncloud/defaults-detailed.rst
docs/ansible/roles/debops.persistent_paths/guides.rst
docs/ansible/roles/debops.dnsmasq/getting-started.rst
docs/ansible/roles/debops.environment/getting-started.rst
docs/ansible/roles/debops.tinc/getting-started.rst
docs/debops-api/_static/api/roles/debops.json
docs/debops-api/_static/api/role/debops.unattended_upgrades.json
docs/debops-playbooks/guides/getting-started.rst
docs/debops-tools/installation.rst
docs/dep/dep-0012.rst
docs/includes/global.rst

```

**Comment by drybjed** [comment]
Good catch, these probably should be changed to internal references. I'll check them out before removing the `latest` branch and docs.

**Comment by nqb** [comment]
@drybjed,

I will do the job for `docs/debops-playbooks/guides/getting-started.rst`

**Comment by nqb** [comment]
@drybjed: should I need to replace `latest` by `master` in all other files mentioned above ?

**Comment by drybjed** [comment]
This should be fixed after the multiple documentation updates. Closing.
