### ISSUE TITLE
[Vagrant] Virtualbox provider can't be use to provision nodes

### ISSUE THREAD

**Issue by nqb** [debops/debops#848]
Hello,

When you use current `Vagrantfile` with `vagrant-libvirt` plugin and a working Libvirt setup, you have the possibility to start an Ansible controller and some nodes to test DebOps roles on it.

This behavior can't be easily reproduce with Virtualbox provider and the current Vagrantfile because it requires a first network card that uses bridged networking or a NAT network [0] in order to:
  * establish communication between Ansible controller and nodes
  * allow machines to get access to Internet (in order to install packages)
  * using the Avahi detection to detect nodes

Of course, you can fit your needs after Vagrant has started VM but it's hard to automate in one Vagrantfile.

First network card set to NAT mode is a strong requirement for Vagrant to reach nodes through SSH. Maintainers don't want to change this [behavior](https://github.com/hashicorp/vagrant/issues/9030).

My proposal is to keep things like this:
 * Virtualbox provider can be use to set up a Ansible controller only and test DebOps roles directly on it
* Libvirt provider can be use to set up a Ansible controller and nodes to test DebOps roles on it.

@drybjed: I can improve documentation on this part if you agree.

[0] https://www.virtualbox.org/manual/ch06.html#networkingmodes

**Comment by drybjed** [comment]
Agreed. DebOps should be focused on configuring production networks that can be expected in normal deplyments, and not be biased towards an environment created by Vagrant. If the Virtualbox environment has to be modified for DebOps to work as expected, this should be documented.

There's [a section for Vagrant documentation](https://docs.debops.org/en/master/tester-guide/vagrant.html) in the docs already, perhaps you could add that info there, with tips on how Vagrant can be used with DebOps?

**Comment by nqb** [comment]
Yes for sure.

**Comment by nqb** [comment]
After all, having same behavior between Virtualbox and libvirt providers was not so hard to achieve. Done in #878.

I'm closing this issue, documentation will come later.
