### ISSUE TITLE
RFC: Switch to GPG keys stored in DebOps monorepo

### ISSUE THREAD

**Issue by drybjed** [debops/debops#856]
The SKS Keyserver network [has been successfully attacked](https://news.ycombinator.com/item?id=20312826) and there's a possibility of a DoS attack on the GPG keys retrieved from there in the future. Unfortunately, suggested replacement in the form of switching the keyserver to `keys.openpgp.org` has a drawback - [old versions of GnuPG don't work with identity-less keys served by this keyserver](https://keys.openpgp.org/about/faq#older-gnupg). One bright side in all this seems to be that at least [the Debian key infrastructure should be safe from this attack vector](https://news.ycombinator.com/item?id=20316318).

DebOps does not have this luxury - we don't have our own `.deb` package with the keyring that could store the keys used in various roles and come with the OS preinstalled. At the moment there are 29 uses of the `apt_key` Ansible module in the repository, but this still might be an attack vector in the future on the infrastructure managed by DebOps.

I don't want to set up a separate keyserver just for DebOps use, to keep the project decentralized as much as possible, and due to the lack of secure keyserver software - the `sks` package in Debian seems to be vulnerable to the same attack as the SKS Keyserver network (however `sks` should still be safe in internal, controlled environments), and the proposed replacement, [`hagrid`](https://gitlab.com/hagrid-keyserver/hagrid), is not yet available in Debian and won't be until at least Debian Bullseye, so in 2+ years.

I think that the next best thing we can do is include the GPG keys required to verify upstream software in the DebOps monorepo itself. There is a precedent for this already - the `debops.owncloud` role contains a set of GPG upstream keys and installs them for verification. I would not do it the same way though - I managed to successfully use the `lookup("file")` Ansible plugin to get the key data from the role directory, therefore this should be a portable method of handling this.

As far as for the trust aspect - the idea behind downloading the GPG keys not from the upstream site but from the keyserver network was that the keyserver network could act as a third-party between the DebOps user and the upstream. The key ids still were provided by the DebOps project though, and a change from downloading the GPG keys to getting them from the DebOps repository should not impact trust level, I think. The GPG keys committed in the repository would still have to be included via signed commits, so the trust path can be traced.

I'd like to hear your opinion on this. In the meantime, I'll prepare a pull request that switches all the GPG keys to the internal storage, should be up for a review in 1-2 days.

**Comment by nqb** [comment]
>  [the Debian key infrastructure should be safe from this attack vector](https://news.ycombinator.com/item?id=20316).

This link seems to be wrong.

**Comment by drybjed** [comment]
The link must have been truncated when I copied it, fixed now.

**Comment by nqb** [comment]
@drybjed: it sounds good for me.

**Comment by drybjed** [comment]
[The PR is up](https://github.com/debops/debops/pull/860).
