### ISSUE TITLE
debops.resources repositories does not support nonpublic repos

### ISSUE THREAD

**Issue by chymian** [debops/debops#882]
the role does not support cloning secured repos.
it does not take ssh-urls (auth per key would be possible)
when cloning https - urls, it hangs there without notice, waiting for name & password.

**Comment by drybjed** [comment]
I'm not sure about the `https://` URLs, I think that an API token specified as `https://<token>:random@github.com/org/repo` should work? As for SSH access, did you try specifying it as `git@github.com:org/repo`?

I'll test these cases out. Thanks for the bug report.

**Comment by chymian** [comment]
I'm running a selfhosted gitea.
the ssh URL: ssh://git@git.domain.org:29418/org/repo.git
the https-URL: https://git.domain.org/org/repo.git
I will check on token-based auth on gitea and report back

**Comment by chymian** [comment]
using an token in gitea, grants access to the whole account, which is not what I want.
the customer should get access to only one repo.
with deploy-keys per ssh this is possible for ro/rw

**Comment by drybjed** [comment]
Try removing the `ssh://` part from the SSH URL, perhaps that will work? But that probably means that you need to set up a normal UNIX `git` account. Not sure how that's done with Gitea.

**Comment by chymian** [comment]
removing the `ssh://` and cloning manually with `git clone` or `debops` doesn't work either.
additionally, with `git clone ssh://` ssh asks for accepting the fingerprint of the git-host, which interrupts the deployment of a fresh installed host. 
if you are going to implement the clone-per-ssh-function, can you pls. also add a ssh-fingerprint-item, which gets written into the users's known_hosts?

**Comment by drybjed** [comment]
This should be possible already by adding the `accept_hostkey: True` parameter in the configuration.

**Comment by chymian** [comment]
ok, the `accept_hostkey: True` which is not in the docu, as others, which I found, after your hint, in the monorepo `~/.local/share/debops/debops/ansible/roles/debops.resources/tasks/main.yml` made the task work with `ssh://…`

my working config is:
```
resources__host_repositories:
    - name: "DebOps setup for <customer>"
      repo: 'ssh://git@git.domain.org:29418/org/repo.git'
      owner: 'user'
      dest: '~user/repo'
      accept_hostkey: true
```

Thx for your support!

**Comment by drybjed** [comment]
The documentation mentions that you can use all parameters recognized by the `git` Ansible module. I'll add your example to documentation to make it easier to discover by other users.
