### ISSUE TITLE
Ansible dig lookups: wildcard considerations

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#905]
Not sure if this is really an issue, but we were kinda taken by surprise.

Some roles like `debops.icinga` and `debops.ldap` use an Ansible dig lookup to determine the hostnames of various services. `debops.ldap` for example queries `_ldap._tcp.<domain>/SRV` to figure out the hostname of the ldap server. if the DNS resolver returns an NXDOMAIN, the role will fallback to `ldap.<domain>`.

We didn't have an `_ldap._tcp.<domain>` SRV record. The `debops.ldap` role picked that up and used `ldap.<domain>` instead. That's all good! The problems started when we added wildcard MX and TXT records to our domain (`*.<domain>`) in order to more effectively combat email spoofing. This causes DNS resolvers to return not NXDOMAIN but NODATA answers for queries for the nonexisting `_ldap._tcp.<domain>/SRV` record. `debops.ldap` doesn't handle this well:

```
TASK [debops.ldap : Generate system-wide LDAP configuration] ********************************************
fatal: [stuxnet.bitsoffreedom.nl]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'value'"}
```

Maybe the dig lookup should check for NODATA responses as well?

**Comment by drybjed** [comment]
Sounds good to me. If I knew that `NODATA` could be another result like that, I would include it in the condition. `NODATA` is as useless for the role as `NXDOMAIN` so we can easily handle it that way.

Want to try and make a PR for this?
