### ISSUE TITLE
[stretch to buster] breaking changes for docker daemon

### ISSUE THREAD

**Issue by nqb** [debops/debops#910]
If you have installed a Debian Stretch with all defaults from `debops.docker_server`, an upgrade to Debian Buster and a subsequent run of `site.yml` breaks your setup. 

It looks like defaults of `debops.docker_server` install upstream packages on Stretch versus distribution packages for Buster (see https://github.com/debops/debops/blob/master/ansible/roles/debops.docker_server/defaults/main.yml#L41).

### Steps to reproduce
1. Install a Debian Stretch with all defaults from `debops.docker_server`
2. Run `debops tools/dist-upgrade -l server`
=> `docker-ce` and `docker-ce-cli` packages have been upgraded to Buster. All is working fine.
3. Run `debops site -l server`
=> `debops.docker_server` role uninstalled `docker-ce` and `docker-ce-cli` packages and try to install `docker.io` but failed.

As mentionned in [defaults](https://github.com/debops/debops/blob/master/ansible/roles/debops.docker_server/defaults/main.yml#L39), it seems a known behavior.

### Workaround
Force `docker_server__upstream` to `True` in inventory for Buster hosts before running `site.yml` playbook.

###

**Comment by nqb** [comment]
I wonder if it possible to save a fact related to upstream/distribution packages and rely on it to handle this case.

In my opinion, we should have a similar default behavior between stretch and buster.

**Comment by drybjed** [comment]
Agreed, facts were designed specifically with situations like this in mind - to keep the state between Ansible runs. Some of the other DebOps roles use them that way. The `debops.nodejs` role has a good example.

Want take a crack at it?

**Comment by nqb** [comment]
> Want take a crack at it?

Yes !
