### ISSUE TITLE
Deprecate role debops.bootstrap in documentation

### ISSUE THREAD

**Issue by debuglevel** [debops/debops#914]
debops.bootstrap was removed in this commit: https://github.com/debops/debops/commit/c4882063be23331671d3bc7adff395278eb8af37#diff-11421633c15c2bd6fa7150cabdcd19fe

But the documentation is still available (and Google is likely pointing you there) and a bit confusing if you try to change the default variables:
https://docs.debops.org/en/latest/ansible/roles/debops.bootstrap/introduction.html

It would be nice to note in this documentation that this role is not used anymore in the boostrap playbook.

**Comment by drybjed** [comment]
Good idea, thanks. I remove roles so unfrequently that I forgot about the documentation. :-) Will do as soon as possible.
