### ISSUE TITLE
One off bug involving sshd__moduli_minimum

### ISSUE THREAD

**Issue by apapsch** [debops/debops#924]
Debian Buster
Debops 1.0.5

The default value for `sshd__moduli_minimum` is `2048`. Looking in `/etc/ssh/moduli` on a debops prepared system, the smallest size entries are `3071` and the vanilla file in the buster package contains smallest entries with a size of `2047`. The modulus string is 512 byte long, which is a hexadecimally encoded number, decoded to a number of 256 byte (2048 bit). Therefore debops should filter the entries with a reported size <= `{{ sshd__moduli_minimum - 1 }}`.

**Comment by drybjed** [comment]
Thanks! This will have to be fixed in the `master` branch as well. I'll include it in the next release.
