### ISSUE TITLE
[debops.nginx] default PHP-FPM config breaks REST APIs

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#935]
The PHP-FPM configuration sections managed by `debops.nginx` contain this line:
```
limit_except GET HEAD POST { deny all; }
```
This limits the HTTP request methods accepted by nginx to GET, HEAD and POST. While this could be seen as a useful security feature and is probably harmless for most websites, it breaks parts of the HTTP core functionality required for REST APIs. For example, this week I was configuring a Passbolt server with debops.nginx, which seemed to work fine until I tried to register a new user. The last step in the user registration process involves the client sending a PUT request, which gets blocked by nginx and causes the client to hang.

The limit_except line can be disabled on a per-server basis, but is on by default. We should consider turning it off by default because of these kinds of unexpected side effects. The line can then be enabled per-server, and maybe we can add a variable for turning it on globally as well.

**Comment by drybjed** [comment]
I consider the `nginx` service to be "public" and accessible by default, in contrast to "private" services that should be secure by default and can be relaxed later. With regards to that - sure, changing the default limit to not block anything and allowing limits per `nginx` server configuration sounds good. It could be defined as `item.php_limit` boolean parameter, which by default limits to just `GET`, `HEAD` and `POST`, and optional `item.php_limit_except` list can be defined that lets you pick your own set. Want to try and make a PR?

As for setting this globally, I'd like to avoid that option. This could cause unitended consequences when you either limit too much by default, or give too much access to something that shouldn't have it. Per-service configuration sounds safer.

**Comment by imrejonk** [comment]
Thanks @drybjed, I'll give it a try!

If we're not globally setting a default limit_except list, wouldn't it be better to just leave the `item.php_limit_except` list empty and skip the `item.php_limit` parameter? That way we can avoid choosing what should be limited/permitted when the user decides to enable `item.php_limit`. Might also be less confusing.

**Comment by drybjed** [comment]
If you enable limiting but don't specify what to "except" from the limiting, you will block everything. That's why a default of `GET`, `HEAD` and `POST` is there in the first place. This is for the case when the user enables limiting but does not specify what to except from such limit.

**Comment by imrejonk** [comment]
Let me explain myself by way of pull request #942. There is just one limit_except-related parameter called `item.php_limit_except`. If it's absent, empty or False, no limits will be applied. If it contains a string or list of strings containing a request method whitelist, the role will apply said whitelist in a limit_except line. If it's True, the role will fail with this error message: `'bool' object is not iterable`. That should prevent an accidental block of all request methods.

We can also skip the boolean part in the documentation and just default to an empty string. Then there's no need to tell the user that they can set the parameter to False as well (which implies that it can be True). Let me know what you think...
