### ISSUE TITLE
[debops.system_users] error with bootstrap playbook

### ISSUE THREAD

**Issue by nvdsteen** [debops/debops#941]
While running the bootstrap playbook, I get the error: 

> fatal: [VM -> localhost]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "Usage: getent_passwd.py3 <user>\n", "stdout_lines": ["Usage: getent_passwd.py3 <user>"]}

I'm using the debops docker image to manage a ubuntu 18.04 VM (virtualbox). Initially, I get the error that `/usr/bin/env python3` is not found. Which I "solved" by installing python3 in the docker container.

**Comment by drybjed** [comment]
Thanks for the heads-up! I'm currently slowly moving DebOps towards Python3-only operation, but I haven't looked at Docker environment yet. I'll update it soon.
