### ISSUE TITLE
[debops.ldap] Python 3 compatibility issue when updating SSH host public keys

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#980]
I'm running the sshd playbook against an LDAP-enabled host, which triggers a dependent run of the `debops.ldap` role. This fails inside a Python 3.7 virtualenv:

``` 
TASK [debops.ldap : Update SSH host public keys in cn=orbit.gwl.amsw.nl,dc=amsw.nl,ou=Hosts,dc=amsw,dc=nl] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: ('Tuple_to_LDAPMod(): expected a byte string in the list', 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDLclv4frtilJ8EwcP/FXnysY8QGdElaKzCEzG2uovxeqdCI1lVFozEppyGfO6uyBqZ+8a3IgfbyPxDpZwWgAPQ= root@orbit')
fatal: [orbit.gwl.amsw.nl -> localhost]: FAILED! => changed=false 
  details: '(''Tuple_to_LDAPMod(): expected a byte string in the list'', ''ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDLclv4frtilJ8EwcP/FXnysY8QGdElaKzCEzG2uovxeqdCI1lVFozEppyGfO6uyBqZ+8a3IgfbyPxDpZwWgAPQ= root@orbit'')'
  msg: Attribute action failed.
```

Running the playbook again in a Python 2.7 virtualenv worked for me. Tested with DebOps v1.0.7.

**Comment by drybjed** [comment]
I suspect that [the `ldap_attrs` script](https://github.com/debops/debops/blob/master/ansible/roles/debops.ansible_plugins/library/ldap_attrs.py) needs to be fixed to work on Python 3. Probably missing `decode('utf-8')` somewhere and the like. I'll try to fix that before the next release, thanks.

**Comment by drybjed** [comment]
This should be fixed by https://github.com/debops/debops/pull/988 and https://github.com/debops/debops/pull/991, closing.
