### ISSUE TITLE
Docker storage driver should be overlay2 in buster

### ISSUE THREAD

**Issue by lhernanz** [debops/debops#987]
According to [https://docs.docker.com/storage/storagedriver/select-storage-driver/](https://docs.docker.com/storage/storagedriver/select-storage-driver/), the recommended driver for modern docker is `overlay2`. The current configuration in [https://github.com/debops/debops/blob/master/ansible/roles/debops.docker_server/defaults/main.yml](https://github.com/debops/debops/blob/master/ansible/roles/debops.docker_server/defaults/main.yml) sets it to `overlay` instead:
```
docker_server__storage_driver: '{{ "aufs"
                                   if (ansible_distribution_release in ["wheezy", "jessie" ])
                                   else "overlay" }}'
```

**Comment by drybjed** [comment]
Sounds good to me. I'l be messing in `debops.docker_server` to fix some things, so I can do this as well before the next stable release.

Do you know if there are any ill effects when the storage driver is changed on existing systems? Or should the value be preserved to not disrupt them?
