### ISSUE TITLE
[debops-tools] Deprecation warning in debops-init

### ISSUE THREAD

**Issue by nqb** [debops/debops#989]
Hello,

After doing a `vagrant up` in root directory, I notice following error message:
```
master: Creating new DebOps project directory in src/controller ...
master: /usr/local/bin/debops-init:165: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
master:   platform.linux_distribution()[0].lower() in ("debian", "ubuntu")):
```
This is certainly caused by #982 because now we installed `debops` with `pip3`.

### Steps to reproduce

1. `vagrant up` in root directory
2. `mkdir myproject; cd myproject`
3. `debops-init test`

### Actual results
Deprecation warning message.

### Expected results
No deprecation warning.

### Additional informations

```console
$ whereis debops-init
debops-init: /usr/local/bin/debops-init

$ head -n1 /usr/local/bin/debops-init
#!/usr/bin/python3
```

In upstream, first line of `debops-init` is:
https://github.com/debops/debops/blob/bb3fcbb7bdd1f0f31f492cdb9d69a9f493d46210/bin/debops-init#L1

However, if I use : `/usr/bin/env python` on controller, I got a Python2 shell.

**Comment by drybjed** [comment]
Yeah, I saw that too, just haven't got time to get to that yet. The script must be updated to use new functions to check the OS platform and distribution. Want to try and provide a fix?

**Comment by nqb** [comment]
> Want to try and provide a fix?

Yes but during September not before.

I take a look and the best way seems to switch to [distro python package](https://docs.python.org/3/library/platform.html#unix-platforms) as Ansible project did for 2.8.
